F5Networks/k8s-bigip-ctlr

- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/kubernetes_one_svc_two_nodes.json
- python/tests/test_k8scloudbigip.py
Problem: The config driver only handled IPv4 Addresses, which ended in the form
':port', whereas IPv6 Addresses end in the form '.port'.
Solution: Correctly configure IPv4 vs IPv6 addresses.
> Configure IPv6 Adddresses properly

- pkg/appmanager/appManager.go
- python/bigipconfigdriver.py
Problem: With the recent Ingress additions, we stopped creating Pools if
the pool members were gone. This is incorrect behavior.
Solution: Still create pools even if members are gone, and handle an empty
pool member array in the python driver. Correctly print a log message when
there are no pool members configured.
Fixes #227
> Create pool even if pool members are gone

- pkg/appmanager/appManager.go
Problem: There was an issue where the controller attempted to access an informer for
a specific namespace, even though the controller was watching all namespaces. This
resulted in a nil pointer reference.
Solution: Use the proper informer if we are watching all/specific namespaces.
Fixes #231
> Don't access specific namespace when watching all

- build-tools/python-tests.sh
- build-tools/rel-build.sh
- python/.coveragerc
Problem:
- Repository did not post coverage to coveralls.
Solution:
- Updated build-tools to support coverage data using BUILDDIR variable to produce coverage data for coveralls on builds.
- Added coveragerc file to set python coverage data configs.
fixes #221
> Add combined Go/Python coveralls

- python/bigipconfigdriver.py
Problem:
config object has been changed to config['resources']['<resource>'] and
the scale test data processing block was not updated causing log time
out errors during the tests.
Solution:
change to correct indexing in test data processing block to prevent
key errors resulting in test failures.
Fixes: #235
> Fixed test data indexing.

- build-tools/Dockerfile.runtime
Problem: We don't want container processes to be run as root.
Solution: Add a user to the runtime container and run processes as this user.
> Run controller as non-root

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Changes have been made to the _f5.py get_pool() function to take an additional param subpath for iapps.
The f5cccl sha in python/k8s-build-requirements.txt and python/k8s-runtime-requirements.txt has been updated for this.
> upgrade _f5.py to include fix for get_pool() func

- docs/RELEASE-NOTES.rst
Problem:
The release notes need to be updated for the new release.
Solution:
Changed the latest release to v1.1.0 and added features new to the
release.
> Update release notes for v1.1.0

- .travis.yml
- build-tools/deploy-docs.sh
- docs/RELEASE-NOTES.rst
Problem:
- travis-ci lacked ability to push docs to aws for release
Solution:
- added deploy section to .travis.yml
- added deploy-docs.sh
fixes #239
> travis able to publish docs to aws

- .travis.yml
Problem:
Travis builds did not post to repo slack channel.
Analysis:
Notifications are configured for the F5Networks namespace, meaning that pushes to branches on a pull request will send notifications, but pushes to branches pre-pull request will not. Notifications are sent on success as well as failure since there is not a "merge when build succeeds" as in GitLab.
Solution:
Generated "secure" key using travis cli tool and added notifiaction section to `.travis.yml` to post build notices to repo slack channel.
> add slack build notifications

- build-tools/attributions-generator.sh
- build-tools/docker-docs.sh
Problem:
Build supporting images need to pull from DockerHub for GitHub build
Solution:
Changed references in to use DockerHub image.
> remove references to gitlab registry

- .travis.yml
- docs/RELEASE-NOTES.rst
@michaeldayreads 
Fixes #244 
Docs deployment to s3 failed in [travis build 62](https://travis-ci.org/F5Networks/k8s-bigip-ctlr/builds/253803406).
The deployment failed because the docs build wasn't included in the script section of the travis config file. I have added it in and addressed some issues in the RELEASE_NOTES to ensure the docs build passes.
> Fixes #244 - docs build missing from travis

- README.md
- docs/README.rst
- docs/RELEASE-NOTES.rst
- docs/conf.py
Problem:
Product names were not meeting F5 guidelines.
Solution:
Changed product name references in all documentation per guidelines
using templates when available.
> Change product name per new guidelines

- .f5license
- Godeps/Godeps.json
- vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
- vendor/k8s.io/client-go/pkg/api/helpers.go
- vendor/k8s.io/client-go/pkg/api/v1/helpers.go
- vendor/k8s.io/client-go/pkg/apis/batch/types.go
- vendor/k8s.io/client-go/pkg/apis/batch/v2alpha1/generated.proto
- vendor/k8s.io/client-go/pkg/apis/batch/v2alpha1/types.go
- vendor/k8s.io/client-go/pkg/apis/batch/v2alpha1/types_swagger_doc_generated.go
- vendor/k8s.io/client-go/pkg/version/base.go
- vendor/k8s.io/client-go/rest/config.go
- vendor/k8s.io/client-go/tools/clientcmd/client_config.go
- vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go
Problem:
Upgrade the client-go package to the latest release version.
Solution:
The client-go package version used previously was required for the
shared informer functionality, but was a pre-release version. The
release version is now available, and is required to support the
upcoming OpenShift changes we are making.
> Upgrade client-go to v3.0.0 release

- docs/README.rst
- docs/conf.py
Problem:
The docs build emits the following warnings and the resulting html
docs don't have the proper substitution for |project|:
WARNING: Undefined substitution referenced: "project".
Solution:
Per the Sphinx docs, |project| is not available as a substitution.
Added explicit variables with the short and long name for the product
and used these where needed.
> Fix improper substitution for "|project|"

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
Problem: The controller needs to be able to load SSL certificates from
Kubernetes Secrets and configure custom profiles on the BIG-IP.
Solution: Enable the controller to search for Secrets in Kubernetes, as defined in the sslProfile field in ConfigMaps,
or tls secretName field in Ingresses. Process the cert and key from the secret and manually create an SSL-profile on
the BIG-IP.
> SSL certificates from k8s secrets

- build-tools/Dockerfile.runtime
Problem: Dockerfile steps that would change most often were being called
in the middle of the Docker build process, before dependency installation.
This caused dependencies to be installed every time a change in our code happened.
Solution: Take advantage of Docker caching and install dependencies first, before
any copying of files.
> Move Dockerfile common steps towards end of file

- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/kubernetes_invalid_svcs_expected.json
- python/tests/kubernetes_no_apps_expected.json
- python/tests/kubernetes_one_iapp_expected.json
- python/tests/kubernetes_one_svc_four_nodes_expected.json
- python/tests/kubernetes_one_svc_one_node_expected.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only_expected.json
- python/tests/test_bigipconfigdriver.py
- python/tests/test_k8scloudbigip.py
Changes to the k8s-bigip-ctlr:
- Creation of a CCCL instance for each managed partition
- Modified create_ltm_config_kubernetes() to create CCCL-compliant schema
- Converted python unit tests
Note: This is an interim step. Currently, the creation of a BIG-IP configuration
occurs in two pieces: the golang frontend creates a config file from the
relevant configmaps and service descriptions, then the python backend performs
another conversion before passing the desired config to CCCL. The goal is to
create the CCCL-compliant BIG-IP config in one step within the golang frontend
of k8s-bigip-ctlr. Most importantly, this commit removes the dependency upon the
legacy f5-cccl/f5_cccl/_f5.py implemention.
> Integrate Kubernetes BIG-IP Controller to use CCCL and CCCL Schema

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/types.go
- pkg/appmanager/validateResources.go
- pkg/test/utils.go
- python/bigipconfigdriver.py
- python/tests/kubernetes_invalid_svcs.json
- python/tests/kubernetes_invalid_svcs_expected.json
- python/tests/kubernetes_one_iapp.json
- python/tests/kubernetes_one_svc_four_nodes.json
- python/tests/kubernetes_one_svc_four_nodes_expected.json
- python/tests/kubernetes_one_svc_one_node.json
- python/tests/kubernetes_one_svc_one_node_expected.json
- python/tests/kubernetes_one_svc_two_nodes.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only_expected.json
Add Route object support for OpenShift. This allows users to create
Route objects that are translated into BIG-IP resources and policies
for routing traffic.
Add unit test utilities and tests for managing Route objects.
Also moved an Ingress unit test to its proper location in resourceConfig_test,
which is where a similar unit test for Routes lives.
> Route support for OpenShift

- build-tools/Dockerfile.builder.dbg
Problem:
Builds can fail due to gpg key server errors.
Solution:
Add redundancy to the gpg key retrieval step so that a reasonable number of servers are tried in succession, with the build proceeding at first successful retrieval.
Tests
In addition to CI builds on k8s-bigip-ctlr, also confirmed local builds using top of tree for k8s-bigip-ctlr and f5-cccl succeed:
- in f5-cccl ` ./build-tools/system-test-img.sh michaeldayreads/k8s-bigip-ctlr 6c160ec "make prod" michaeldayreads f5devcentral/f5-cccl.git@02e2160124e208dfec5a1ac657b8ba6f078d3907`
- img at https://hub.docker.com/r/michaeldayreads/cccl/tags/
> add redundancy to gpg key retrieval

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
- python/tests/kubernetes_invalid_svcs_expected.json
- python/tests/kubernetes_no_apps_expected.json
- python/tests/kubernetes_one_iapp_expected.json
- python/tests/kubernetes_one_svc_four_nodes_expected.json
- python/tests/kubernetes_one_svc_one_node_expected.json
- python/tests/kubernetes_one_svc_two_nodes.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only_expected.json
Problem:
The controller needs to support SSL passthrough termination to achieve
paritiy with the OpenShift F5 Router.
Solution:
SSL passthrough is achieved by using an iRule to look at the SNI
information to get the target server name. The iRule uses internal
data groups that contain information that allows the iRule to map the
server name to the correct pool and then pass the connection through
unencrypted to that pool. The iRule itself was copied from the
OpenShift F5 Router verbatim. To support all of this new functionality,
the controller was modified as follows:
1. Added support for the 'iRules' section in the output configuration.
2. Updated the Virtual struct to include an array of fully-qualified
iRule names in the form of '/Partition/iRuleName'.
3. Added support for the …
> Add support for SSL passthrough termination

- docs/README.rst
- docs/_static/config_examples/sample-rbac-cc-deployment.yaml
- docs/_static/config_examples/sample-rbac-clusterrole.yaml
- docs/_static/config_examples/sample-rbac-clusterrolebinding.yaml
- docs/_static/config_examples/sample-rbac-serviceaccount.yaml
Problem:
Sample configs for using k8s-bigip-ctlr with rbac (k8s >= 1.6) were not included.
Solution:
Added sample configs.
Testing:
Tested existing document examples in a k8s 1.6 kubeadm deployment.
> Add rbac sample configs

- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
Problem: Default pools were being set on virtual servers for Ingress
and Route configuration. This would mean that if traffic for a specific host/path
didn't match any rules, it would still be forwarded to the default pool. This is
incorrect behavior. If traffic doesn't match a rule, then it shouldn't go to any pool.
Solution: Remove the default pool in the case of multi-service Ingress and Routes.
Fixes #288
> Remove default pool for Ingress and Routes

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
Problem: The action location parameter for our https redirect rule only
works in BIG-IP version 12.0.0+. Version 11.6.1 has a different format.
Solution: Use a generic iRule instead of a policy rule to set the http
redirect. This works in both BIG-IP versions.
> Use iRule to support http redirect in 11.6.1

- build-tools/Dockerfile.rhel7.runtime
- build-tools/build-release-images.sh
- build-tools/help.md
Problem: There are a few additional pieces for the RHEL based image
to meet expectations, including the license and help.md files.
Solution: Add the license, help.md, and an additional description label
to the built release image.
> Additional Dockerfile steps for RHEL based image

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/routing_test.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
- python/tests/kubernetes_invalid_svcs_expected.json
- python/tests/kubernetes_one_svc_four_nodes_expected.json
- python/tests/kubernetes_one_svc_one_node_expected.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
Problem:
Add support for OpenShift reencrypt routes
Solution:
The main focus of this fix is the addition of reencrypt route support
in OpenShift, which required several other changes:
1. Added server SSL profile support to bigipconfigdriver.py and
refactored existing SSL profile related code for reuse.
2. Added support for server SSL profiles in the controller, including
the ability to attach them to virtual servers.
3. To improve configuration consistency, route objects are now sorted
before they are processed by syncRoutes(). The sort order is by
namespace/service/path.
4. Refactored createRSConfigFromRoute() to better handle the
commonality between create and update modes while adding support for
reencrypt routes.
5. OutputConfigLocked() now looks at server profiles when satisfying
the …
> Add support for re-encryption termination for OpenShift routes.

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem:
1. Need to add functionality for the route-label cli argument.
2. There is a bug when configuring routes using the first service port we see,
as all route configuratiosn end up using this port, which is wrong.
Solution:
1. Add a watcher for route labels if they are provided. The label on the Route config
should be of the format 'f5type: label', where label is provided in the --route-label cli
argument. Default is to watch all routes.
- Also removed the route-default-server-cert argument, as it is not needed.
2. Set specific expectations around configuring the backend service port, rather than just
grabbing the first we see. The expectations are:
- If a port is provided in the Route config, use it.
- Else if the Route is of type passthrough or reencrypt, port is set to 443
- Else …
> Add route label watcher; set backend port properly

- build-tools/Dockerfile.rhel7.runtime
- build-tools/run-in-docker.sh
Problem: The devel image in rhel7 did not have permission to
access the filesystem. The release image in rhel7 was removing
setuptools, which is needed in CCCL.
Solution: Add the 'Z' flag to the Docker run volume mount. Keep setuptools
in the release image for CCCL to use.
> Fix rhel7 devel permissions; keep setuptools

- cmd/k8s-bigip-ctlr/main.go
- docs/README.rst
- docs/_static/config_examples/sample-edge-route.yaml
- docs/_static/config_examples/sample-passthrough-route.yaml
- docs/_static/config_examples/sample-reencrypt-route.yaml
- docs/_static/config_examples/sample-unsecured-route.yaml
Problem:
The product documention needs to be updated to cover OpenShift Route
resources.
Solution:
Added key information regarding OpenShift Routes to the product
documentation, including examples. Removed hidden attribute from new
controller parameters.
> Add OpenShift Route resources to product documentation.

- pkg/appmanager/appManager.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
Problem: SNIDefault was not being set for custom profiles when configuring
https Routes. The server name was set, but a default SNI was not.
Solution: Set the default SNI for the first custom profile for a virtual server.
All subsequent profiles for that same virtual server will not be set for default SNI.
> Fix SNIDefault for Routes

- docs/README.rst
Problem: Need to inform users what the expectations for backend exposed ports
are for the different Route types.
Solution: Clarify the use of port 443 for Passthrough and Re-encrypt Routes and port 80
for all others. Also mention that custom ports should be specified in the Route config.
> Port specifications for Route Types added to docs

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update to version of CCCL that ensures immutable parameters
of Nodes and Virtual Addresses are not passed in BIG-IP 'update'
operations.
> Update CCCL version

- README.md
- cmd/k8s-bigip-ctlr/main.go
- pkg/pollers/nodePoller.go
- pkg/pollers/nodePoller_test.go
Problem: If you use `nodeport` (which is the default) per default all nodes from the cluster will be added to the pool. In some cases you only want to use a subset of these nodes (e.q. only nodes with the label `node-role.kubernetes.io/node`) because not all nodes are reachable by the F5 or the nodes are already managed by F5 (but nor the Plugin). Currently we use to F5 to load balance traffic to the API servers (HA setup), this means that the Kubernetes master nodes are already present in F5 if you start the bigip-ctlr without a nodeLabelSelector the creation of the node pool for Kubernetes will fail since the bigip-ctlr can't create nodes that are already present.
> Add node label selector

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager_test.go
- pkg/appmanager/validateResources.go
Problem: When using a kubernetes ingress class other than "f5", the controller
hit a segfault, due to trying to access a field in a nil struct.
Solution: Change the way the required value is grabbed, and use outputConfigLocked instead of
outputConfig, since the calling function is already locked.
Fixes #311
> Fix SIGSEV on non-"f5" valued class annotation

- Makefile
- docs/README.rst
- docs/conf.py
We need to document the existing and upcoming functionality the controller provides in OpenShift environments.
The documentation has been updated and edited as needed to support the new functionality.
Staged docs are online at staging site (/products/connectors/k8s-bigip-ctlr/elbert/index.html).
> openshift feature parity docs 

- docs/README.rst
Problem: Missing documentation for the new CLI option that allows for specifying a node label
for the controller to watch for.
Solution: Added the CLI description to the README.
> Node label selector CLI docs

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/test/utils.go
Problem:
The controller sometimes wishes to identify Unschedulable nodes in order
to prevent sending traffic to them - traffic that is guaranteed a second
hop.
In 1.6 Taints are beta and fully supported in 1.7. Nodes may no longer
be marked Unschedulable but be tainted as NoSchedule. Creating the same
behavior but failing the controller test of watching the Unschedulable
field.
Solution:
Update controller to look for and prefer the Node.Spec.Taint setting and
then defer to the Node.Spec.Unschedulable setting - if a node selector
label has been configured appManager will ignore taint.
Tests: new unit tests, and test_restore.py / test_e2e.py
Fixes #321
> Controller should support Node Taints for k8s 1.6

- python/bigipconfigdriver.py
Problem:
k8s-bigip-ctlr scaletests were failing due to object renaming when the
uplift to CCCL was made.
Solution:
Update the logging code in the controller for the scaletests to reflect
the name changes.
> Fixed scaletest logging.

- pkg/appmanager/appManager.go
Problem: The log informing users that the SSL profile name provided couldn't be
found as a Secret and instead is used as a regular path was misleading. Users may think
there was an error if a normal path is provided, even though there wasn't.
Solution: Add this log into DEBUG rather than INFO, and clear up the message.
Fixes #326
> Change Secret SSL profile log to be DEBUG

- cmd/k8s-bigip-ctlr/main.go
- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem: Routes in multiple namespaces were not supported, since a single IP address is supplied
to the controller, and therefore would cause conflicts when attempting to create a new set of virtuals
for a new namespace.
Solution: Rename the virtuals for OpenShift Routes, and only create 2 vservers for all routes in all namespaces.
Fixes #331
> Support Routes in multiple namespaces

- cmd/k8s-bigip-ctlr/main.go
- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
Problem: The controller was using the first https route's cert/key
as the default for SNI for the https virtual server. There was a bug
that either caused none of the Routes to be used, or more than one.
Upon further discussion, we concluded that we don't want to use the Routes'
certs/keys as the default SNI profile, and instead a generic or user-specified default.
Solution: Route certs/keys will no longer be used as default SNI profiles for the https
virtual server. Instead, we will allow the user to create client and server ssl profiles and
specify them via CLI. If none are specified, the controller creates a generic profile, inherited
from either the clientssl or serverssl profiles, and use those as default for SNI.
> Create default client and server profiles for SNI

- build-tools/docker-docs.sh
- build-tools/make-docs.sh
Problem:
linkcheck fails due to links in release notes not
yet live.
Solution:
Remove RELEASE-NOTES.rst file prior to linkcheck. The html file has
already been generated at this point and the source is no longer needed.
Testing:
Tested that the following command passed linkcheck with changes (these
failed previously):
./build-tools/docker-docs.sh build-tools/make-docs.sh
Fixes: #337
> Exclude release notes from docks link checker

- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
Problem: When services or routes with the same names were created in different namespaces,
this created a myriad of problems.
1. The client ssl certs would clobber each other due to the
naming.
2. Pool members would not be populated for a second service if the service name
was the same as another.
3. Internal data groups were not deleted
Solution:
1. Change the name of client ssl certs to be namespace and route specific.
2. Make more namespace adjustments to handle services with the same names.
3. Remove internal data groups when the associated routes are deleted.
4. Handle data groups for different namespaces.
Fixes #335, #336
> Various OpenShift Route namespace bug fixes

- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
Problem: When using a pre-existing config as a base for a newly processed config,
the controller would copy by reference instead of value. This resulted in the config from
the cache being updated whenever the newly processed config was updated, keeping both configs
in the same state. This prevented updates from happening.
Solution: Use golang's builtin copy method to copy by value instead of reference.
Fixes #339
> Fix copy by reference bug

- docs/RELEASE-NOTES.rst
Mentioned the limitation that the controller currently cannot specify individual
redirect policies per route. Redirect applies to all routes on the virtual
> Add redirect limitation to Release Notes

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
Problem: If a port was updated on a Route object, the controller would not update the corresponding
Pool with the new port. There was also an issue that if one Route had an inactive pool, the controller
would deactivate all stored configs when attempting to equalize them.
Solution: Update an existing pool if the port changes. Also, if a pool becomes inactive, don't deactivate
all other stored configs for the Route virtual servers. Simply keep the active state for all other configs.
Fixes #346
> Fix port update for Routes

- docs/RELEASE-NOTES.rst
Problem: The 1.2.0 release added support for Kubernetes 1.7 but it isn't
noted in the relnotes (it is noted in the docs version compatiblity
matrix)
Solution: Add a bullet to the relnotes.
affects-branches: 1.2-stable
> Add Kubernetes 1.6 and 1.7 support to release notes.

- .travis.yml
- Jenkinsfile
- Makefile
- build-tools/_build-lib.sh
- build-tools/build-debug-artifacts.sh
- build-tools/build-release-artifacts.sh
- build-tools/fmt.sh
Problem: The travis build was taking a long time due to the devel containers
being built more times than necessary.
Solution: Remove unnecessary devel builds. Also specified the number of compilers
used in the Ginkgo build. This *may* help with ginkgo run times, though
that has yet to be seen.
> Improve travis build times

- .travis.yml
Problem:
The previous commit to add support for version agnostic
deploy documentation missed adding the version prefix 'v'.
Solution:
Added missing version prefix.
Testing:
Ran these changes on the stable branch to see that the docs deploy step
was executed.
affects-branches: master, 1.2-stable
> Add missing version prefix while deploying docs

- README.md
Problem:
Coveralls badge pointed at "master" is showing coverage is "unavilaable".
Solution:
Use `?branch=HEAD` to indicate which number to post.
> Fix coverage badge reference

- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing_test.go
- pkg/appmanager/types.go
- pkg/test/utils.go
Problem: Users may not want to use the certs/keys exposed in the Route resource
configuration. Instead, a user wants to use a pre-defined profile from the BIG-IP
to be linked to the Route.
Solution: Add annotations for Route resources to allow users to specify profiles on the BIG-IP
to use instead of creating a custom profile from the certs/keys within the Route config.
> Client and server ssl annotations for Routes

- .travis.yml
- build-tools/build-release-images.sh
Problem:
- Dockerhub images did not have "latest" tag
- images need to be able to be specifically referenced in automated regression tests
Solution:
- Updated tagging to included latest
- Added timestamp to build tag and included that information as a docker label to make it available to docker inspect in regression set up.
> Add docker latest tag and docker label to allow pinned image for tests

- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/test_bigipconfigdriver.py
- python/tests/test_k8scloudbigip.py
Moved code that configures vxlan tunnels and custom profiles via the f5-sdk
to CCCL and removed the dependency upon the f5-sdk and f5-icontrol-rest.
> Remove f5-sdk dependency from K8s/OS ctlr

- Jenkinsfile
Problem:
rhel image build process did not export BUILD_STAMP for regression tests to pin image.
Solution:
Added BUILD_STAMP to rhel build using same labeling conventions for other rhel tags.
> Add BUILD_STAMP to rhel image

- cmd/k8s-bigip-ctlr/main.go
- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
Problem: Users may be uncomfortable with the controller looking for Secrets for custom SSL
profile loading. Even if a user doesn't provide a secret name to the Ingress or ConfigMap,
the controller still looks for a secret before defaulting to a BIG-IP profile.
Solution: Add a CLI flag to disable the controller from ever trying to look for Secrets to
load SSL profiles from. By default, this flag is enabled to true (backwards compatability),
but the user can set to false if desired.
> Allow users to disable Secret SSL loading

- docs/README.rst
Problem:
1. Ingress partition annotation was listed as required, but is optional.
2. OpenShift Route port information was not quite clear.
Solution:
1. Listed the partition annotation as optional.
2. Cleared up some ambiguity with the Route port information.
Fixes #367
> Product doc fixes

- docs/README.rst
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem: OpenShift users would need to hard code a Route's targetPort if the port was
something other than what we already assumed. This was an inconvenience for the user. The controller
also would not recognize port names, such as "8080-tcp", rather than port numbers. The OpenShift
GUI creates Routes in this manner.
Solution: The controller will now accept port numbers or port names in the targetPort field
in a Route config. If this field is not provided, then the controller will grab the first port
off of the service that the Route references.
Fixes #350
> targetPort flexibility for Routes

- docs/README.rst
Problem: Configuration parameters in the README were in random order and hard to follow.
Solution: Alphabetized the arguments and organized them by category. The ordering/organization now mimics what a user would see if they were to print the help text when running the controller.
> Alphabetize and organize CLI arguments in docs

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Incompatibility with policy rules fixed in f5-sdk 3.0.3, update
requirements to point to new CCCL version.
> CCCL incompatible with BIG-IP v11.6.1 policies

- docs/RELEASE-NOTES.rst
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Problem: Certificate and key files are not being cleaned up when their associated
profiles are deleted.
Solution: CCCL now removes these files when profiles are removed.
> CCCL update to remove cert/key files

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/routeDomain.go
- pkg/appmanager/routeDomain_test.go
- pkg/appmanager/schema.go
- pkg/appmanager/schema_test.go
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- schemas/bigip-virtual-server_v0.1.4.json
- schemas/test/test-bigip-virtual-server.js
- schemas/test/util/schema-handler.js
Problem:  Need to make sure controllers handle Big-IP addresses that
have optional route domain IDs specified.
Solution: Allowed virtual address field to contain route domains by
updating schema to define Bigip IP formats that include
route domains.
> Added non-0 route domain support

- .f5license
The urllib3 and chardet packages were bundled inside of requests and were
not attributed correctly. Properly attribute the licenses for these packages.
> License info for urlib3 and chardet

- build-tools/Dockerfile.rhel7.runtime
Problem: RedHat pushes security updates out and requires they be installed into
all images in their catalog.
Solution: Have microdnf update container packages to ensure that the latest security
packages are installed when the RHEL image is built.
> Update microdnf packages during rhel build

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/types.go
Problem:
The configuration data structure has become unruly and needs to be
simplified.
Solution:
The following changes were made to the configuration data structure:
1. Only one copy of the resource configuration is stored, instead of
one per backend.
2. Struct members that are not part of the CCCL schema but still
required internally are no longer serialized.
3. Many of the configuration structures have changed to be close to the
output CCCL format, which requires fewer transformations between
formats. Moved format conversions out of the config writing code and
instead initialize the structs correctly when they are created.
4. Client SSL profiles are now stored along with server SSL and other
profiles in the Profiles array.
5. The Virtual struct no longer contains members for IApps, as …
> Refactor internal configuration data structure.

- pkg/appmanager/routing.go
Problem:
CCCL 'loses' leading and trailing whitespace, and therefore constantly
needs to push the IRule to the BIG-IP.
Solution:
CCCL issue 183 addresses the CCCL bug, but this commit removes leading
and trailing whitespace from the 2 existing IRules to avoid the issue.
Fixes #410
affects-branches: master, 1.3-stable
> IRules with leading or trailing whitespace sync constantly

- docs/README.rst
Added UDP as an option for virtualServer mode and health-monitor
protocol; supported in v0.1.5 of the schema.
> VEL-1183: Document UDP support in k8s-bigip-ctlr

- pkg/appmanager/outputConfig.go
- python/bigipconfigdriver.py
Problem: When debug logging, customProfiles were removed from the resources struct. This could cause future syncing issues because we removed a reference to the profiles, so our internal store was in an incorrect state.
Solution: Don't touch the resources blob when attempting to alter what is logged (customProfiles in this case). Instead, create a value copy of the resources into a new struct, leaving out the profiles. Log this new copied struct, which avoids us from altering our internal store.
Fixes #365
> Create resource copy for debug logging

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
Problem:
The controller was creating only one event broadcaster for all
namespaces, which is not correct. This causes errors when broadcasting
events once an event is generated for a second namespace.
Solution:
1. Added some new infrastructure to support one event broadcaster per
namespace.
2. Moved all of the event notification code to eventNotifier.go.
3. Updated existing Ingress tests to validate events.
4. Added a new unit test to validate the new one event broadcaster per
namespace functionality.
5. Updated some methods in mockAppManager for Ingress objects to update
the fake kube client with Ingress objects to allow the correct code
path for events to be followed (like it happens in production).
6. Some cleanup around the Params structure where it was allowing
public access to …
> Ingress events for multiple namespaces are confusing

- pkg/appmanager/outputConfig.go
Problem: IApp pool members were not properly being added to the ARP table.
Solution: Add IApp pool members to the ARP table.
> Add IApp pool members to ARP table

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Problem: The "source" field on virtuals was missing a route domain, causing a discrepancy
between route domains on source and destination fields.
Solution: Update the CCCL sha with the fix for this bug.
> Update CCCL sha for route domain source fix

- .travis.yml
- Makefile
- cmd/k8s-bigip-ctlr/main.go
- Log the version and build info when the controller starts
- When building from a tagged CI build, use the version from the
tag instead of the one from next-version.txt
> Add version and build info to Docker container

- Jenkinsfile
Problem:
- Jenkinsfile that builds rhel image invokes `build-tools/build-devel-image.sh` which in turn invokes `build-tools/_build-lib.sh` which expects `BUILD_VERSION` and `BUILD_INFO` env vars, which are not present.
Solution:
- Added version tool invocations to Jenkinsfile.
fixes #453
> Add version information to rhel image build

- docs/README.rst
- docs/_static/config_examples/example-vs-resource-udp.configmap.yaml
Problem:
- Virtual Server Resource backend table did not include health monitor information.
- Recv field added by #444 were not yet documented.
Solution:
- Added health monitor details for supported fields to backend table.
- Added recv field documentation to ingress/routes.
- Reordered ingress/route health annotations to reflect order of fields on health monitors within BigIP ui.
fixes #388
> Update docs for config health monitors, recv field

- python/bigipconfigdriver.py
Problem: SSL profiles were being managed by our NET CCCL, which would attempt
to add/delete profiles from the Common partition (if your tunnel was defined there).
Solution: Only manage ssl profiles with the LTM CCCL instances. This guarantees that Common
profiles are not being touched.
This will be removed once CCCL fully supports SSL profiles.
> Only manage ssl profiles with LTM CCCL

- docs/RELEASE-NOTES.rst
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/test_k8scloudbigip.py
Problem: The controllers can fail to create the appropriate
resources if the default route domain for the partition is
not 0.
Solution: Updated the CCCL library to a version that enforces
the use of route domains. If not specified by the user (the
controller), the partition's default route domain is used.
> Update to new cccl with full rd support (including fdb)

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
Problem:
Since there is only one virtual for HTTP OpenShift Routes, any Route
that specifies that HTTP should be redirected to HTTPS affects all
Routes.
Solution:
1. The controller now maintains a new data group for HTTP redirects.
2. Updated the HTTP redirect IRule to perform a lookup to the new data
group by host and path to determine if the HTTP request should be
redirected.
3. The controller keeps the redirect data group updated for both
OpenShift Route and Ingress resources to prevent the need to
maintain 2 IRules for HTTP redirect and to automatically do the
right thing when shared-ip for Ingress is implemented. This required
some the existing data group handling code to be moved so it would
be able to work across resource types (previously it was only used
by Routes).
4. Removed …
> Set InsecureEdgeTerminationPolicy affects all Route objects.

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/validateResources.go
Add support for Ingresses with the same IP:Port specification to share virtual servers.
1. Pools for Ingresses have been renamed to exclude the name of the Ingress resource, that way multiple Ingresses using the same backend don't create new pools; the pools are shared.
2. Virtual server names are of the format "ingress_ip_port".
3. If Ingresses have different IP addresses then they will create separate virtual servers.
Closes #325
> Shared Ingress support

- pkg/appmanager/appManager.go
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
Problem: When an Ingress had multiple Secret tls names provided, the controller
would configure these profiles on the BIG-IP without setting a default for SNI. This
would cause only one of the profiles to be linked to the virtual.
Solution: Similar to the way Route profiles are configured, if an Ingress specifies any
custom profiles, the controller will create a basic default clientssl profile for the virtual
server that will be set as default for SNI. Any Ingress profiles will then be created for the
virtual as additional profiles.
Fixes #344
> Create Default for SNI profile for Ingress

- cmd/k8s-bigip-ctlr/main.go
- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/validateResources.go
Problem: Customers don't want to specify IP addresses in their Ingress configs, since Ingresses live close to the applications (not the networking configuration).
Solution: The controller now supports a "default-ingress-ip" configuration parameter that will be used as the IP address for all Ingresses with the annotation "virtual-server.f5.com/ip:controller-default". Ingresses without this annotation will be configured with their own specified IP.
Fixed an issue regarding health monitors on shared single service ingresses not being configured properly. Also updated ingress vs names to include a route domain with a "." delimiter instead of "-". Finally, fixed an issue where new policies were not being set properly on existing configs.
> Default IP for Ingress

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/types.go
Problem:
The way node updates were being handled causes problems for
multi-service Ingress resources.
Solution:
Changed ProcessNodeUpdate to simply populate the virtual server work
queue when nodes change instead of having another code path that
updates configs (and incorrectly in the case of multi-service Ingress).
This allowed for the removal of the NodePort member in the meta-data
stored in resource configs. This change required some changes to
existing unit tests as follows:
1. Removed validateConfig() calls from the "should process node
updates" test as ProcessNodeUpdate() no longer writes out configs and
appropriate validations already exist in the test.
2. Updated one of the event count validations in the "configures
virtual servers via Ingress" test as the test was seeing an …
> ProcessNodeUpdate assumes ConfigMap

- Makefile
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/validateResources.go
Problem:  Need to be able to handle the alternateBackends definition
in the route spec.  This is used to specify addition services to use
for A/B deployments
Solution: Updated the route handling to return an array of services
instead of just one.
> Process multiple services per route definition

- pkg/vxlan/vxlanMgr.go
- pkg/vxlan/vxlanMgr_test.go
Problem: The custom record names that were created for OpenShift didn't match the formatting
of the record names as they came back from the BIG-IP. Leading zeroes were stripped by the controller, but not by the BIG-IP.
Solution: Ensure that leading zeroes in the tunnel record names are retained to match the BIG-IP config.
Fixes #461
> Fix VXLAN tunnel record names for consistency

- python/bigipconfigdriver.py
Problem: Pool names have changed, so scale tests logs were not being written out correctly.
Solution: Pool names now contain the name of the service, whereas formerly they mirrored the name. Update this to accurately find the pool name.
> Update pool names for scale test logs

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
Problem: Each route may specify multipe services.  We need pools
created for each of these services.
Solution: During route sync, determine if the service belongs to
the route and process accordingly.
> Added creation of pools for alternateBackends (openshift only)

- python/bigipconfigdriver.py
Problem:
- set_user_agent() incorrectly targeted `VERSION_BUILD.json` without `/app/python/` prefix generating an Error log entry at start up.
Solution:
- added full path
Tests:
- spun up controller and confirmed message no longer showing
fixes #464
> fix VERSION_BUILD log error

- CONTRIBUTING.md
- LICENSE
- cmd/k8s-bigip-ctlr/pythonDriver.go
- docs/README.rst
- docs/conf.py
- pkg/vlogger/console/log_console.go
- pkg/vlogger/doc.go
- pkg/vlogger/log.go
- pkg/vlogger/log_null.go
- python/tests/test_k8scloudbigip.py
- requirements.docs.txt
Fixes #483 
Fixes #261 
Changes made:
- update docs config to use an extension for table formatting 
- update docs requirements
- change copyright year from 2017 to 2018
- Change how local relative links are handled so they won't be ignored by the linkcheck. 
- Move all link substitutions to rst_epilog in conf.py
- Move all footnotes in docs/README to bottom of page
- add note about not supporting path-based routes for TLS re-encryption (per conversation with @russokj )
> Fix Doc bugs

- pkg/appmanager/appManager.go
- pkg/appmanager/profiles.go
- pkg/appmanager/resourceConfig.go
Problem: Now that Ingresses are built off of existing configs, it is important that
all data is correctly copied to each new config. Profiles were not being correctly copied
when an Ingress was updated, causing some intermittent issues.
Solution: Correctly copy profiles when updating an existing config. Also ensured that configs are
written out when profiles are updated.
> Sync profiles for Ingresses

- docs/RELEASE-NOTES.rst
Added a bug fix note for a comparison problem in CCCL that caused
unnecessary updates to occur for Virtual Servers on BIG-IP
> Release Notes for CCCL Virtual Server bug fix

- .f5license
- Godeps/Godeps.json
Bumped the commit for the yaml.v2 package to the latest in order to inherit the Apache license,
whereas this package formerly used LGPLv3.
> Update yaml.v2 to latest

- docs/README.rst
- docs/RELEASE-NOTES.rst
- pkg/appmanager/resourceConfig.go
Problem: Routes would default to using round-robin as their load balancing method, without
the ability to configure a different method.
Solution: Routes can now be annotated with the 'virtual-server.f5.com/balance' annotation, similar
to Ingress, in order to use a different LB method than round robin.
Fixes #491
> Add balance route annotation

- docs/README.rst
- docs/conf.py
Fixes #422 
This PR contains the agreed-upon fix for the schema-lb mode mismatch -- linking out to the schema in f5-cccl.
I have also made some general edits to improve organization and usability.
> Clarify docs

- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Adding two new unit tests for A/B deployment. The first test verifies that alternate backends in Routes create the correct number of pools and rules. The second test verifies that the data groups are correctly populated with the weights and corresponding pool names (for each path).
Also fixed the PoolCount method to correctly count the number of pools (formerly it would count configs per svcKey, which resulted in duplicates in some cases).
> Unit tests for A/B deployment

- pkg/appmanager/resourceConfig.go
Problem: When we copy a config from the internal store to reuse in a new config, not all
structs were being copied by value. Nested structs were still copied by reference, which resulted
in updates not being properly seen (as the internal store was updated by reference, so the later checks never saw this update).
Solution: Ensure that we are copying all complex nested structs by value instead of reference, to prevent updates from being skipped.
> Update cfgCopy method to include all complex types

- docs/RELEASE-NOTES.rst
- python/bigipconfigdriver.py
- python/tests/test_bigipconfigdriver.py
Problem: If the CCCL library throws a Big-IP exception (or any
exception), or if the driver encounters an exception while reading
the config file, then the driver hangs due to the thread terminating
(but not the process).
Solution: Catch the exceptions, log an error as specific as possible,
and then enter the retry loop.
Fixes: #506
> Bigipdriver.py hangs when exceptions occur

- python/bigipconfigdriver.py
Problem:  In the last commit, the cccl network
configuration was no longer being called due to
a return statement being indented too far.
Solution: Removed 4 spaces so the return statement is outside
the for loop that cycles between updating the ltm and network
objects.
> Fixed location of return statement in update_cccl()

- .travis.yml
Problem:
Travis script uses variable CTLR_VERSION to set version
string when deploying docs. This variable is not being set.
Solution:
Added variable CTLR_VERSION to travis.
> Added variable CTLR_VERSION to travis script

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
Problem: When deleting unused profiles, if processing a namespace that did not contain
an Ingress that referenced a profile on a virtual, the controller would delete the profile (even
if the profile was referenced by an Ingress in a different namespace).
Solution: Add a namespace field to the ProfileRef struct, in order to tell which namespace a profile
reference comes from. This way we don't delete a profile uninentionally when processing a namespace that
the profile didn't come from.
Note: This is a temporary fix that can be properly reworked when the fix for bug #471  is in.
Fixes #517
> Fix namespace bug when deleting profiles

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
Problem:
When Route resources are updated to reference a different service, the
old pools are not cleaned up until the next full refresh cycle. This is
also applicable to Ingress resources.
Solution:
There was no way before this commit to detect that a Route or Ingress
has been updated to reference different services. Now the Resources
object has the ability to track dependencies for Ingress and Route
objects (currently only Service dependencies are tracked), which allows
changes in dependent services to be identified, and pools updated
accordingly.
This commit also contains a bug fix for deleteUnusedResources, fixing
an issue where a policy that contains only 1 rule is deleted regardless
if it is a rule that should be removed for that invocation. That
function was also not protected by …
> Old service pools are not immediately removed

- docs/conf.py
Problem:
The docs version string as displayed on the clouddocs sidebar for
product docs shows an incorrect version string.
Solution:
The problem is that the docs version string is based on the version
information from next-version.txt. This is okay for non-release branches
such as master but not accurate for the stable branches off of which we
pull releases.
The fix is to use the latest git tag to determine docs version for
stable branches.
> Fix docs version string

- build-tools/docker-docs.sh
- docs/Makefile
- docs/conf.py
Problem:
The previous fix to extract docs version information relied on
git commands running in the containthedocs environment which
was failing and always going through the non-stable branch
path.
Solution:
Extract the docs version information in the same way as the previous
fix, but prior to running the containthedocs container. In the
docs Makefile, use these release related variables (if set) to
override the ones in the Sphinx config file.
Testing:
Ran the following commands with various values for TRAVIS_BRANCH
to test the functionality:
./build-tools/docker-docs.sh # from dev-machine
./build-tools/make-docs.sh   # from containthedocs shell
Now, browse docs/_build to ensure the generated docs have
the version string to meet the expectation as set by TRAVIS_BRANCH.
> Fix version information in documentation

- Makefile
- build-tools/vet.sh
- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/types.go
- pkg/pollers/nodePoller_test.go
- pkg/vxlan/vxlanMgr.go
- pkg/vxlan/vxlanMgr_test.go
- pkg/writer/configWriter_test.go
Problem:
Improve code verifications with 'go vet'
Solution:
Added a new make file step (make vet) and added the 'vet' target to the
existing verify step. Also fixed all of the current problems identified.
"go vet" has all standard checks enabled (using the -all flag), as well
as the experimental flag -shadow which is very useful to help find
problems due to shadowed variables.
Fixes VEL-1291
> Enable 'go vet' checking during verify step

- python/tests/kubernetes_one_svc_two_nodes.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
- python/tests/kubernetes_one_udp_svc_two_nodes.json
- python/tests/kubernetes_one_udp_svc_two_nodes_expected.json
CCCL now enforces the relationship that the Health Monitor interval must
be less than the timeout
> Fix unit tests to use correct Health Monitor parameters

- build-tools/python-tests.sh
- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/tests/test_bigipconfigdriver.py
Problem:
The build should use the bandit security linter for the python code.
Solution:
Added bandit v1.4.0 to the build requirements, python test script; and
updated the python unit tests to address an issue found by bandit.
Fixes VEL-1246
> Integrate bandit security linter into build

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/test/utils.go
Problem: When using the IP annotation for a ConfigMap, the virtual server was mistakenly being set
to 0.
Solution: Use the port from the provided ConfigMap, instead of 0.
Fixes #549
> Fix an issue with vserver getting port 0

- pkg/vxlan/vxlanMgr.go
Problem:
High CPU usage when controller should be idling with no orchestration
changes
Solution:
The vxlan manager consumer should not use a default select case for the
channel read. This allows the process to tight loop when no reads are
available. It is OK to block on this read.
This should be cherry-picked back to 1.4 branch
Fixes #555
> Tight loop in vxlan manager causes high CPU usage

- python/bigipconfigdriver.py
- python/tests/test_bigipconfigdriver.py
Problem:
The bigipconfigdriver could encounter errors on start up that are
recoverable but are currently fatal if encountered.
Solution:
If the bigipconfigdriver encounters BIG-IP connection erros or missing
config file errors (since these are written out by the controllers) it
will now log these errors and enter a retry backoff loop until
recovered.
Fixes: #510
> Add retry backoff for recoverable start up errors.

- python/bigipconfigdriver.py
Problem:
Current retry backoff callbacks do not do any logging on success.
Solution:
Add success logging to retry backoff callbacks.
> Added retry cb success logging.

- docs/RELEASE-NOTES.rst
Problem:
Some iApps have limitations that prevent deployment by the controller - e.g. the Application Services Integration iApp is not compatible with BIG-IP > 12.1.1. Nightly regressions skip BIG-IP / Controller combinations that exceed these limitations and the documentation is not explicit.
Solution:
Add a base limitation to the release notes.
See https://github.com/F5Networks/f5-application-services-integration-iApp/issues/16
> Clarify persistence of iApp limitations

- docs/RELEASE-NOTES.rst
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Problem: The CCCL library currently pulls in the f5-icontrol-rest
via the f5-common-python package.  This package does not pin the
f5-icontrol-rest package and new builds will therefore pull the
latest version.
Solution: Updated CCCL to pin the f5-icontrol-rest to a previous
version that did not have a memory leak issue.
Fixes: #551
> Update CCCL pointer to a version that contains a stable f5-icontrol-rest

- docs/RELEASE-NOTES.rst
Problem:
Bugfixes destined for the next released version are being listed
under a specific version tag based off of the next-version in
the stable branch. There are some problems with this approach:
1. What if we don't cut that specific version as the next release?
2. When cherry-picking this change into the stable branch, we now
have release notes for the specific version published to clouddocs
which may confuse customers causing them to think they are behind.
Solution:
Any bugfixes for upcoming release are listed under a 'next-release'
section in the release notes (both in master and stable). The
workflow then would be to rename 'next-version' appropriately when
its time to cut a release (and cherry-pick that to the appropriate
stable branch).
Note: This commit also fixes some …
> Replace specific next version in release notes with generic string

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/validateResources.go
Problem: iRules and datagroups were being created early and left behind for both Ingresses and Routes.
The ctlr also had issues leaving behind health monitors and profiles for Routes.
Solution: Ensured that iRules and datagroups are only created when necessary, and are cleaned up when done being used. Also added some logic to clean up health monitors and profiles properly for Routes.
Fixes #567
> Cleanup for leftover objects (Ingress/Routes)

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/validateResources.go
Cleanup for leftover objects (Ingress/Routes)
Problem: iRules and datagroups were being created early and left behind for both Ingresses and Routes.
The ctlr also had issues leaving behind health monitors and profiles for Routes.
Solution: Ensured that iRules and datagroups are only created when necessary, and are cleaned up when done being used. Also added some logic to clean up health monitors and profiles properly for Routes.
> Cherrypick 567

- requirements.txt
Problem:
The agent had an issue with hard coded paths to the CCCL schema which
was causing rhel image errors.
Solution:
Update the agent pointer to point to the the fix.
> Updated agent pointer.

- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
Problem: The ssl passthrough irule in 11.6 was not validating data fields correctly. Also in 11.6, we
were passing a wildcard to a datagroup record, which needs to be escaped.
Solution: Properly format the iRule variables to be compatible with 11.6. Also, escape the wildcard string
that is passed in the https redirect data group.
> Fix iRule name for 11.6; datagroup record

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/resourceConfig.go
Problem: Some logging around using Secret SSL profiles was confusing or vague. Also, the partition was not included if only the profile name was provided (which is the case with Secrets), resulting in a bunch of unnecessary updates to the virtual server. Finally, configmap profiles were not being cleaned up properly when removed.
Solution: Update the logging to be clearer about what is happening, and removed a log that was misleading. Ensured that if a secret profile name was used, then the partition is added to prevent constant updates to the virtual server. Also ensured that profiles are cleaned up in the configmap case.
Fixes #552
> Fix SSL Secret profile issues

- docs/README.rst
- pkg/appmanager/profiles.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
Problem:
We need to reencrypt from the BigIP to the PODs in Openshift
Solution:
Adding support for a new annotation in Ingress (from the #433 issue)
virtual-server.f5.com/serverssl: "/Common/serverssl-k8s"
Detailed description of your solution:
Adding handling for serverssl in resourceconfig.go/handleIngressTls to add the profile
and profiles.go/deleteUnusedProfiles to don't accidently delete it. I also added a debug output so it's possible to logg unused profiles
Testing :
We have tested it on 1.4.3 branch in our environment based on Openshift 3.6 and 3.7.
> Fix: #433 Add Serversslprofile to Ingress integration

- cmd/k8s-bigip-ctlr/main_test.go
Problem: If running locally without the bigipconfigdriver.py installed, one of the unit tests would fail when looking for the existence to this file. This test shouldn't care whether the file exists, as that is not what is being tested.
Solution: Remove the check for the existence of bigipconfigdriver.py, as it is not necessary to the test.
Fixes #623
> Unit test shouldn't look for python driver

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
- pkg/test/utils.go
Problem: The node label selector was ignored in cluster mode due to the endpoints being acquired without caring which node they came from.
Solution: When getting the endpoints for cluster mode, the controller will now check which node they came from. This will ensure that if a node is not being watched, the controller will not use endpoints on that node.
Fixes #592
> Fix node label selector in cluster mode

- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
- pkg/appmanager/validateResources.go
Problem: Single service Ingresses should not be able to share a virtual server with any other Ingress. Single service Ingresses don't create policies (since there is only one pool), so having multiple pools without a policy doesn't make sense.
Solution: When an Ingress update happens, and either the incoming Ingress is single service, or we already have a single service configured on the specified IP:Port, then we reject the incoming Ingress.
Fixes #608
> Disallow single service Ingress to share VS

- pkg/appmanager/resourceConfig.go
Problem: Extended paths that had / characters were causing dead links on the BIG-IP GUI. Traffic would still work, but the GUI would not.
Solution: Changed any / characters to underscores in Ingress rule names.
Fixes #638
> Replace rule / with underscore

- docs/RELEASE-NOTES.rst
- pkg/appmanager/profiles.go
Problem: If pre-existing profiles were being supplied via annotation for Routes, the controller was accidentally deleting these profiles.
Solution: When cleaning up unused profiles, be sure to check if the annotation profiles should be kept. The client/server profiles we check will either be in the route OR in the annotation.
Fixes #649
> Don't remove Route annotation profiles

- .f5license
- docs/README.rst
- docs/RELEASE-NOTES.rst
- docs/conf.py
- requirements.txt
Problem:  Need to support externally defined virtual servers in
the controller partition.  This is needed to bring parity to the
Openshift F5 Router.
Solution: The CCCL library has been updated to perform a merge
instead of a replace if the resource has a cccl-whitelist
metadata flag set to true/1.  The change here is simply to include
new CCCL change by updating the f5-ctlr-agent.  In addition, the
product docs, the release notes, and license information required
by the whitelist feature have been updated.
> Updated f5-ctlr-agent to include whitelist changes

- docs/RELEASE-NOTES.rst
Problem:
The cccl-issue for installing the certificates and keys to the
managed partition was not included in the Release Notes.
Solution:
Added this issue to the Release Notes under Bug Fixes.
> Added cccl-issue for certificates and keys to the Release Notes.

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem: If a rule was deleted in an Ingress, but the pool still remained (pool was referenced multiple times in Ingress or multi-service gets reduced to single-service), the rule would still be configured.
Solution: Track Ingress host/path rules as an object dependency. If an Ingress gets updated and that host/path rule no longer exists, then the rule is deleted from the config.
Fixes #635
> Delete rules that no longer exist in Ingress

- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
- pkg/appmanager/validateResources.go
Problem: When updating a multi-service Ingress to a single-service Ingress, there were a few issues. First, the controller would still have the previous multi-service ingress stored, and so when seeing the single-service, would deny the IP address to be shared, and reject the Ingress. Also, if changing from a multi-service to single-service, the default pool was not updated.
Solution: Change the single-service check to verify whether or not the previous config came from an ingress with the same name, rather than of the same type. This allows different type ingresses to be updated properly. If going from a multi-service Ingress to single-service, set the virtual's default pool.
> Fix multi-service to single-service transition

- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem: Similar to a previous Ingress problem we had, if a Route's host/path spec changes, the controller doesn't clean up the original rule.
Solution: Track the route host/path rule as an object dependency, and clean up the original rule if the host/path changes.
> Clean up Route rules if Spec changes

- build-tools/Dockerfile.rhel7.builder
Problem:
If the RHEL host has pip packages that are part of the distribution,
and they conflict with the versions required by the pip install
commands in the Dockerfile, the install fails.
Solution:
Ignore any installed versions of pip packages on the RHEL host
and install the ones specified in the requirements file.
> Ignore versions of pip packages already on rhel host while building

- docs/_templates/breadcrumb.html
- docs/_templates/extralinks.html
I made a few docs-nav updates to improve the user experience:
- Add devcentral link to sidebar (same as in the solution docs)
- Add link to the solution docs to the breadcrumb
> Improve navigation between doc sets

- docs/RELEASE-NOTES.rst
- pkg/appmanager/resourceConfig.go
Problem:
url-rewrite rule names were targetvalue instead of target-value making
them difficult to read. The release notes were missing the limitation
comment for the url-rewrite feature.
Solution:
Add - to url-rewrite names so they are target-value. Add limitation
note to release notes.
> Fix url-rewrite rule naming add limitations to release notes.

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- requirements.txt
Problem: Node watching was only enabled for nodeport mode, and cluster mode w/ vxlan specified. This breaks when cluster mode is being run without vxlan. Pool members were not being configured.
Solution: Removed the stipulation that a vxlan name had to be specified in order to watch nodes. Also, updated the CCCL pointer to pull in the list length bug fix.
Fixes #682 
Fixes #683
Fixes #686
> Fix node watching; update CCCL pointer

- docs/conf.py
- pkg/appmanager/appManager.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
Problem: There were a couple of problems causing performance issues. First, using gob encoding to deepcopy configs proved to be inefficient. Secondly, the controller's steady-state check relied upon the queue being empty before writing any configs. With a large number of resources to process, and Kubernetes constantly updating endpoints, the queue would take a long time before being empty, therefore the controller wouldn't write any configs in a reasonable time.
Solution: Switched back to manual deepcopy instead of gob encoding. Saved off the initial queue length on startup, and kept track of the number of processed items before writing out a config, rather than waiting for the queue to be empty.
> Fix performance issues

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- docs/README.rst
- docs/RELEASE-NOTES.rst
- docs/conf.py
Problem: Using the CLI to provide BIG-IP arguments is a security vulnerability, as they are displayed when running 'ps'.
Solution: Allow for users to create and mount files via a Secret, and provide the mount path to the controller. The controller will look in this path for username, password, and url files. If they are not found, it falls back to using the CLI.
> Allow files for BIG-IP parameters

- docs/README.rst
- docs/_static/config_examples/example-bigip-credentials-directory.yaml
- docs/_static/config_examples/sample-k8s-bigip-ctlr-secrets.yaml
Adding deployment config example for how to mount a secret containing BIG-IP information into the controller.
> Config example for credentials directory

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles_test.go
This patch adds a switch to the creation args to instruct CC to
either watch, or not watch, ConfigMap events. The default value
of this switch is `true`; as-in "watch ConfigMaps". This was
the default behavior before this switch was added.
> Adds switch to disable ConfigMap processing

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
Problem: A bug existed for both Routes and Ingresses where all BIG-IP resources would temporarily be deleted when a single service was deleted. This was due to some bad logic that would deactivate an entire config if a service for that config wasn't found.
Solution: The logic now considers if there are multiple services for a config, and some are still active, then don't deactivate the config if a single service goes away. Only when all services are gone will the config be removed.
Fixes #743
> Don't remove all resources when deleting service

- docs/README.rst
- docs/RELEASE-NOTES.rst
- pkg/appmanager/profiles.go
Problem: The controller requires either literal cert/key info or annotations to be specified for Route profiles. If neither were specified, the controller silently failed.
Solution: Added docs and a log warning to inform the user that one of these fields is required.
Fixes #746
> Docs and log message for bad Route spec

- .approvals.json
- Makefile
- build-tools/rel-build.sh
- build-tools/run-in-docker.sh
- docs/README.rst
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
- pkg/appmanager/types.go
- requirements.txt
This patch adds whitelist annotation processing to CC. Whitelist
entries are created as part of L7 policies.
> Adds whitelist annotation support to CC

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
Problem:
Currently if there are two multi-service ingresses or routes pointed
at the same service if one of them is deleted its rules will be left
on the policy on the BIG-IP causing disruption to traffic as the
controller tries to reconcile the desired config versus the left
overs on the BIG-IP.
Solution:
Add rule check in the dependency deletion in UpdateDependencies that
will find the rules associated with cleaned up dependencies and add
those to the remove dependencies slice to clean them up. Update unit
tests to factor in this change.
Fixes: #735
> Fix same service rule cleanup

- docs/README.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
Adding support for the whitelist annotation for Routes. This is the same functionality as Ingresses (only allow specific IP access) for certain L7 rules.
> Whitelist IP support for Routes

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
- requirements.txt
Problem: 1. Route rules were not sorted correctly, causing "first-match" to behave unintentionally.
2. Whitelisted L7 rules for Routes with iRules would still allow traffic to flow through the iRule even when failing the policy.
3. Policy with whitelist rules didn't have the required "tcp" flag.
Solution: 1. Sorted Routes by URI to mimic "best-match".
2. Whitelisted Route rules now add a "reset connection" rule to prevent traffic from unintentionally flowing through an iRule.
3. Added "tcp" field to policy.
Fixes #755 #765
> Add whitelist reset rule, fix Route sorting

- pkg/appmanager/resourceConfig.go
Problem: If a service was deleted or goes away, the reset rule for routes using that service was not cleaned up.
Solution: Clean up reset rules if they exist when a pool is removed.
> Clean up reset rules when service goes away

- pkg/appmanager/routing.go
Problem:
The customer was facing the issue in routing the child paths of service from HTTP to HTTPS. 
Fix:
Modified the BIG-IP IRules to handle this situation.
> Fixes #789: Fixes the tls http to https route for child paths

- .approvals.json
- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
RedHat is decommissioning their registry **registry.access.redhat.com** and changing it to **registry.redhat.io**. This PR contains necessary changes to adapt to the new registry.
> Change Redhat registry location

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
Mitigates #810 where the controller deletes BigIP resources on startup and restart where a large number of services present in Kubernetes
> Delay vsQueue Length Assessment

- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
there are actually two issues here when Ingress ssl-redirect is true
1, the http virtual server should not have policy configuation as the
policy would handle the request instead of ssl-redirect
2, when http-port is non standard port 80, the ssl-redirect irule should
take non-standard port 80 into consideration
this patch fixes above two issues
> http_redirect_irule_443 irule should honor custom http port

- docs/README.rst
- docs/conf.py
Move #3 and #4 footers (username / password) into the BIG-IP System table.
Also add the sphinx_copybutton module to conf.py.
These changes need to be made to both the v1.7 and v1.8 branch.
> Update README.rst and conf.py

- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
Problem:
Only 200 responses are being handled. Controller crashes for incoming responses other than 200.
Solution:
All responses are handled. Any response other than 200 will be logged in
Debug.
Testing: Added unit test cases for 500 and Protocol error.
affects-branches: feature.user-defined-as3
> Handled big ip REST call response code and message

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Data plane traffic fails in ClusterIP mode because there are no static ARP entries available in BIG-IP to forward traffic to flannel/sdn interface.
Created a master list to track discovered AS3 Members and sending the list to VxLAN manager for ARP update and FDB update.
affects-branches: feature.user-defined-as3
> Add Static ARP for AS3 Members

- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
- pkg/test/configs/as3config_without_adc.json
Problem:
Without ADC class also, AS3 Template is being parsed and Controller is crashing.
Solution:
Updated logic not to handle any AS3 Template without ADC class.
All related unit tests pass.
affects-branches: feature.user-defined-as3
> Handle AS3 Templates with no ADC class

- pkg/appmanager/appManager.go
LoadBalancer and NodePort services behave the same way in the sense that they use a port on the node for traffic ingress. The controller should be able to treat them the same way.
I've tested that this works for NodePort and LoadBalancer service types.
> Support LoadBalancer Service types in addition to NodePort.

- pkg/appmanager/as3Manager.go
Problem: When service discovery labels are tagged to multiple
Services, all of the endpoints are added to AS3 template. This can
potentially cause issues in traffic distribution.
Solution: Detect services that use the same tags and list them to the user and
don't process any endpoint until there is a one to one mapping between a
Service and Pool.
Affected-branches: feature.user-defined-as3, master
> Address multiple Services tagged with the same labels

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: We are customizing and hard linking AS3 JSON Schema with the
controller. If there are bugs in the JSON schema or the validator we use,
there is no way to address this situation without shipping a new release.
Solution: Make AS3 Schema validation configurable so that the user can
disable validation.
affected-branches: feature.user-defined-as3
> Option to disable AS3 Validation

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
Problem: Insecure flag was always set to true.
Solution: Introducing --insecure flag option. The default option is set as false for secure communication. User can change it as true to enable insecure communication to bigip.
affects-branches: feature.user-defined-as3
> Option to enable insecure communication

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/outputConfig.go
Problem: Sending AS3 Static ARP entry updates deletes existing ARP
entries from legacy resources.
Solution: This is happening because CCCL is declarative. AS3 member
update is handled along with legacy ARP processing.
Affected branches: feature.user-defined-as3
> Combine AS3 ARP Update with legacy ARP Processing

- README.md
The hyperlink had an extra character < in the link which prevented the hyperlink from being created
> Update readme to fix typo in hyperlink

- README.md
Changed text in Official Build steps to reference Debian rather than Alpine as we no longer build on an Alpine base image
> Change official build steps to reference Debian

- pkg/vxlan/vxlanMgr.go
- pkg/vxlan/vxlanMgr_test.go
Problem: CIS takes the node ip information from kube api in cluster mode. It should actually take these details from flannel as CIS creates the fdb entries in BIG-IP using these details.
Solution: Use Flannel annotations to get the node ip addresses.
Affected Branches: master
> Fix797: Take the flannel node IP as Vtep endpoint

- docs/conf.py
Problem: iApp documentation link is broken which causes builds to fail.
Solution: Changed the URL to point to a general documentation on F5
Technologies, which have correct pointer to iApps.
affected-branches: master
> Broken Link Fix for iApp Documentation

- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
Problem:
CIS always posting same AS3 declaration to BIGIP if there are no changes in the declaration.
Solution:
Implemented MD5 checksum mechanism on the AS3 declaration to identify the changes on the declaration.
master
> Implementation of sending AS3 declaration to bigip only if there is change in declaration

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem:
CIS was not supporting third party certificates/self-signed certificates for secure communication to BIG-IP
Solution:
Given an option to pass the BIG IP's third-party certificates/self-signed certificates using config map for secure communication
master
> Option to add BIG-IP third party certificate/self signd certificate (using config map) to CIS

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/validateResources.go
Problem: Active configMap need to be pushed to vsQueue when ever there
are node changes (add or delete)
Solution: Node changes are triggered with Node SharedIndexInformer and
Active config maps are pushed into vsQueue when ever a node is added or
deleted.
> Handling Node changes (Add and Delete)

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: AS3 Template and declaration may contain sensitive data such as
private keys and passwords. Adding them in log will make them visible in
plain text at unintended places.
Solution: Remove AS3 Template and Declaration logging. Instead, log the
matched kubernetes Service along with discovered endpoints for the
service.
> Remove AS3 Template and Declaration Logging

- build-tools/Dockerfile.debian.runtime
Problem: libidn11 package used by upstream debian stretch is vulnerable
to remote attacks.
Solution: Remove libidn11 package during controller build.
Affecetd-branches: master, 1.9-stable
> Remove libidn11 package from controller

- README.md
Removed the words "Local Traffic Management" from the readme first paragraph as we can now address other module functionality via AS3.
> remove Local Traffic Management from 1st paragraph

- docs/RELEASE-NOTES.rst
- pkg/appmanager/routing.go
Problem: When handling multiple http connection, BIG-IP gets stuck forever
inside the "foreach" cycle, producing a 'prefix' variable. The iRule is never
unsetting 'prefix', so if you run multiple HTTP requests over the same
connection, the variable keeps being appended to, accumulating more and more
content.
Solution: Always initialize `prefix` with empty value before handling
paths.
> Unset prefix before handling paths

- pkg/appmanager/as3Manager.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
Problem:
In Openshift, CIS does not populate FDB entries in BIGIP when agent is selected as AS3.
Solution:
Allow cccl to do this, This will be eliminated when we develop our own go-sdk for FDB and ARP Entries.
feature.as3 and master
> Update FDB Entries for Openshift Routes Using CIS

- pkg/appmanager/appManager.go
Problem:
Master node is considered as a pool member when it is in ready to schedule state.
Solution:
Ignore Master node always.
master, feature.as3
> Ignore Master Node as Pool member

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/routing_test.go
This fix will add new argument to the BIGIP Controller deployment
--manage-ingress=true/false
> Support "manage-ingress" configuration option in BIGIP controller deployment

- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.debian.runtime
Problem:
There were a few  security Vulnerability issues were there in Debina Base OS 9(python:2.7-slim-stretch)
Solution:
Upgrading Debian base os from 9 to 10
Master
> Upgrading CIS Debian base os from 9 to 10

- docs/conf.py
Problem: `make docs` command breaks because of a broken anchor in docs configuration file.
Solution: Remove anchor from the link. The URL itself is sufficient for the reference
Affected Branches: master
> Fix broken `make docs`

- Makefile
- build-tools/golang/0001-Enable-AS3-Declaration-logging.patch
**Problem:** The production build do not log AS3 declarations because of
security considerations. However, AS3 declarations are vital in the
development/testing process.
**Solution:** Added a new make target so that executing `make dev` which will apply a git
patch to log AS3 declarations and then builds the container image.
**Affected-branches:** master
> Add funtionality to make developer builds

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem:
Currently, AS3 schema validation uses a particular version to validate the schema and not the latest
Solution:
This fix will allow AS3 schema validation to be done with the latest/updated AS3 schema 
master
> as3 schema validation using latest schema

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
Problem: When manage-routes is enabled and route-vserver-addr is not given then deployment fails with unknown error.
Solution: Check whether cis deployment option route-vserver-addr is also given when manage-routes is enabled. This will not crash the deployment but provide a detailed help message.
> route-vserver-addr is required when mange-routes is enabled

- docs/RELEASE-NOTES.rst
- pkg/vlogger/console/log_console.go
Problem: Controller logs all messages to Standard Error by default.
Solution: Set the output destination of INFO logs to Standard output and
fall back to default behaviour of `log/syslog` package.
Fixes: #1016
affected branches: master
> Log INFO messages in Standard Output

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Types.go
- pkg/appmanager/types.go
Controller will look for `virtual-server.f5.com/waf` annotation in
routes. If found, it applies it to the virtuals based on the following
condition.
1. Route doesn't contain TLS spec: Applies only to HTTP virtual.
2. Route contains only TLS spec: Applies only to HTTPS virtual.
3. Route contains TLS Spec and `insecureEdgeTermination` is 'Allow':
Applies to both HTTP and HTTPS virtuals.
> Add Support for WAF Policy reference in Route

- docs/RELEASE-NOTES.rst
- docs/conf.py
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: In Openshift ROUTE status is updated by its default router. We need to update it with respect to BIG-IP acceptance of the route.
Solution: OpenShift default router is scaled down. BIG-IP controller is updated to handle Route ADMITTED status based on the response from BIGIP. 
Signed-off-by: Trinath SOMANCHI trinath.somanchi@gmail.com
> Update Route admitted status in OpenShift 3.11 GUI

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
Problem: WAF Policy is not being applied in virtual if Path in the OCP route is "/"
Solution: Remove ending "/" in a path to fix the issue.
Affected-Branches: master, 1.11-stable
> Fix applying WAF to root of a domain

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/types.go
Problem: Routes in one namespace leading to override the AS3 configuration of routes in another namespace. The AS3 generated by controller consists of configuration related to routes that belong to only one namespace at any point of time. 
Solution: Handling multiple namespaces and make sure the AS3 configuration generated by controller consists of configuration related to all routes in all namespaces.
> Fix Issue with WAF Policy for routes in Multiple Namespaces

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: The status update in OCP 3.11 was done while scale-down of openshift-default-router. But this is not possible with OCP 4.x and higher versions where a OpenShift default router always exists.
Solution: Check where there is an update from F5 BIG-IP router, else update the condition. This makes F5 route status update co-exists with openshift default router updates.
Signed-off-by: Trinath Somanchi trinath.somanchi@gmail.com
Affected-branches: master, 1.11-stable
Docker Image: somanchit/k8s-bigip-ctlr:route-admit-status
> OCP 3.11 and 4.1 - Fix for Route Admit statuses

- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
Problem: outputConfigLocked is being called without locking properly
Solution: Call outputConfig instead of outputConfigLocked so that locking of resources is ensured
> Fix calling unsafer method of Output Config

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
Problem: Controller is crashing when Route with WAF Policy is deployed with unavailable service
Solution: Make sure, policy exists in AS3 declaration before applying WAF related to conditions and actions. Because Controller does not create policy if Route is configured with unavailable service.
> Fix Controleller crash with WAF Route and unavaible service

- cmd/k8s-bigip-ctlr/main.go
Problem: CIS crashing when unable to pull the latest as3 schema
Solution: Added appropriate defensive logic and handled the fallback logic
affects-branches: master, 1.11-stable
docker-image: snatra27/k8s-bigip-ctlr:1.11.1_build_4
> CIS crashes when unable to pull latest as3 schema

- pkg/appmanager/appManager.go
Problem: When NS resources are not being monitored, CIS is unable to clean respective objects in BIG-IP
Solution: Lock the resources being processed and let output config processing be taken care separately. 
Signed-off-by: Trinath Somanchi trinath.somanchi@gmail.com
Affected-branches: master, 1.11-stable
Docker Image: somanchit/k8s-bigip-ctlr:nsfix
> Fix NS resource cleanup when not monitoring

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
Problem: 
1. CC does not deal with the situation where one URI for a hostname should be re-encrypted and another URI should be edge terminated
2. CC does not handle child paths 
3. SSL based routing is incorrect for child paths.
Solution:
1. As of today Server SSL Datagroup(ReencryptServersslDg) created by CIS creates keyvalue pair with key as ServerName and value as ServerSSL. When a reencrypt route and Edge route are attached to the same hostname, the ServerSSL of reencrypt route is used by Edge Route as well.
The best way to overcome this situation is to update the Datagroup with Servername and Path.
Example:
For Route With Host-> foo.com and Path-> /foo ......... update the data group key as foo.com/foo instead of foo.com
2. Added new logic into Irule to handle problem2
3. Added two …
> Fix path and ssl based routing

- pkg/appmanager/as3Manager.go
- pkg/appmanager/outputConfig.go
**Problem:**
For Ingress resource in K8S setup, Data plane traffic fails for ClusterIP mode because there were no static ARP entries available in BIG-IP to forward traffic to flannel/sdn interface.
**Solution:**
Using Ingress pool members populating the AS3 Members list and sending the list to VxLAN manager for ARP update.
**Branches-effected:** master
> Ingress data traffic fails for ClusterIP mode as there are no static ARP entries available in BIG-IP

- pkg/appmanager/as3Manager.go
- pkg/appmanager/outputConfig.go
Problem:
ARP entries are improper when multiple ingress resources are configured.
Solution:
The arp entries population are corrected when there are multiple Ingress resources along with other resources.
Branches-effected: master
> ARP entry issues with multiple ingress resources

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Utils.go
- pkg/appmanager/as3Utils_test.go
- pkg/appmanager/outputConfig.go
- pkg/test/configs/as3config_override_simple_cfgmap_resource.json
- pkg/test/configs/as3config_simple_cfgmap_resource.json
Problem:
Need a feature that overrides existing AS3 configuration with a new user-defined AS3 configuration, using k8s ConfigMap. So the administrator will be able to modify the existing virtual server configuration incrementally as needed without having to overwrite/delete the existing one
Solution:
Implemented AS3 override feature in CIS, this feature enables administrators to create a virtual server in a controlled and managed partition manually and add metadata so that f5-cccl will not create a new virtual server.
docker-image: snatra27/k8s-bigip-ctlr:cis-override-json-2
> AS3 override feature in CIS

- pkg/appmanager/as3Manager.go
problem:
ingPoolMember is causing a crash as it is not initialised.
Solution:
remove the block as it is no longer used.
> var ingPoolMember is no longer used

- pkg/appmanager/routing.go
problem:
a_b deployment fails for the re-encrypt routes.
solution:
sslpassthroughIrule is looking for a_b deployment data group at the wrong path.
master
> Fix the path for abdeployment datagroup in BIGIP

- pkg/appmanager/outputConfig.go
Problem: ARP entries are not getting populated for K8S Ingress resources
Solution: Fixed the ARP issues caused due to merge 
Docker Image:  snatra27/k8s-bigip-ctlr:rel12_build_12
> ARP entry population fix Merge Issue

- pkg/appmanager/appManager.go
Problem: continuous calling output config due to overriding config map
Solution: Fixed by removing override declaration check.
Docker Image: snatra27/k8s-bigip-ctlr:rel12_build_12
> Fixed continuous calling outputconfig due to overriding cm

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/as3Manager.go
Problem: When agent changes from "cccl" to "as3" or vice versa, there is stale configuration on BIG-IP for the old agent.
Solution: Deleted CIS managed old partition when agent altered.
Docker Image: amit49g/k8s-bigip-ctlr:deletePartition
> Delete CIS managed partition when agent altered

- docs/RELEASE-NOTES.rst
Update the release version from Next Release to 1.12
Update the Limitation -> CIS does not support virtual-server.f5.com/http-port annotation.
> Update Release Notes for 1.12

- build-tools/Dockerfile.rhel7.runtime
Problem:
Fix RHSA-2019:4190 - Security Advisory
Solution:
Update nss and dependent packages.
master
> fix the rhel nss-tools vulnerabilities

- pkg/appmanager/appManager_test.go
- pkg/appmanager/routing.go
Problem:
Fix httpsredirectdg for multiple ingress/routes on same host
Refer: https://github.com/F5Networks/k8s-bigip-ctlr/issues/975
Solution:
Modify CIS to map the combination of host and path [instead of host] to ingress/route backend.
master
> Fix httpsredirectdg for multiple ingress/routes on same host

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
**Problem:**
[1] CIS watches all `Ingress` resources that either have `kubernetes.io/ingress.class: f5` or that don't have that annotation at all.
In a cluster that has multiple ingress controllers, it ends up with unpredictable results for ingresses that do not specify their class, the different controllers fighting against each other to handle the resource.
[2] CIS processes ingresses with ingress.class defaults to "f5" and there is no option for custom ingress classes.
**Solution:**
New controller deployment options:
- `--manage-ingress-class-only` (default - `false`) is added. when set to `true`, only considers `ingress.class` annotated ingresses. Using the below option, user can configure the controller with custom `ingress.class`. 
-  `--ingress-class` (default - `f5`) is added to …
> Support Ingress.Class and Manage default Ingresses.

- pkg/appmanager/appManager.go
Problem:
master label changed from node-role.kubernetes.io/master: "true" to node-role.kubernetes.io/master: "" in Openshift 4.1 and k8s 1.13.
Solution:
Start considering all the nodes including master. 
master
> Update the unscheduled node list for master label change in Openshift

- pkg/appmanager/as3Manager.go
Problem: AS3 accepts max 64 characters for BIG-IP object name. 
Solution: Need to reduce object name length created by CIS, by using short names instead of complete names that frame the object name.
Image: amit49g/k8s-bigip-ctlr:1287
> Reduce object name length for AS3

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/postmanager/postManager.go
Problem: Controller posts a declaration to /declare/, and TMOS has no idea about the partitions(tenants) that are going to be affected.
Solution: Controller posts declaration to /declare/\<list of comma separated tenants in the declaration\>, so that TMOS has visibility about tenants and it can filter out tenants.
> Add Feature Tenant Filter

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
Problem: CIS allows userDefinedConfigmap with CIS managed partition as tenant, which causes declaration to be pushed to Networking partition.
Solution: Do not process userDefinedConfigmap if it has a CIS managed partition as tenant.
> Fix CIS allows userDefinedConfigmap with CIS managed Partition as Tenant

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/resourceConfig.go
Problem: Ingress resource - Performance problem with a large number of ingresses(git hub issue #1014)
Solution: Optimized the Kubernetes client API calls in CIS while processing Ingress resources
Docker Image: snatra27/k8s-bigip-ctlr:ingress-performance-issue
> Performance issue in CIS when simultaneously processing more number of ingress resources

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/postmanager/handleRouteStatus.go
- pkg/postmanager/postManager.go
Problem: Route status is not being updated on the OpenShift dashboard after introducing postmanager package
Solution: Handover the responsibility of updating the route status to postmanager, whenever post manager successfully posts config to BIG-IP, it updates the route status as well.
> Add Route Admit Status on OpenShift Dashboard

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
- pkg/postmanager/postManager.go
Problem: Controller pushes config to BIG-IP after 30 seconds if encounters 404 code on previous request. 
Solution: Controller does not push configuration if it encounters code 404 on previous request.
> Add error handler for code 404

- pkg/appmanager/routing.go
Problem: 
Fix issues for Edge route with InsecureEdgeTerminationPolicy:Redirect. Observed Issue in passing the traffic for "/" as app root.
Solution:
Modify Redirect IRule to support the changes.
Master
> Fix issues for Edge route with InsecureEdgeTerminationPolicy:Redirect

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/resourceConfig.go
Problem: Multiple messages are posted to BIG-IP while ingress resources deployed
Solution: This is introduced as part if the performance specific changes, this issue is fixed after reverting specific code in performance feature
Build-Image: snatra27/k8s-bigip-ctlr:v1.13.0_rel_build_3
> Fix for multiple ingress message requests to BIG-IP

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/postmanager/handleRouteStatus.go
- pkg/postmanager/postManager.go
Problem: Route status is not being updated because of default router updates the status and makes CIS to fail to update the status. And internal DS are being overridden that leads to inconsistent behaviour of Status update.
Solution: Always get routes before updating the status instead of cached ones. Maintain internal DS properly.
> Fix Route Admit Status issue

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/postmanager/postManager.go
Problem: Continuously posting new declaration to BIG-IP without much delay leading to 503 response from BIG-IP as AS3 is busy in performing earlier requests
Solution: Delay the post call to BIG-IP with given number of seconds through CIS config parameter, let the CIS to produce all the declarations with out blocking for BIG-IP response and after the delay ends pick up the latest declaration produced and post, so that CIS will not do many post calls.
> Add post delay time

- cmd/k8s-bigip-ctlr/main.go
Problem: CIS is unable to delete AS3 partition when deployed in CCCL due to schema validation is failing for the AS3 declaration
Root Cause: AS3 schema is not fetched by the time as3 delete partition is triggered.
Solution: Fetch AS3 schema before triggering delete as3 partition.
> Fix Delete AS3 partition declaration schema validation failure

- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
Problem: Edge Redirect Route is not working with combination of Edge Allow Route or insecure Route.
Root Cause: Edge Redirect route doesn't have a policy in http virtual, which is needed by WAF to decide to drop or allow a request to virtual.
Solution: Add a policy to http virtual, in case of Edge Redirect Route, so that the policy will be consumed by WAF later, so that traffic reaches http virtual and eventually gets redirected to https virtual
> Fix Edge Route Redirect issue with WAF

- pkg/appmanager/appManager.go
- pkg/appmanager/routing.go
Problem:
CIS fails to send traffic for edge routes with path "/". 
Steps to reproduce:
Create a route resource with host some foo.com and path as "/" for "service: svc-1" as shown below. Try the below URL --> https://foo.com/<something> 
```
oc get routes
NAME                  HOST/PORT   PATH     SERVICES          PORT    TERMINATION     WILDCARD
example-route-1      example.com     /              svc-1                <all>   edge/Redirect   None
```
CIS fails to send to send traffic to backend with svc-1
The reason for this is, CIS creates datagroup entry for foo.com/ for pool --> svc-1 but Irule looks at datagroup for entry foo.com.
Solution:
Removing the trailing slash created for datagroup entries
master
> Removing the trailing slash created for datagroup entries

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Types.go
Feature: Adding TLSv1.3 support to TLS_Server profile using AS3
Created 3 deployment flag to support TLS 1.3 and for TLS 1.2 gave provision to set ciphers.
1. --tls-version=<1.2 or 1.3>
2. --cipher-group=/Common/f5-default
3. --ciphers=ECDHE_ECDSA:ECDHE
For TLS 1.3 need to set cipher-group 
For TLS 1.2 need to set ciphers
Note:  - AS3 only supports TLS 1.3 in tmos version 14.0+.
- ciphers and cipher-group are mutually exclusive, only use one.
affected-branch: master
Signed-off-by: Amit Gupta amit0658@gmail.com
> Adding TLSv1.3 support to TLS_Server profile

- pkg/appmanager/resourceConfig.go
Problem: Updating balance annotation in Routes and Ingresses not working
Solution: It is not being updated in config structures, so update the internal config structures with new value of annotation.
> Fix balance annotation update issue for routes and ingresses

- docs/RELEASE-NOTES.rst
- pkg/appmanager/routing.go
The ssl-redirect irule would fail to do http to https redirect
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1160
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: f5ingress
namespace: default
annotations:
#nginx.ingress.kubernetes.io/rewrite-target: /
kubernetes.io/ingress.class: "f5"
virtual-server.f5.com/ip: "controller-default" # mgmt network
virtual-server.f5.com/partition: "k8s"
virtual-server.f5.com/balance: "least-connections-node"
virtual-server.f5.com/serverssl: 'Common/serverssl'
ingress.kubernetes.io/ssl-redirect: "true"
ingress.kubernetes.io/allow-http: "false"
virtual-server.f5.com/health: '[
{"path": "nginx.cluster.example.com/", "send": "GET /test_check HTTP/1.1\r\nHost: nginx.cluster.example.com\r\n\r\n", "interval": 5, "timeout": 10}
]' …
```
> fix httpsredirect for ingress with noHostSpec

- docs/RELEASE-NOTES.rst
**Problem:** [1.13 Release notes](https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.13/RELEASE-NOTES.html) is carrying "next release" header.
**Solution:** Removed excess header.
**Affected Branches:** 1.13-stable
**Signed-off-by:** Surendhar <surendhar@ymail.com>
> Remove Header in Release Notes

- Makefile
- all_attributions.txt
- build-tools/Dockerfile.debian.builder
- build-tools/attributions-generator.sh
- build-tools/build-devel-image.sh
- build-tools/build-release-images.sh
- build-tools/rel-build.sh
What are Attributions Generators ?
Attributions Generators basically automates the process of reading LICENSE files. There are many popular attribution generators like licensee.
CIS Attributions Generator ?
CIS is using a specific attributions generator called ninka (License Identification Tool).
What is the problem that team is facing today?
CIS is using a old dependency management tool for source code called deps(specific to Golang). There are two disadvantages using deps.
Adding or deleting any dependency is a very tedious process.
Community is moving to Go modules, so new dependencies are not easy to import.
To get rid of this problem CIS has successfully migrated to Go mods. But, ninka (License Identification Tool) does not support Go modules. 
It is almost impossible to update …
> Start using new attributions generator: Licensee

- pkg/crmanager/informers.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
Features:
1.  Ignore AddFunc for service as we dont bother about services until they are mapped to one or many VirtualServer. Any new service added and mapped to a VirtualServer will be handled in the VirtualServer Informer AddFunc.
2. Process Service and Endpoint Changes. Services and Endpoints changed will indirectly trigger the effected VirtualServer/s. 
3. Input custom resource obj instead of rqkey structure to syncVirtualServer, syncService and synEndpoint. This will not only improve the performance but will also maintain a symmetry between multiple functions.
4. Introducing checkValidVirtualServer, VirtualServers identified from services or picked from the queue should pass the checks within checkValidVirtualServer. This will be enhanced in stages to achieve utmost out of this …
> Handle Service and Endpoint changes for Custom Resources.

- docs/_static/config_examples/crd/basic/example-single-pool-virtual.yml
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
Problem:
Fix issues in populating resource config structure for virtual server. CIS in custom resourcemode was not able to populate the poolmembers of a pool as it was not able to fetch the node details.
Solution:
Integrate the node polling capabilities in to CIS CRD mode. This will help custom resources resource config to fetch the pool members endpoints. 
> Fix issue in populating resource config with pl members and policies.

- config/apis/cis/v1/types.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
problem:
CRD:  CIS in custom resource mode should not create HTTPS Virtual Server for unsecured custom resource.
Solution:
Since we do not support TLS for now, Just create HTTP.
// TODO: We will support TLS feature for CRD in coming releases. With TLS, we will create both HTTP and HTTPS VS.
> CRD: Eliminate Https VS for unsecured VirtualServer CR

- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- requirements.txt
Problem: CIS uses Two partitions of BIG-IP, one for LTM and another for NET configurations.
Need to use only one partition for both LTM and NET configurations.
Solution: Disable LTM manager in f5-ctlr-agent and push both configurations to same partition which is configured by user.
> Update CR Manager to use single partition in BIG-IP for both LTM and NET Configurations

- cmd/k8s-bigip-ctlr/main_test.go
Problem:
Failed Unit Test: Handle Empty VXLAN flags.
Solution:
This implementation changed in spf13 v1.0.3.
Usage() is not called as ContinueOnError is set for unit tests.
So we adopted to the new behaviour introduced.
Refer --> FlagSet.failf() in flag.go
Regards,
> Fix failed Unit Test, Handle empty vxlan flags

- pkg/crmanager/informers.go
- pkg/crmanager/node_poll_handler.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
Feature:
Handle deletion of services and virtual server custom resource.
Solution:
VirtualServer:
Get the name of the VirtualServer to be deleted and format it to the way it is stored in resourceconfig map. Use the basic delete operation on map to delete the respective resource config.
Service:
Delete Operation on service is very similar to Update Operation. We populate all the pools(corresponding to this service) with empty pool members(as endpoints are removed). This pool will be completed deleted from BIG-IP when user removes the service configuration from virtualserverspec.
> CRD: Delete Implementation for VirtualServer and Service

- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.debug.runtime
- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
Problem: Pip version 20.1 has changes related to internal req module, which is leading to build failures as f5-ctrl-agent setup is dependent on pip internal req module.
Solution: As a workaround restrict pip version to 20.0.2 in docker images.
> Set pip version in Docker images to 20.0.2

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
- pkg/appmanager/appManager.go
- pkg/appmanager/profiles.go
- pkg/resource/resourceConfig.go
Problem: Observed dump of "Overwriting existing entry for backend" logs when routes configured in different namespaces
Solution: Consider profile context along with name and partition while adding or updating profile context.
> Flooding of logs  "Overwriting existing entry for backend" multi routes

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Resource.go
Problem: With Multiple ClientSSL profiles support from AS3 3.18,
ServerTLS object being a list, profiles are being added as per route profiles
in metadata. Though multiple routes are using same BIGIP pointer ClientSSL
profiles, the List is being populated with duplicates.
Solution: Make BIGIP pointer references in ServerTLS object for VS
unique.
Bug: CONTCNTR-1805
Affected branches: master
> Handle duplicate ClientSSL profiles added to AS3 ServerTLS object.

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
Problem: Records in ServerName and ServerSSL DataGroups are
toggled during verify interval which leads to posting AS3
declaration to BIG-IP though there is no change in monitored
resources.
Solution: Always sort the order of records being posted so that
controller post only when there is a change is resources being
monitored.
Bug: CONTCNTR-1806
> Sort Servername and ServerSSL DataGroup record items

- pkg/appmanager/profiles.go
Deleting the warning message "Both clientssl annotation and cert/key provided for Route" as we need to document for preference for both annotations and TLS spec certs used.
> Deleting the warning message

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
Problem: Records in TLS_Server class are
toggled during verify interval which leads to posting AS3
declaration to BIG-IP though there is no change in monitored
resources.
Solution: Always sort the order of records being posted so that
controller post only when there is a change is resources being
monitored.
JIRA: CONTCNTR-1822
> Sort TLS_Server certificate record names

- build-tools/golang/0001-Enable-AS3-Declaration-logging.patch
"make dev" image build that enable AS3 declaration logging was failing due to outdated patch.
Created new patch to fix this issue.
> Fix for make dev that enable AS3 declaration logging for developer image

- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/appManager.go
- pkg/resource/types.go
Problem: CIS does not update the big-ip object if the namespace label is removed for ConfigMaps.
Solution: Added the support for the management of namespace labels on AS3 Config Maps in CIS.
> Added namespace label support for AS3 ConfigMaps in CIS

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/agent.go
- pkg/agent/agentAS3.go
- pkg/agent/agentCCCL.go
- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3ConfigMap.go
Problem: When CIS configured as AS3 Agent, CIS will use the defined partition AND create another partition called <partition_name>_AS3. The first partition is used for FDB entries and the other partition is used for AS3 config, Using two different partitions is confusing and there is no real value on relying on two different partitions.
Solution: CIS should only support a single partition and <partition_name>_AS3 must be removed.
> Single partition for CIS when configured in AS3 agent

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/agent.go
- pkg/agent/agentCCCL.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/l2l3agent.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/appManager.go
- pkg/resource/types.go
Problem: When CIS is in AS3 mode, CCCL agent is also initialized
for L2/L3 support. This makes two agents while one agent is configured.
Solution: Remove CCCL init when AS3 is the agent. Extend L2/L3 for AS3 agent.
Affected Branches: master
Fixes issue #1312 partly.
> Simplify L2/L3 support for AS3 mode

- config/apis/cis/v1/types.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/profile.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Feature:
Process CRD TLSProfile with BIG-IP reference SSL Profiles
Description:
The scope of this PR is to process the TLSProfile CRD with BIG-IP reference client and server SSL. Example shown below.
```
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
name: reencrypt-tls
labels:
f5cr: "true"
spec:
tls:
termination: reencrypt
clientSSL: /common/clientssl
serverSSL: /common/serverssl
reference: bigip
hosts:
- foo.example.com
``` 
The behaviour of the http VirtualServer can be handled using httpTraffic object of VirtualServer CustomResource.
```
// -----------------------------------------------------------------
// httpTraffic = allow -> Allows HTTP
// httpTraffic = none  -> Only HTTPS
// httpTraffic = redirect -> redirects HTTP to HTTPS
// …
```
> Process CRD TLSProfile with BIG-IP reference SSL Profiles

- Makefile
Problem: Docker volume is not being removed in case of build failure, which is leading to build environment corruption.
Solution: Remove the volume as part of clean up with make clean.
> Remove Docker volume as part of clean up

- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/worker.go
Feature:
Add support to TLSProfile Informer AddEventHandler(UpdateFunc)
When a TLSProfile is updated by the User, All the Virtual Servers referencing it should sync for the changes with TLSProfile.
AddFunc and DeleteFunc are not handled in this PR.
- master
Regards,
> Add support to TLSProfile Informer AddEventHandler(UpdateFunc)

- pkg/agent/as3/as3ConfigMap.go
Problem:
AS3 Override was not working with the changes made to support Multiple AS3 Configmaps
Solution:
Fixed Issues. Override Configmap now works fine along with the changes made to support Multiple AS3 Configmaps.
Regards,
> Handle Issues with as3 Override functionality

- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Utils.go
Bug: CIS's copy of tenant names are not in sync with actual configuration and showing improper tenants logs
Solution: We should not consider previously deleted partitions and keep the tenant names in sync with actual configuration
> CIS Tenant Names in Sync with Actual Configuration

- pkg/crmanager/backend.go
Bug: CIS crash when modified the f5label of CRD virtual server
Solution: Provided a nil check for svcName
> CIS Crash When Modified The f5label of Virtual Server

- pkg/crmanager/resourceConfig.go
Problem:
CIS currently accepting Reencrypt TLS CRDs with httpTraffic as "allow"
Solution:
Ignoring Reencrypt TLS CRD with httpTraffic as "allow".
DockerImage:
nandakishoref5/k8s-bigip-ctlr:reencrypt_allow_block_v1
> Ignoring Reencrypt CRDs with httpTraffic as ALLOW

- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
Problem:
Validate TLSProfile CRD for Required SSL Parameters
Solution:
Validates TLSProfile CRD for Required SSL Parameters, This includes valid parameters for the type of termination(edge, re-encrypt and Pass-through).
Regards,
> Validate TLSProfile CRD for Required SSL Parameters

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
Bug: Unable to debug when given invalid CIS deployment parameter
Solution: Provided fix to handle invalid deployment parameter in CIS
> Handle Invalid CIS Deployment Parameter

- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
Problem: AB route traffic is being dropped with the presence of another route with WAF.
Root cause: Policies are not being added for AB routes, which are required for WAF to allow the traffic.
Solution: Add policies for AB routes, as well.
> Fix AB route issue with combination of another WAF route

- pkg/crmanager/backend.go
Problem: 
CIS not able to create multiple TLSClients in a single AS3 Declaration
Solution:
Remove the below condition ->
CIS will create a new TLSClient only if TLSClients is empty.
> CRD: Fix issue with multiple TLSClients

- pkg/crmanager/backend.go
CIS Crashes when we delete CR having TLS profile (only seen when using secrets).
affected branch: master
> [CRD] CIS Crashes when we delete CR

- pkg/appmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
Problem: When a route is deployed with Alternate Backend, policy is getting updated with each service one at a time alternatively, causing config to be being pushed to BIG-IP for every periodic check.
Solution: When a route is deployed with Alternate Backend, policy will have only the actual backend service all the time, as Alternate Backend Pool will be selected by iRule.
> Fix FlipFlop of Policy with AB deployment Routes

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/CustomResource.md
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
Hi, 
After a lot of research, we can now conclude that the issue is with the kubernetes code-generator package. However, as per few recommendations made in the community, I have made the below change to CIS which did not eliminate the issue but reduced the frequency of the issue.
Change in CIS ---> Instead of reading the namespace from the ObjectMeta of the TLSProfile Custom Resource... Pass the namespace of the VirtualServer Custom Resource as an argument to function which is trying to read the TLSProfile. 
I have raised the below issue on kubernetes organisation, code-generator repository in GitHub.
https://github.com/kubernetes/code-generator/issues/116
Regards,
> Fix issues with reading TLSProfile Intermittently

- pkg/crmanager/worker.go
Problem: Empty HTTP virtual server is being created in case of no HTTP traffic cases associated with HTTPS virtual server
Solution: Create a HTTP virtual server if HTTPS server has TLSAllowInsecure or TLSRedirectInsecure configured.
> Fix unnecessary creation of HTTP VirtulServer in case of No HTTP traffic

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Types.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Share node implementation for CRD, ingress and routes
Implementation of global share nodes flag(--share-nodes=true) which shares node across tenants.
> Share nodes implementation for CRD, ingress and routes

- pkg/crmanager/nccWorker.go
When referring to Resource Type, it is with respect to BIG-IP, so the resource type should be VirtualServer, but not NginxCisConnector.
> Fix NginxCisConnector resource type issue

- cmd/k8s-bigip-ctlr/main.go
NCC(NginxCisConnector) is added to the userAgent only when CIS is configured with "--nginx-cis-connect-mode=true" 
> Adding NCC to TEEMS User Agent

- pkg/appmanager/appManager.go
Problem:  without any actual update in as3 Configmap, update handler is triggered .
Solution: compare old and cur object before callback function for configmap updates.
> Fix continuous configmap updates

- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
Problem: CIS deletes the previously existing configuration from tenant , if corresponding configmap is edited with invalid config.
Solution: Ignore the invalid config and dont cleanup configuration unless configmap is updated with valid config or deleted.
> Handle invalid configmap processing

- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager_test.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/crmanager/backend.go
- pkg/resource/types.go
- pkg/test/configs/oneSvcOneNodeConfigExp.json
- pkg/test/configs/oneSvcTwoPodsConfigExp.json
- pkg/test/configs/twoSvcTwoPodsConfigExp.json
- pkg/test/configs/twoSvcsFourPortsFourNodesConfigExp.json
- pkg/test/configs/twoSvcsFourPortsThreeNodesConfigExp.json
- pkg/test/configs/twoSvcsOneNodeConfigExp.json
- pkg/test/configs/twoSvcsThreeNodesConfigExp.json
- pkg/test/configs/twoSvcsTwoNodesConfigExp.json
Problem : With multiport service support enabled from 2.2.1, while running CIS in nodeport mode, user has to provide service's nodeport value in the configmap servicePort.
Solution: Fix made to map service port to corresponding service's nodeport so that config maps are compatible for 2.2.0 and 2.2.1
Ref: 
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1564 
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1602
> Fix configmap serviceport value for nodeport mode #1602

- pkg/appmanager/appManager.go
Problem : Multiport service support was broken for nodeport mode in CIS 2.2.1 release.
Solution: Fix made to support the multiport service in nodeport mode.
> Fixed the multiport support for nodeport

- pkg/crmanager/resourceConfig.go
Global parameters SNAT needs to be updated by every Virtual server pointing to the same hostname.
> Global Param Update

- pkg/crmanager/resourceConfig.go
Global parameters SNAT needs to be updated by every Virtual server pointing to the same hostname.
> Global parameter update

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/TransportServer/transport-server.yaml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
Add allowVlans support for TransportServer resource
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1621
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1592 
TS yaml files now suppport below spec parameter : 
`allowVlans: ["/Common/devtraffic"] `
> Allow vlans support for TransportServer CRD

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
Problem: Currently virtual server custom resource does not allow to reference iRules created in bigip.
Solution: Added the support for irules in virtual server custom resource as mentioned in [Github-1571](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1571)
> Added support for irules for virtual server custom resource 

- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
Problem: TransportServer assigns wrong pool/service when same IP address is used with two transport server as mentioned in [Github-1671](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1671).
Solution: Added the logic for checking the combination of transport server's address and port are unique and the corresponding services are attached properly.
> Fixing the issue where TransportServer assigns wrong pool/service

- requirements.txt
Problem: CIS was unable to update the ARP entries on big ip when there is Mac address update instead of IP address.
Solution: Added a condition to remove the ipaddress field from payload when ever updating the ARP, as it's an immutable field.
> Fix for mac address update in ARP

- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.debug.runtime
- build-tools/Dockerfile.rhel7.runtime
- pkg/appmanager/validateResources.go
- pkg/crmanager/worker.go
`Failed to validate TLS cert and key: tls: failed to find any PEM data in certificate input`
Rootcause : certificate input via annotations were ignored 
Fix : If SSLAnnotations are present, hostname validation in certificates is skipped. As the certificate resides in BIGIP machine. 
`Hostname in route does not match with certificate hostname: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0` 
Rootcause : 
By default, crypto library used in vendor package for certificate validation, rejects certificates with CommonName (CN) mentioned in Certificate. It expects an env variable to be set GODEBUG=x509ignoreCN=0 to consider validating CommonName certificates. Note: SAN is recommended over CN and CN would also …
> Allow CN certificate in Routes and CRD

- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
Problem: Same Datagroup is being shared with all the Virtuals in CRD mode, which leads to security issue.
Solution: Create a dedicated Datagroup and iRule of each Virtual with the hosts it routes.
> Fix Datagroup sharing by Virtual Servers

- pkg/appmanager/appManager.go
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1641 
Problem : [DEBUG] [CORE] Finished syncing virtual servers default (24.867µs)
Solution:
[DEBUG] [CORE] Finished syncing virtual servers example_vs in namespace default (24.867µs)
> Fix VS log message

- CONTRIBUTING.md
Problem: CLA link is broken in Contributor docs.
Solution: Update CLA with correct URL.
Fixes: #1683
> CLA link is broken in Contributor docs.

- docs/RELEASE-NOTES.rst
- pkg/appmanager/routing.go
- pkg/crmanager/routing.go
In CIS 2.1.0 Release :- We were logging the error(<CLIENTSSL_DATA>: Unable to find pool for) in openshift_passthrough_irule  and  traffic for unknown host and HTTP2 request was being handled by policy.
In CIS 2.2.x Release:- We removed the error log (<CLIENTSSL_DATA>: Unable to find pool for) from openshift_passthrough_irule  and drops the connection in openshift_passthrough_irule , Hence traffic for unknown host and HTTP2 request is blocked by openshift_passthrough_irule .
In this PR,  We are removing the error logs (<CLIENTSSL_DATA>: Unable to find pool for) from openshift_passthrough_irule  and drops the connection in openshift_passthrough_irule  only for HTTP1.1 traffic for unknown host. If HTTP2 traffic is received we are not dropping …
> Fix for HTTP/2 traffic is blocked when http-2 profile is applied.

- pkg/agent/as3/as3Common.go
- pkg/appmanager/profiles.go
- pkg/resource/resourceConfig.go
- pkg/resource/resourceConfig_test.go
- pkg/resource/types.go
Problem: OpenShift-Route Parameter "caCertificate" is ignored by CIS.
Solution:  CIS is able to support `caCertificate` param from OpenShift edge termination Routes using AS3 `ChainCA`.
Signed-off-by: : Amit Gupta amitg2812@gmail.com
> Support for caCertificate in TLS Edge termination route

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
- pkg/agent/as3/postManager.go
**Description**: Currently AS3 minor versions such as (3.22.1, 3.19.1 etc. ) were not working with CIS 2.x releases.
**Changes Proposed in PR**: Added support for schema version support for AS3.
> Adding support for AS3 schema version

- pkg/crmanager/worker.go
**Description**:  Allow user to leverage IPAM Controller or specify a VirtualServer Address.
We need to provide more flexibility
if a VirtualServer Address is specified in the resource, don't leverage the IPAM Controller even if a cidr parameter is specified
if No VirtualServer Address is specified in the resource and a cidr parameter is specified, leverage the IPAM Controller
> Allow user to leverage IPAM

- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
Following recommendation from: https://github.com/F5Networks/charts/pull/44#issuecomment-782008655
This changes the format to add columns to the output for TransportServers i.e.:
```
$ kubectl get ts -n cluster1
NAME              VIRTUALSERVERADDRESS   VIRTUALSERVERPORT   POOL          POOLPORT   AGE
frontend1         10.1.10.82             8081                frontend1     80         3h20m
frontend2         10.1.10.82             8082                frontend2     80         3h20m
frontend3         10.1.10.82             8083                frontend3     80         3h20m
frontend4         10.1.10.82             8084                frontend4     80         3h20m
frontend5         10.1.10.82             8085                frontend5     80         3h20m
my-frontend-crd   10.1.10.82 …
```
> add columns to TransportServer CRD

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/resource/resourceConfig.go
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1458 
Reset rule exists in BIGIP even after deleting a whitelist/source-range annotation
Delete reset matching rule from policy and update config
**Fixes**: #1458
> Remove reset rule when whitelist range is updated

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**: Continuous overwrite of backend observed when using Configmap with iApp in cccl mode.
- Update pool members properly in iAppPoolmembers Table, so that resource config doesn't take this as an update and process every 30s  
**Fixes**: #1690
> Fix continuous overwrites with iApp in cccl mode

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/TransportServer/ts-with-service-address.yaml
- docs/_static/config_examples/crd/basic/virtual-with-aservice-address/README.md
- docs/_static/config_examples/crd/basic/virtual-with-aservice-address/example-service-address-with-virtual.yaml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/resource/types.go
**Description**:  Virtual server IP address can also be replaced by a reference to a Service_Address.
**Changes Proposed in PR**: Service_Address reference support in Virtual Server CRD and Transport Server CRD
**Fixes**: https://github.com/F5Networks/k8s-bigip-ctlr/issues/1592
> Service address support in VS and TS CRD

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Types.go
- pkg/appmanager/profiles.go
- pkg/resource/types.go
**Description**:  If ECDSA-signed certificate/key used in an OS-Route, the BIG-IP selects wrong certificate and present it to the client.
The BIG-IP selects the certificate which is marked as sni-default=true in specific client-ssl profile option
Add servername to clientssl profile for ECDSA cert
**Fixes**:  Resolves #1723
> Fix for ECDSA-signed cert in Openshift routes

- pkg/appmanager/validateResources.go
- pkg/crmanager/worker.go
**Description**: Hostname error mismatch in certificate is getting periodically logged. 
**Changes Proposed in PR**: Changed error log to debug log 
**Fixes**:  resolves https://github.com/F5Networks/k8s-bigip-ctlr/issues/1645
> Debug log for cert hostname mismatch

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  Add Feature Route Domain in CRD Mode
Added "default-route-domain" deployment parameter for supporting RD in CRD Mode.
**Fixes**: GitHub #1730
Intermediate CIS build: nandakishoref5/k8s-bigip-ctlr:rd_v3
> Add Feature Route Domain in CRD Mode

- docs/RELEASE-NOTES.rst
- pkg/crmanager/crManager.go
- pkg/crmanager/worker.go
CIS is unable to process any updates when used --namespace in CIS deployment. CIS post the config after the controller is restarted.
CR Informer was configured to listen to all namespaces. When CIS is started for specific namespaces, informer was not found. Added code to handle same.  
**Fixes**: 
Internal 679 ; CONTCNTR-2567
> CIS unable to post the declaration when configured to watch namespaces

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/Install/clusterrole.yml
- pkg/crmanager/crManager.go
**Description**:  _CIS is unable to track the changes happened that would effect IPAM Spec_
**Changes Proposed in PR**: _Delete and Create the IPAM resource, so that the old entires gets freed and IP requests made according the latest configs_
> Fix Stale entries of IPAM Spec when CIS restarts

- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/networkingV1/single-service-tls-ingress.yaml
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/ingress_test.go
- pkg/appmanager/profiles.go
- pkg/appmanager/validateResources.go
- pkg/resource/types.go
- pkg/test/utils.go
**Description**:  Added support for "virtual-server.f5.com/clientssl" annotation in ingress resource
**Changes Proposed in PR**:  Added support for "virtual-server.f5.com/clientssl" annotation in ingress resource
> Added support for "virtual-server.f5.com/clientssl" annotation in ingress resource

- docs/RELEASE-NOTES.rst
- pkg/crmanager/routing.go
- pkg/resource/resourceConfig.go
- pkg/resource/resourceConfig_test.go
**Description**:  Fixed rewrite-url annotation does not support to rewrite all child paths.
> Fix for rewrite target url for virtual server, ingress and route

- docs/RELEASE-NOTES.rst
- pkg/appmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
Fixed http redirect not working when used virtual-server.f5.com/rewrite-target-url annotation with routes
> Fixed http redirect not working when used virtual-server.f5.com/rewrite-target-url annotation with routes

- docs/RELEASE-NOTES.rst
- pkg/crmanager/node_poll_handler.go
**Description**: When a node is added/deleted to the cluster, CIS will not add the node as pool members unless any pod CIS monitors is deployed in that new node. Added TS processing for node poller.
> Fix inconsistent behaviour with CIS while adding nodes

- cmd/k8s-bigip-ctlr/main.go
**Description**:  Default periodic-sync-interval set to 30s
> Default periodic-sync-interval set to 30s

- docs/RELEASE-NOTES.rst
- docs/config_examples/crd/IngressLink/cis-config/cis_rbac.yaml
- docs/config_examples/crd/Install/clusterrole.yml
**Description**:  Updated ClusterRole - Removed `resourceName` in rule for secrets resources.
**Changes Proposed in PR**: From 2.5, CIS monitors Secret resources. So update the ClusterRole. 
- [] Updated the documentation
> Update secrets RBAC and upgrade 2.5 notes properly

- pkg/crmanager/crManager.go
**Description**: CIS not deleting old f5ipam cr which is not in use (During partition name changes).
**Changes Proposed in PR**: CIS deletes all IPAM CR while starting.
> Fix:CIS not deleting old f5ipam cr which is not in use

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
**Description**:  If there is newline character at end of file due to which CIS fails to map the username, password and url. We need to remove the newline character while parsing file.
**Changes Proposed in PR**: Removing the newline characters from file while mapping the credentials. Customer can use --credentials-directory parameter instead of these three parameters (--bigip-username, --bigip-password, --bigip-url ). For that they need to create three files named username, password and url inside a directory and then create a Kubernetes secrets using this directory. Please see the CIS deploy file for [example](https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/example-bigip-credentials-directory.yaml)
**Fixes**: #1921
> Fixing the issue with credential-directory parameter

- pkg/crmanager/crManager.go
**Description**:  IPAM CR not creating with partition name in all lower case.
**Changes Proposed in PR**: Fixed IPAM CR creation with partition name in all lower case.
> IPAM CR not creating bug fix

- pkg/crmanager/crManager.go
- pkg/crmanager/worker_test.go
**Description**:  _Kubernetes does not accept capital letters as part of resource names and CIS uses BIGIP partition names as part IPAM resource name. When BIGIP partition has a capital letter in its name, there is a conflict. _
**Changes Proposed in PR**: To solve this issue CIS replaces Capital letters with corresponding small letter along with an extra "-"
> Update IPAM resource name format to support partitions with Captial letters

- pkg/crmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
**Description**:  _For CIS use case of formatting IP address, strings.ReplaceAll solves efficiently reducing processing time by a factor of 2. => 50% lesser time _
> Using strings.ReplaceAll to improve performance

- pkg/crmanager/resourceConfig.go
- pkg/resource/routeDomain.go
**Description**:  Regex calls accounted for 15% of memory utilisation while running 1000 ingresses on scale setup. 
> Replace Regex to improve performance

- pkg/appmanager/profiles.go
- pkg/appmanager/routing.go
- pkg/crmanager/profile.go
- pkg/crmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
**Description**:  reflect package impacts performance. reflect.DeepEqual consumed ~12% = 1 GB of memory while running performance on scale setup with 1000 ingresses. 
> Replace reflect.DeepEqual to improve Performance

- docs/RELEASE-NOTES.rst
- pkg/crmanager/backend.go
**Description**: Add CIS BIGIP credential to GTM if GTM credential is not present
> Add CIS BIGIP credential to GTM if GTM credential is not present

- pkg/crmanager/resourceConfig.go
- pkg/crmanager/resourceConfig_test.go
- pkg/crmanager/routing.go
LTM resource names are framed based on hostname in certain places. Now this need to be based on context, in case of single host, hostname can be used, but in case of Multi-host hostGroup can be used.
- Helper functions identify the context and frame LTM resource name accordingly.
> LTM resource name changes for multihost support

- docs/config_examples/customResourceDefinations/customresourcedefinitions.yml
**Description**:  Pattern matching update for arg nodeMemberLabel. Allowed "/" in prefix part of nodeMemberLabel. Ex.: f5/role=worker
> Pattern matching update nodeMemberLabel

- docs/config_examples/customResource/Policy/transportserver-with-policy.yaml
- docs/config_examples/customResource/Policy/virtualserver-with-policy.yaml
- pkg/crmanager/backend.go
Policy CRD Firewall and log profile assignment for transport server was missed while framing AS3 declaration
- common AS3 supported options in VS and TS are now processed in `processCommonDecl` function
**Fixes**: internal CONTCNTR-3022
> Fix firewall and log profile support for transport server

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/l2l3agent.go
- pkg/agent/as3/postManager.go
**Description**:   Earlier CIS used to send Unified AS3 declaration with multiple ConfigMaps. A defect in a VS/Tenant will stop applying the good VS/Tenant configuration. This feature will be available only with CIS parameter --filter-tenants=true.
**Changes Proposed in PR**: With these changes CIS will be sending the Unified AS3 declaration to each tenant's api endpoint.
**Fixes**: resolves sr/1-7481508471/
> Fix for TENANT based AS3 declarations of ConfigMaps

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Manager.go
- pkg/appmanager/validateResources.go
**Description**:  Fix crash while validating secrets
- handle `use-secrets` config option  while checking for valid secrets in ingresses and configmaps 
- handle nil ingress and ConfigMap informer case 
**Fixes**: resolves #2102, resolves #2016
> Fix crash while validating secrets

- docs/RELEASE-NOTES.rst
- pkg/crmanager/resourceConfig.go
**Description**:  Fix for Allow type LoadBalancer with different TargetPort and Port values
**Changes Proposed in PR**: Replaced the service port value with target port for pool and health monitor in service type load balancer
**Fixes**: resolves #2014
> Fix for Allow type LoadBalancer with different TargetPort and Port values

- go.mod
- go.sum
- vendor/github.com/F5Networks/f5-ipam-controller/pkg/ipammachinery/ipam.go
- vendor/modules.txt
**Description**:  Update vendor with IPv6 support for ipam f5-ip-provider
- updated go.mod and synced vendor
**Fixes**: internal CONTCNTR-2994 
https://github.com/F5Networks/f5-ipam-controller/pull/83
> Update vendor with IPv6 support for ipam f5-ip-provider

- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
**Description**:  _VirtualServers are not being processed if hostGroup is used and VirtualServerAddress is specified only in one VS_
**Changes Proposed in PR**: VirtualServers will be processed even if VirtualServerAddress is specified in one VS.
> Fix VirtualAddress issue with HostGroup

- pkg/crmanager/worker.go
Fix for  Allow type LoadBalancer with different TargetPort and Port value in nodeport mode
> Fix for  Allow type LoadBalancer with different TargetPort and Port value in nodeport mode

- pkg/crmanager/worker.go
**Description**:  Modify serviceTypeLB naming convention to support ipv6 addresses
- Modify serviceTypeLB naming convention to support ipv6 addresses
> Modify serviceTypeLB naming convention to support ipv6 addresses

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
**Description**:  Sometimes, even before teem data is initialised, CRManager is trying to modify it. This is resulting in a crash. This will not be an issue in appmanager as informers are setup after teemdata initialisation. 
- Initialise Teem data immediately after starting CR informers, even before get BIGIP registration key request.
- Also, updating latest FIC go mod
**Fixes**: internal 791, 800
> Fix teem CRD initialisation

- docs/RELEASE-NOTES.rst
- pkg/crmanager/resourceConfig.go
**Description**:  Support multihost VS policy rules for same path and service backend combination. 
- CIS with NGINX KIC for multiple hosts with default path /  
- append hostnames with an existing hostgroup rule. 
**Fixes**: internal CONTCNTR-3060
> Support multihost VS policy rules for same path and service backend combination

- docs/RELEASE-NOTES.rst
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  Fix for ExternalDNS adds both VSs to a Wide IP pool. Also added the fix for processing the dns resources if virtual server is deleted.
**Changes Proposed in PR**: Fix for ExternalDNS adds both VSs to a Wide IP pool. Also added the fix for processing the dns resources if virtual server is deleted.
**Fixes**: resolves #1918
> Fix for ExternalDNS adds both VSs to a Wide IP pool

- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
When root domain and wildcard domain refer to same VSaddress, CIS is only pushing the latest updated resource config, it is overwriting the policies/rules. 
- Added an error log stating config fault and it stops further processing. 
- Fixed existing unit testcases and added new one. 
**Fixes**: resolves internal 805
> Fix VS with same virtual address but different hosts

- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
Reverts F5Networks/k8s-bigip-ctlr#2186
Reverting this PR to avoid hybrid - IPAM and static IP address combination -  deployment conflicts
> Revert "Fix VS with same virtual address but different hosts"

- docs/RELEASE-NOTES.rst
- helm-charts/f5-bigip-ctlr/Chart.yaml
- helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
**Description**:  Fix for Helm Chart ClusterRole Does Not Have Correct Permissions
**Changes Proposed in PR**: Fixed the clsuter role permissions
**Fixes**: resolves #2184
> Fix for Helm Chart ClusterRole Does Not Have Correct Permissions

- docs/RELEASE-NOTES.rst
- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/routing.go
**Description**: Added fix for processing oldest route when same host and path in routes
**Changes Proposed in PR**: Updated the sorting logic of routes and removed unnecessary variables
> Added fix for processing oldest route when same host and path in routes

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**:  Fix ExternalDNS adds both VSs to a Wide IP pool with using "httpTraffic: allow" with VS CR
**Changes Proposed in PR**: Fix ExternalDNS adds both VSs to a Wide IP pool with using "httpTraffic: allow" with VS CR
**Fixes**: resolves #2212
> Fix ExternalDNS adds both VSs to a Wide IP pool with using "httpTraffic: allow" with VS CR

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**:   Fixed github issue 2222 deleting virtual server when hostGroup is used.
**Fixes**: resolves #2222
> Fix deleting VirtualServer when hostGroup is used

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**:  Fix for CIS crash when a wrong ConfigMap is created and deleted subsequently
**Fixes**: resolves #2234
> Fix for CIS crash when a wrong ConfigMap is created and deleted subsequently

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Fix recreating arp entries
- updating f5-ctlr-agent, f5-cccl commit ID's
- addresses both as3 and CCCL mode ARP entries recreation issue
**Fixes**: resolves #2077
Related PRs: 
https://github.com/f5devcentral/f5-ctlr-agent/pull/58
https://github.com/f5devcentral/f5-cccl/pull/272
> Fix recreating arp entries on restart

- cmd/k8s-bigip-ctlr/main.go
- requirements.txt
**Description**:  Allow pushing resources in CCCL nodeport mode and openshift cluster mode
- introduced new disable-arp entry in global section for agent to distinguish whether or not to push ARP/FDB's
**Fixes**: internal issues 836, 837
> Allow pushing resources in CCCL nodeport mode and openshift cluster mode

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/backend.go
- pkg/controller/types.go
**Description**:  Allow FDB updates in CRD mode in openshift cluster mode
- CRD mode initialises python driver from initController
- Added disableARP parameter to global section. This will be used to make a decision in f5-ctlr-agent
> Allow FDB updates in CRD mode in openshift cluster mode

- pkg/controller/backend.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
Reverts F5Networks/k8s-bigip-ctlr#2288
ipam and hostgroup combinations needs to be validated. Reverting changes for now.
> Revert "virtualServerAddress must be present for hostGroup"

- pkg/controller/backend.go
**Description**:  Poll tenant status continuously and block incoming config updates for 201
* On receiving 201 from AS3, CIS will poll continuously for the task status.  Any incoming declarations will not be posted, and 503 is avoided 
* Refactored poll status and retry failed tenant functionality - split'ed into functions 
* Handled invalid config rollback case
> Poll tenant status continuously and block incoming config updates for 201

- pkg/agent/cccl/outputConfig.go
It seems inside copyResourceData(), it forgot to
copy over iapps as well. To reproduce, if you set log-level to DEBUG,
and you create a configmap for iapp, you will see logs like
"[CCCL] LTM Resources: XXX", which does not include iapp
part.
**Fixes**: resolves #2191
> iapps is not copied over

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3ConfigMap.go
**Description**:  Backwards incompatible in multiple port service
**Changes Proposed in PR**: If the service port does not match with the configMap port we are adding the first port of the service in the endpoint, this will make sure that old configMaps keeps working like earlier. 
**Fixes**: resolves #2255
> ConfigMap backward compatibility fix

- requirements.txt
**Description**:  Currently, CIS just attaches only secured GTM pool members ignoring to remove the oldGTMPoolmembers created by CIS if existing. This fix ensures that CIS properly removes the old GTM pool members from the BIGIP.
> Remove unused GTM PoolMembers created by CIS in old versions

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
- pkg/controller/worker.go
**Description**:  Added support for passthrough traffic termination for routes 
**Changes Proposed in PR**: All the passthrough traffic will be handled via iRule only for both virtual server and route resources. Removed the policy rules implementation for virtual server's passthrough traffic.
> Added support for passthrough traffic termination for routes 

- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
**Description**:  Fixed the issue of CIS not processing the complete route group if service is not found for any route
**Changes Proposed in PR**: Fix to process route group if service not found for any route
> Fix to process route group if svc not found

- pkg/controller/constants.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
**Description**:  Fixed issue of CIS allowing insecure traffic for all the routes when one route is having insecureEdgeTerminationPolicy policy as allow.
**Changes Proposed in PR**: Skip adding forwarding policy rule to HTTP virtual server if the route doesn't allow insecure traffic.
> Fixed issue related to allowing of insecure traffic

- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/test/utils.go
**Description**:  _When an extended spec local configmap was deleted, the controller was not checking for other local configmaps_
**Changes Proposed in PR**: look for other local configmaps and process latest available if the local configmp is deleted
> Fix alternate extSpec local ConfigMap issue

- pkg/controller/responseHandler.go
When the cluster does not have any CIS managed resources, resource status update needs to be handled correctly. 
- Handle resource status update with zero resources in cluster
> Handle resource status update with zero resources in cluster

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/ExternalDNS/README.md
- docs/config_examples/customResource/ExternalDNS/externaldns-pool-priority-order.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- docs/upgradeProcess.md
- pkg/controller/types.go
- pkg/controller/worker.go
- requirements.txt
- Support GTM global-availability mode and order precedence with EDNS.
- With global-availability LB mode,  BIG-IP GTM distributes DNS name resolution requests to the first available virtual server in a pool. BIG-IP GTM starts at the top of a manually configured list of virtual servers and sends requests to the first available virtual server in the list. Only when the virtual server becomes unavailable does BIG-IP GTM send requests to the next virtual server in the list. Over time, the first virtual server in the list receives the most requests and the last virtual server in the list receives the least requests.
- https://github.com/f5devcentral/f5-ctlr-agent/pull/64
- Support new order …
> Support GTM global-availability mode and order precedence with EDNS

- pkg/controller/nativeResourceWorker.go
**Description**:  CIS is not reverting the global policies when local configMap is deleted
**Changes Proposed in PR**: When a local config map is deleted we are looking for the configMap in the respective namespace and then CIS will fallback to Global configMap
> Fix to pick global config when local configMap is deleted

- docs/config_examples/rbac/clusterrole.yaml
**Description**:  Upgrade Process includes clusterrole with missing statements in section “Upgrading from 2.4.0 to 2.5.0”
**Changes Proposed in PR**: Updated cluster roles to provide access to routes resource for service account
> Added missing clusterrole permission for routes in OpenShift

- pkg/controller/node_poll_handler.go
**Description**:  Enqueue update event for resources during node update
- Previously, create event was getting enqueued, and since the resource is already processed, the resource wasn't getting processed. Fixed to include an update event while enqueuing
> Enqueue update event for resources during node update

- docs/RELEASE-NOTES.rst
- pkg/controller/resourceConfig.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Fix for confusing EDNS Pool name
**Changes Proposed in PR**: Instead of unique timestamp we will be using the bigip hostname and partition for creating the poolName.
**Fixes**: resolves #2336
> Fix for confusing EDNS Pool name

- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Utils.go
CIS should not delete existing config when configmap in bad format 
The issue happens because:
The coming configmap json(containing partitions to create) is fully parsed because of bad schema format.
Thus, by comparing existing configmap in CIS, the fails-to-parsed partition is considered as `deleteTenants`.
The fix can be: recording the parsing result, more concisely tell later logic to distinguish it's invalid or real-missing.
**Fixes**: resolves SR  1-8181523521 / connell-1
> Fix issue of deleting partition when bad as3 schema.

- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
- pkg/controller/worker.go
**Description**:  Changes in Pool and Monitor Name Format for CRD to support HostGroup with same path and same service-name with different host and health monitor strings.
> Changes in Pool and Monitor Name Format for CRD

- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  Allow allowOverride value to be a string in nextgen route spec
- modify allowOverride value to be string 
- added and modified UT 
**Fixes**: internal
> Allow allowOverride value to be a string in nextgen route spec

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**:  Fix for empty pool members in AS3 declaration in case of hubmode
**Changes Proposed in PR**:  Replaced use of endpoint informer with kubeclient to fetch endpoints as in case of hubmode with namespace specified, cis doesn't watch all namespaces.
> Fix for empty pool members in AS3 declaration in case of hubmode

- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Resource.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/appManager.go
- pkg/vlogger/log.go
- pkg/vxlan/vxlanMgr.go
Reverts F5Networks/k8s-bigip-ctlr#2194
@zongzw , After integration we are observing that these logs are very frequent and almost increase the CIS logs by 33%. 
As it's not used by any customer, I would advice you to move it to a new log level called TRACE or Otherwise you can also create a new environment variable to enable such logs only for your usecase.
> Revert "Add Timeit function for timecost calculations."

- pkg/controller/controller.go
**Description**:  [GITLAB #919] [NextGenRoutes] CIS havent enabled sharedNodes for NodePort mode
**Changes Proposed in PR**: if pool-member-type is nodeport enabled shareNodes by default
> Enable shareNodes by default for pool-member-type NodePort

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/ingress-with-vs-ip-cidr.yaml
- pkg/agent/as3/as3Utils.go
- pkg/appmanager/appManager.go
- pkg/appmanager/ingress.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/schema.go
- pkg/controller/backend.go
- pkg/resource/resourceConfig.go
- pkg/resource/resourceConfig_test.go
- pkg/resource/routeDomain.go
- pkg/resource/routeDomain_test.go
- pkg/resource/types.go
- requirements.txt
**Description**:  Added support to configure netmask for Virtual Server for Ingress
**Changes Proposed in PR**: CIDR notation is allowed for virtual-server.f5.com/ip in the annotation of ingress resources.
**Fixes**: resolves #1850
> Added support for netmask for Virtual server

- docs/RELEASE-NOTES.rst
- docs/config_examples/nativeResources/configmap/extendedRouteConfig.yaml
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  Add support for BigIP ClientSSL/ServerSSL profile in NextGen Routes
**Changes Proposed in PR**: Added support to refer to bigip ClientSSL/ServerSSL 
> Added support for BigIP ClientSSL/ServerSSL profile reference in NextGen Routes

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/vlogger/README.md
- pkg/vlogger/doc.go
- pkg/vlogger/logger.go
**Description**:  Add support for log-file deployment parameter to store the CIS logs in a file
**Changes Proposed in PR**: We can specify the --log-file deployment parameter in CIS which enables redirects all the logs to the specified log file. If --log-file deployment parameter is not defined CIS will put the logs in stdout & stderr streams.
**Fixes**: resolves #2158
> Add support for log-file to store the CIS logs

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/CustomResource.md
- docs/config_examples/customResource/VirtualServer/virtual-with-pool-svc-different-ns/vs-with-pool-svc-diff-ns.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/resourceConfig.go
**Description**:  Renamed svcNamespace field in Pool of Virtualserver CR to serviceNamespace
**Changes Proposed in PR**: Renamed svcNamespace field in Pool of Virtualserver CR to serviceNamespace
**Fixes**: resolves #1933
> Renamed svcNamespace field in Pool of Virtualserver CR to serviceNamespace

- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/ingress-https-monitor.yaml
- pkg/agent/as3/as3Common.go
**Description**:  Fix to set ingress https monitor send string
**Changes Proposed in PR**:  Support given to set send string for ingress https monitor
**Fixes**:  #2394
> Fix to set ingress https monitor send string

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
**Description**:  Fix for adding unique pool members in nodePort mode
**Changes Proposed in PR**: Fix for adding unique pool members in nodePort mode
**Fixes**: resolves #2492
> Fix for adding unique pool members in nodePort mode

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**: Fix CIS adding both VIPs to GTM pool members for ingresslinks
**Changes Proposed in PR**:  Fix to add only one member to pool for IngressLink
**Fixes**: gitswarm issue #847 
> Fix CIS adding both VIPs to GTM pool members for ingresslinks

- docs/RELEASE-NOTES.rst
- pkg/controller/informers.go
- pkg/controller/worker.go
**Description**:  IngressLink doesn’t remove the services
**Changes Proposed in PR**: Fix to monitor NGINX+ service changes
> Fix to monitor NGINX+ service changes

- pkg/controller/types.go
- pkg/controller/worker.go
**Description**: CIS fails to send AS3 declaration for the recreated domain after IPAM controller restart.
**Changes Proposed in PR**: Fixed issue 
> Fix CIS fail to send as3 for recreated domain after IPAM restart

- docs/RELEASE-NOTES.rst
- pkg/controller/responseHandler.go
- pkg/controller/worker.go
**Description**:  Update ExternalIP of associated services of Type LB for VS and IngressLink CR as the associated service resource is in pending state if not updated for service Type LB.
**Fixes**: resolves #2586
> Update ExternalIP of associated services of Type LB for VS CR and IngressLink CR

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/healthMonitors.go
**Description**:  CIS fails to remove old HTTP ingress monitor when type is modified.
**Changes Proposed in PR**: Fix to remove old ingress monitor when type is modified
> Fix to remove old ingress monitor when type is modified

- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigWithTLSCertsK8SSecrets.yaml
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/worker.go
**Description**:  Support for TLS profiles as K8S secrets in nextGenRoutes
**Changes Proposed in PR**:  TLS certs as K8S secrets can be specified in the extended Config map.
> Support for TLS profiles as K8S secrets in nextGenRoutes

- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
**Description**:  Path based A/B iRule is getting added for domain based A/B route
**Changes Proposed in PR**: Fix to add path based A/B IRule only for path based rencrypt route
> Fix to add path based A/B IRule only for path based rencrypt route

- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/deployment/deployment-pod-with-livenessprobe.yaml
- pkg/controller/nativeResourceWorker.go
- pkg/controller/worker.go
**Description**:  Support to create Health Monitor from the pod liveness probe that route exposes
**Changes Proposed in PR**: Added Support to create Health Monitor from the pod liveness probe that route exposes
> Support to create Health Monitor from the pod liveness probe that route exposes

- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfig.yaml
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
…gmap
**Description**:  Support for Default SSL profiles from baseRouteSpec in extended Confi…
**Changes Proposed in PR**: Added support for default client and server server SSL profiles in nextGen routes
> Support for Default SSL profiles from baseRouteSpec in extended Configmap

- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/ingress-with-health-monitors.yaml
- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Common_test.go
- pkg/agent/as3/as3Types.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/healthMonitors_test.go
- pkg/resource/types.go
- requirements.txt
**Description**:  Add sslProfile to https health monitors for Ingress
**Changes Proposed in PR**:  Add sslProfile to https health monitors for Ingress
> Add sslProfile to https health monitors for Ingress

- config/apis/cis/v1/types.go
- pkg/controller/types.go
- pkg/resource/types.go
**Description**:
Removes an unnecessary extra `omitempty` struct tag option on `TrafficGroup` fields in the `ServiceAddress` types.
**Fixes**:
> Remove repeated `omitempty` struct tag option from `TrafficGroup` fields

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/healthMonitors.go
- pkg/appmanager/healthMonitors_test.go
**Description**: Remove unused ingress health monitors
**Changes Proposed in PR**: Removing health monitors if no pool uses it
> Remove unused ingress health monitors

- docs/RELEASE-NOTES.rst
- pkg/controller/validate.go
- pkg/controller/worker_test.go
**Description**:  Validate insecure Virtual Server CR
**Changes Proposed in PR**: Added check to ensure HTTPTraffic is not set for insecure VS
**Fixes**: resolves #2686
> Validate insecure Virtual Server CR

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/controller/node_poll_handler.go
- pkg/controller/node_poll_handler_test.go
**Description**:  Remove nodes with NotReady state from bigip pool members in NodePortMode.
**Fixes**: resolves #2677
> handle node notready update 

- docs/config_examples/customResource/DeploymentParameters/DefaultRouteDomain/README.md
**Description**:  Add Default Route Domain Documentation applicable for MultiParition feature and single Partition
> Add Default Route Domain Documentation

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3ConfigMap.go
**Description**:  Fix  for AS3 label not working in AS3 configmap with filter-tenants
**Fixes**: resolves #2725
> Fix AS3 label not working in AS3 configmap with filter-tenants

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/README.md
**Description**: NextGen Route Controller takes precedence over Legacy Route deployment parameters
> NextGen Route Controller takes precedence over Legacy Route deployment parameters

- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers.go
- pkg/controller/multiClusterInformers.go
- pkg/controller/multiClusterWorker.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/node_poll_handler.go
- pkg/controller/node_poll_handler_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Multi Cluster service support with improved nodes & service update processing 
**Changes Proposed in PR**: This PR addresses following:
1.  **The initial processing of CIS resources:** Earlier CIS used to process all the services at CIS start up and create a poolMember cache. With this changes now CIS does not cache any services at startup instead it directly process the routes/serviceTypeLB/VS/TS/IngressLink and then maintains the pool member cache only for services which are referenced in these resource. This will improve the CIS start up time as we won't process all the services in system and also improve memory used by CIS as less services will be in the cache.
2. **Processing of service updates** Earlier for service changes we use to have svcResourceCache which used …
> Multi Cluster service support with improved node & service update processing

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/README.md
- docs/config_examples/customResource/Policy/policy-with-client-server-ssl-profile.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- docs/upgradeProcess.md
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**: Add support for setting client and server ssl profiles from policy in NextGen
**Changes Proposed in PR**: Add support for setting client and server ssl profiles from policy in NextGen
> Add support for setting client and server ssl profiles from policy in NextGen

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/postManager.go
**Description**:  Fix for handling fail-over scenarios
**Changes Proposed in PR**: With these changes we will we performing following actions at CIS startup so we delete any partition which is not monitored by CIS HA.
1. Get AS3 Declaration
2. Compare tenants got from BigIP AS3 declaration with current rsConfig tenants 
3. Any tenant which is not there in current rsConfig needs to be removed from BIGIP. 
4. Add an empty partition config in rsConfig to delete the tenant.
Note: We are using tenant label to identify that tenant is created by this CIS instance. Tenant label consist of BIGIP-IP and default partition to identify unique CIS instance.
> Fix for handling fail-over scenarios

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/README.md
- docs/config_examples/customResource/Policy/policy-with-client-server-ssl-profile.yaml
- docs/config_examples/customResource/Policy/policy-with-http-analytics-profile.yaml
- docs/config_examples/customResource/Policy/policy-with-multiple-irules.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- docs/config_examples/next-gen-routes/README.md
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigWithHTTPServerPolicyCR.yaml
- pkg/controller/backend.go
- pkg/controller/controller_suit_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker_test.go
**Description**:  Handle policy for insecure VS in NextGenRoutes
**Changes Proposed in PR**: Added support to apply different polices/profiles to HTTP and HTTPS VS using httpServerPolicyCR in route groups in NextGen routes.
> Handle policy for insecure VS in NextGenRoutes

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/controller/controller.go
- pkg/controller/node_poll_handler.go
- pkg/controller/types.go
- pkg/vxlan/vxlanMgr.go
- pkg/vxlan/vxlanMgr_test.go
Cilium VTEP support for BIG-IP has been added in Cilium 1.12.0 release https://isovalent.com/blog/post/cilium-release-112/#vtep-support
add --cilium-name to allow user to specify --cilium-name=<tunnel name> for Cilium VXLAN and BIG-IP VXLAN integration, see deployment guide
https://github.com/f5devcentral/f5-ci-docs/blob/master/docs/cilium/cilium-bigip-info.rst
**Changes Proposed in PR**: #2825 
add --cilium-name to specify BIG-IP tunnel name for Cilium VXLAN integration, so user will not be confused when asked to use --flannel-name to specify BIG-IP tunnel name
Co-developed-by: Vincent Li <v.li@f5.com> 
**Fixes**: resolves #2825, #2826
> Add Support of CiliumTunnelName parameter

- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/TransportServer/monitors-transport-server.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
**Description**:  Add HTTP Monitor Support for Transport Server CR
Add HTTP Monitor Support for Transport Server CR
**Fixes**: resolves #2550
> Add HTTP Monitor Support for Transport Server CR

- pkg/controller/controller.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Skip recreating IPAM CR
**Changes Proposed in PR**: Comparing all the CIS processed IPAM entries with the existing IPAM CR entries and removing the unused iPAM entries from the IPAM CR after the first Post Call. 
> Skip recreating IPAM CR

- pkg/controller/nativeResourceWorker.go
**Description**:  Fix for removing LTM obj on namespace deletion in NGRoutes
**Changes Proposed in PR**: Handling policy CR not found after VS deletion.
> Fix for removing LTM obj on namespace deletion in NGRoutes

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Exclude the removal of static ARP entries for Flannel CNI during CIS restart.
This issue is occurring only in some scenarios.
> Exclude the removal of static ARP entries for Flannel CNI during CIS restart

- docs/RELEASE-NOTES.rst
- pkg/controller/resourceConfig.go
**Description**: Fix monitor not creating for VS CRD when send string is missing
**Changes Proposed in PR**: Fix monitor not creating for VS CRD when send string is missing
**Fixes**:  #2800
> Fix monitor not creating for VS CRD when send string is missing

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**:  Ignore virtualservername if hostgroup parameter is  configured on virtualserver CR
**Fixes**: resolves #2867
> Ignore virtualservername if hostgroup configured

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingress_test.go
**Description**:  Moving the node informers at appManager level
**Changes Proposed in PR**: Currently we are creating node informer for each namespace in namespace mode. With this PR we will be creating a single node informer at controller level
**Fixes**: resolves #2898
> Moving the node informers at appManager level

- docs/RELEASE-NOTES.rst
- pkg/controller/resourceConfig.go
**Description**:  Add validation message for monitor when send string is missing
**Changes Proposed in PR**: Add validation message for monitor when send string is missing
> Add validation message for monitor when send string is missing

- pkg/controller/resourceConfig.go
**Description**:  Enable tcp monitor for VS crd without send string
**Changes Proposed in PR**: Enable tcp monitor for VS crd without send string
> Enable tcp monitor for VS crd without send string

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Code Refactoring for extended configmap support in crd mode
**Changes Proposed in PR**: This PR adds support for new CIS deployment parameter for passing the extended configMap (--extended-spec-configmap). This PR also includes multi-cluster route annotation validation.
> Code Refactoring for extended configmap support in crd mode

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/ingress_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/resource/resourceConfig.go
- pkg/resource/resourceConfig_test.go
- pkg/resource/types.go
**Description**: Improve error handling and K8S resources fetching method
**Changes Proposed in PR**:   To reduce the risks of improper processing of K8S resources when error is encountered while communicating with K8S API server, the following changes are introduced:
1. Improve Error handling: If error encountered while fetching pool members then handle it instead of setting empty pool members.
2. Use informers to fetch K8S resources:   Temporary issues with K8S API server doesn't impact CIS as resources are fetched from local cache maintained by informers.
**Fixes**: resolves #2909
> Improve error handling and K8S resources fetching method

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**: fix to process clustername and service add change under extendedserviceReferences
> fix to process clustername and service add change under extendedserviceReferences

- docs/config_examples/next-gen-routes/README.md
- pkg/controller/nativeResourceWorker.go
- pkg/controller/worker.go
**Description**:  Fix CIS crash when GCM is missing 
**Changes Proposed in PR**:  This PR has the following improvements:
1. Fix CIS crash when Global ConfigMap is missing when CIS is running in secondary mode
2. CIS exits gracefully if Global ConfigMap is missing when it start running.
> Fix CIS crash when GCM is missing

- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/extendedConfigmap/global-config-with-primary-cluster-health-probe.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-active-active.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster.yaml
- pkg/controller/nativeResourceWorker.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Rename multiCluster parameters and update documentation
**Changes Proposed in PR**:  Following changes are done in this PR:
1. HA mode names and documentation have been improved
2. HA config and endpoint parameters have been renamed
3. MultiCluster documentation has been improved
**Fixes**: resolves #2990
> Rename multiCluster parameters and update documentation

- pkg/controller/resourceConfig.go
- pkg/controller/worker.go
**Description**:  Fix handling service creation after VS/TS CR creation
**Changes Proposed in PR**: Reprocess VS/TS resources associated with the service when is created the service is created after the creation of the VS/TS.
> Fix handling service creation after VS/TS CR creation

- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/extendedConfigmap/global-config-with-primary-cluster-health-probe.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-active-active.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster.yaml
- pkg/clustermanager/types.go
- pkg/controller/multiClusterHealthProbeManager.go
- pkg/controller/multiClusterInformers.go
- pkg/controller/multiClusterWorker.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Rename multiClusterConfigs to externalClustersConfig Section for better user understanding 
- Renamed multiClusterConfigs to externalClustersConfig Section  for better user standing.
- Modifications to log messages where necessary.
- Improved few Multicluster log messages.
**Fixes**: resolves #2999
> Rename multiClusterConfigs to externalClustersConfig Section

- pkg/controller/nativeResourceWorker.go
**Description**:  Fix to process local configmap on global configmap allowOverride change
**Changes Proposed in PR**: Fix to process local configmap on global configmap allowOverride change
> Fix to process local configmap on global configmap allowOverride change

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/worker.go
**Description**: Reprocess route groups on cluster ratio update
1) Reprocess route groups on cluster ratio update
2) Add log to print multi-cluster-mode
3) Warning log if GCM is created in a namespace not monitored by CIS
> Reprocess route groups on cluster ratio update

- pkg/controller/multiClusterWorker.go
- pkg/controller/worker.go
**Description**:  CIS is not caching the pods in nlpstore, Hence no pool members are added in nodeportlocal mode.
> Fix for pod caching in nodeportlocal mode

- docs/config_examples/Install/openshift/HA/f5-k8s-bigip-ctlr-openshift-ose-bigip-01.yaml
- docs/config_examples/Install/openshift/HA/f5-k8s-bigip-ctlr-openshift-ose-bigip-02.yaml
- docs/config_examples/Install/openshift/StandAlone/f5-k8s-bigip-ctlr-openshift.yaml
**Description**:  When following either https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-standalone.html
or https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html
CIS creation brings the following warning
```
$ oc create -f f5-bigip1-ctlr-deployment.yaml 
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cntr-ingress-svcs" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cntr-ingress-svcs" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cntr-ingress-svcs" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cntr-ingress-svcs" must set …
```
> #2967 fix pod security violation warning on openshift installation

- build-tools/Dockerfile.ubi
- requirements.txt
**Description**:  Upgrade python version to 3.11.5 to mitigate CVE-2023-40217
> Upgrade python version to 3.11.5

- pkg/controller/multiClusterWorker.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/worker.go
**Description**:  Fix to populate pool mem when svc is missing in local and present in HA cluster
**Changes Proposed in PR**: Fix to populate pool mem when svc is missing in local and present in HA cluster
> Fix to populate pool mem when svc is missing in local and present in HA cluster

- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
**Description**:  Fix health monitor names in multiCluster ratio mode
**Changes Proposed in PR**: In multiCluster ratio mode create health monitors with distinct names in case of Virtual Server CR.
> Fix health monitor names in multiCluster ratio mode

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/backend.go
**Description**:  Undefined value specified for the "global:log-level" field in the configuration file
**Changes Proposed in PR**: Setting the log level value to DEBUG when deploy arg loglevel value is AS3DEBUG
**Fixes**: resolves [#1053](https://gitswarm.f5net.com/cc/docs/-/issues/1053)
> #JRA-4147 set loglevel to DEBUG when arg LogLevel with value AS3DEBUG

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingress_test.go
- pkg/controller/node_poll_handler.go
- pkg/controller/node_poll_handler_test.go
- pkg/test/utils.go
- pkg/vxlan/vxlanMgr.go
**Description**:  Fix logic for node not ready check
**Changes Proposed in PR**: Previously we are looking for  "NoExecute" taint added by kubernetes node controller in node not ready check to determine "NotReady" nodes. But this taint could be added in other scenarios in different distributions and is not reliable to check nodeready check. This is changed to look for nodecondition in node status with ready check not true to determine "NotReady" nodes.
> Fix logic for node not ready check

- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/README.md
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfigWithAutoMonitor.yaml
- docs/config_examples/next-gen-routes/deployment/deployment-pod-with-readinessprobe.yaml
- docs/upgradeProcess.md
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/types.go
- pkg/controller/worker_test.go
**Description**:  Add support for readiness based auto monitoring
**Changes Proposed in PR**:  Moved from pod liveness probe based health monitor to readiness probe based health monitor for autoMonitor. Added support for TCP probe with readiness.
**Fixes**: resolves #3089
> Added support for readiness based auto monitoring

- docs/RELEASE-NOTES.rst
- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/extendedConfigmap/global-config-with-primary-cluster-health-probe.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-active-active.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-cluster-admin-state.yaml
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster.yaml
- docs/config_examples/next-gen-routes/README.md
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfig.yaml
- docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfigWithAutoMonitor.yaml
- docs/config_examples/next-gen-routes/migration-guide.md
**Description**:  Removing global and local nomenclature for extended configmap
> Removing global and local nomenclature for extended configmap

- pkg/appmanager/appManager.go
- pkg/controller/constants.go
- pkg/controller/node_poll_handler.go
**Description**:  ocp4.14 annotation k8s.ovn.org/host-addresses is changed to k8s.ovn.org/host-cidrs.
> support new ovn k8s annotation

- cmd/k8s-bigip-ctlr/main.go
- pkg/vlogger/logger.go
**Description**:  Show logs with microseconds in the timestamp. Golang is not supporting milliseconds.
**Changes Proposed in PR**: Customised the console logger with flags
> customise console logger with micrsoseconds in the timestamp

- docs/RELEASE-NOTES.rst
- docs/config_examples/multicluster/README.md
- pkg/controller/multiClusterWorker.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/validate.go
- pkg/controller/validate_test.go
- pkg/controller/worker.go
**Description**:  Improve extendedServiceReferences/multiClusterServices validation
**Changes Proposed in PR**: Restrict specifying services running in CIS HA clusters as extendedServiceReferences/multiClusterServices.
**Fixes**: resolves #3230
> Improve Extended Service validation

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/VirtualServer/virtual-with-hostAliases/README.md
- docs/config_examples/customResource/VirtualServer/virtual-with-hostAliases/tls-with-multiple-hosts.yaml
- docs/config_examples/customResource/VirtualServer/virtual-with-hostAliases/virtual-with-hostAliases.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- pkg/controller/informers.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
- pkg/controller/worker.go
**Description**:  Multi host support for VS CRD
**Changes Proposed in PR**: Added hostAliases field where users can specify multiple host aliases for a Virtual Server CR.
**Fixes**: resolves #3262
> Multi host support for VS CRD

- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
**Description**: Improved log for tls handling in routes
> Improved log for tls handling in routes (#3296)

- pkg/controller/nativeResourceWorker.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**: Fix hostname check for the certificates using canonical name
**Fixes**: resolves #3268
> Fix hostname check for the certificates using canonical name

- cmd/k8s-bigip-ctlr/main.go
**Description**:  Currently ARP is getting enabled for other CNIs like calico etc, which causes controller to hallucinate about readiness and stops it from processing the cccl configuration. ARP should be enabled only for flannel CNI, all other CNI it should be disabled.
**Fixes**: resolves #3299
> Fix enable arp only for flannel CNI

- docs/RELEASE-NOTES.rst
- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-cluster-admin-state.yaml
- pkg/clustermanager/types.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/responseHandler.go
- pkg/controller/routing.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Add support to avoid service pool creation for clusters under maintenance
**Changes Proposed in PR**: Added support for no-pool as a value for adminState for clusters. If specified CIS doesn't add pool members from the affected cluster to the service pool.
**Fixes**: resolves #3284
> Add support to avoid service pool creation for clusters under maintenance

- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
**Description**:  Fix for missing rules for VS with HostAliases and hostGroup
**Changes Proposed in PR**: In case of VS with HostAliases and hostGroup defined the rule names will have hostGroup name as well as the host name for which this rule is meant to. This will ensure that rule name for all the host aliases are unique in case hostGroup is used.
> Fix for missing rules for VS with HostAliases and hostGroup

- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Should throw an error when host group is configured with different vs address, ipamLabel and different host groups with same vs address
**Changes Proposed in PR**: Added extra validations in processAssociatedVirtualServers
> add host group validations for vsAddress and ipamLabel

- docs/RELEASE-NOTES.rst
- pkg/controller/nativeResourceWorker.go
- pkg/controller/worker.go
**Description**:  Fix service pool update issue with A/B NextGenRoute
The strategy used to get the service port number for A/B NextGenRoute is as follows:
Step 1: Try to fetch the port number from the base service in the local cluster
Step 2: If the base service is not found, try to fetch the port number from the base service in the HA peer cluster(in case of multi-cluster active-active)
Step 3: If the base service is not found in HA peer cluster, try to fetch the port number from the alternate backend services in the local cluster
Step 4: If the A/B services are not found in local cluster, try to fetch the port number from the alternate backend services in the HA peer cluster(in case of multi-cluster active-active)
**Fixes**: resolves #3326
> Fix service pool update issue with A/B NextGenRoute

- docs/RELEASE-NOTES.rst
- pkg/appmanager/routing.go
- pkg/controller/routing.go
**Description**:  Fix TLS iRule fails after recent browser updates
**Fixes**: resolves #3402
> Fix TLS iRule fails after recent browser updates

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/TransportServer/ts-with-weight-alternate-backend/README.md
- docs/config_examples/customResource/TransportServer/ts-with-weight-alternate-backend/ts-with-weight-alternate-backend.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/customResource/transportServer/README.md
- docs/config_examples/multicluster/customResource/transportServer/ts-with-weight-extended-service.yaml
- pkg/controller/backend.go
- pkg/controller/controller.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/resource/types.go
**Description**:  Support weight, alternate backend and ratio for transport server
**Changes Proposed in PR**: Support weight, alternate backend and ratio for transport server
> Support weight,alternate backend and ratio for transport server

- cmd/k8s-bigip-ctlr/main.go
**Description**:  k8s default partition is getting created when filter tenants and disable partition are true
**Changes Proposed in PR**: Added disable partition check when cleaning up default partition k8s
**Fixes**: resolves #3279
> #3279 add disable partition check for cleanup

- build-tools/Dockerfile.ubi
**Description**:  Upgrade python version to 3.9.19
**Changes Proposed in PR**: Upgrade python version to 3.9.19
> Upgrade python version to 3.9.19

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Fix CIS removing config on VS deletion from different namespace
**Changes Proposed in PR**: Fix CIS removing config on VS deletion from different namespace
**Fixes**: resolves #3395
> Fix CIS removing config on VS deletion from different namespace

- docs/RELEASE-NOTES.rst
- pkg/controller/backend.go
- pkg/controller/backend_test.go
**Description**: After deleting all IngressLink CRs from the cluster, CIS would push bare AS3 declaration with no defaultRouteDomain parameter, resetting the Partition default RD to 0 and breaking subsequent Static Route push.
**Changes Proposed in PR**: set defaultRouteDomain on tenant delete.
**Fixes**: resolves #3406
> #3406 fix defaultroutedomain on resources delete

- docs/RELEASE-NOTES.rst
- pkg/controller/routing.go
**Description**:  For http2 protocol we receive the sslpath as '*', hence replacing it with root path, however it will not handle the http2 path based routing for now. Only HTTP/2 full proxy mode is supported.
**Fixes**: resolves #3401
> Fix for invalid iRule generation for HTTP/2 full proxy mode

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**: fix adding pool members from external clusters in nodeportlocal mc mode
**Changes Proposed in PR**: fix adding pool members from external clusters in nodeportlocal mc mode
**Fixes**: resolves #3396
> fix adding pool members from external clusters in nodeportlocal mc mode

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/README.md
- docs/config_examples/customResource/Policy/policy-with-ftp-profile.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker_test.go
**Description**:  Add support for FTP profile in policy CR
**Changes Proposed in PR**: Added support for FTP Profile in Transport server 
**Fixes**: resolves #3438
> #3438 support FTP Profile for transport server

- docs/RELEASE-NOTES.rst
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Fix empty pool issue when VS/TS created before service
**Changes Proposed in PR**: Fix empty pool issue when VS/TS created before service
> Fix empty pool issue when VS/TS created before service

- Makefile
- build-tools/rel-build.sh
…4851)
**Description**:  Added debugging flags to Go build process with -gcflags="all=-N -l (#4851)
**Fixes**: resolves #4851
> Added debugging flags to Go build process 2.x-master

- docs/RELEASE-NOTES.rst
- pkg/controller/informers.go
**Description**:  CIS not removing pool members of GTM when host annotation removed on Transport server, Ingress link and service type LB
**Changes Proposed in PR**: Added host param to the enqueueupdate functions for delete event
> update edns pool members as per the hosts of the resource

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**: Change of weight from primary to alternate backend is not graceful for transport server
**Changes Proposed in PR**: Will set admin state to disable when pool weight is 0 for transport server
**Fixes**: resolves #3542
> #3542 set adminstate to disable when pool weight is 0 for transport server

- docs/RELEASE-NOTES.rst
- f5-bigip-ctlr-operator/Dockerfile
- helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
**Description**:  fix to disable default uid in F5 BIG-IP Controller Operator
**Changes Proposed in PR**: fix to disable default uid in F5 BIG-IP Controller Operator
> fix to disable default uid in F5 BIG-IP Controller Operator

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/TransportServer/ts-with-weight-alternate-backend/README.md
- docs/config_examples/customResource/TransportServer/ts-with-weight-alternate-backend/ts-with-weight-alternate-backend.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- docs/config_examples/multicluster/README.md
- docs/config_examples/multicluster/customResource/transportServer/README.md
- docs/config_examples/multicluster/customResource/transportServer/ts-with-extended-service-ha-svcs.yaml
- docs/config_examples/multicluster/customResource/transportServer/ts-with-external-services.yaml
- docs/config_examples/multicluster/customResource/transportServer/ts-with-weight-extended-service.yaml
- docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services-and-ab.yaml
- docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services.yaml
- pkg/controller/multiClusterWorker.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/validate.go
- pkg/controller/validate_test.go
- pkg/controller/worker.go
**Description**:  Rename extendedServiceReferences as multiClusterServices
**Changes Proposed in PR**: Rename extendedServiceReferences as multiClusterServices
> Rename extendedServiceReferences as multiClusterServices

- azure-pipelines.yaml
- build-tools/Dockerfile.debian
- build-tools/Dockerfile.debug
- build-tools/Dockerfile.ubi
- build-tools/rel-build.sh
- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/serviceTypeLB/README.md
- docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/policy-with-pool-settings.yaml
- docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/service-type-lb-with-poolsettings-in-policycr.yaml
- docs/config_examples/customResource/serviceTypeLB/service-type-lb-with-custom-partition.yaml
- docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
- go.mod
- pkg/controller/backend.go
- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/multiClusterInformers.go
- pkg/controller/postManager.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/validate.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**:  Enhancements for CRDs and Svc type LB
> Enhancements for CRDs and Svc type LB

- pkg/controller/worker.go
> Fix for pool members not updating when service port and target ports are different

- pkg/controller/resourceConfig.go
- pkg/controller/worker.go
**Description**:  Poolname and monitor name not updated when service port is updated with servicetypeLB and transport server
**Changes Proposed in PR**: Handled the service port and target port modifications
**Fixes**: resolves #1172
> Poolname and monitor name not updated when service port is updated with servicetypeLB and transport server

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**:  handle kubeclient updates when kubeconfig secret is updated for external clusters.
1. handled kubeclient updates when kubeconfig secret is updated for external clusters.
2. For primary clusters(i.e local cluster) where cis is running, kubeconfig is read from inClusterConfig provided by Kubernetes. Secret update will have no impact on local cluster
**Fixes**: resolves #3727
> handle kubeconfig update 

- docs/RELEASE-NOTES.rst
- pkg/controller/apiHandler.go
- pkg/controller/as3Handler.go
- pkg/controller/backend.go
- pkg/controller/controller.go
- pkg/controller/gtmBackend.go
- pkg/controller/postManager.go
- pkg/controller/postManager_test.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
**Description**:  support for exponential timeout when bigip is busy
**Changes Proposed in PR**: As part of this PR, We are embedding the timeouts in the agentPostConfig itself and timeout is increased for each config request when BigIP is busy upto max timeout of 240 sec.
**Fixes**: resolves #3766
> feat: support for exponential timeout when bigip is busy

- pkg/controller/as3Handler.go
- pkg/controller/as3Handler_test.go
- pkg/controller/backend.go
- pkg/controller/gtmBackend.go
- pkg/controller/postManager.go
- pkg/controller/types.go
**Description**:  There was a corner case where Agent is reading the cached tenants before it's update with the current BIGIP config, Hence some time it was reporting that there is no changes made to the config.
> fix: tenant cache to avoid the concurrent read write

- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/worker.go
**Description**:  replace svc name with vsAddress in monitor name
> fix: replace svc name with vsAddress in monitor name

- pkg/controller/responseHandler.go
**Description**:  Fix for LB type service status update
**Changes Proposed in PR**: Following code fix is done for LB type service status update
* If LB service is present as pool for VS/TS then while updating the status of LB service avoid taking the Virutal Address directly from VS/TS status for updating the LB type service status.
> fix: LB type service status update

- docs/RELEASE-NOTES.rst
- docs/config_examples/Install/k8s/sample-k8s-bigip-ctlr.yaml
- docs/config_examples/Install/openshift/f5-k8s-bigip-ctlr-openshift.yaml
- docs/config_examples/Install/openshift/quick-start-guides/HA/next-gen-route/cis/f5-bigip-ctlr-01-deployment.yaml
- docs/config_examples/Install/openshift/quick-start-guides/HA/next-gen-route/cis/f5-bigip-ctlr-02-deployment.yaml
- docs/config_examples/Install/openshift/quick-start-guides/StandAlone/f5-k8s-bigip-ctlr-openshift.yaml
- helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
**Description**:  Improve logging when BIG-IP is not reachable during pod initialization
**Changes Proposed in PR**: Increased the period seconds to 120 secs
**Fixes**: resolves #3895
> increase the period seconds to 120 for the Helm values
