F5Networks/k8s-bigip-ctlr

- README.md
Problem:
README did not have coverage and build badges.
Solution:
Updated README.md.
> add build and coverage badges

- python/bigipconfigdriver.py
- python/tests/test_bigipconfigdriver.py
Two commits to fix two issues with the controller:
1) Fix exception handling in _do_reset to fix incorrect back off timer reseting.
2) Fix back off timer from an event to a Timer so it does not block _do_reset looping.
> Fix backoff timer

- docs/conf.py
Problem:
The version and path info need to be updated
Solution:
Changed the version info to point to 1.1.0 and product docs
path to 1.1
> Update version and path info for v1.1.0

- docs/RELEASE-NOTES.rst
@amudukutore @michaeldayreads 
#251 - Correction to Release Notes
"+* Configure multiple SSL Profiles for a BIG-IP Virtual Servers."
"Virtual Servers" should be "Virtual Server".
> Fixes #251

- pkg/appmanager/appManager.go
Problem:
The syncVirtualServer() function is too large.
Solution:
I refactored the ConfigMap specific code into syncConfigMap() and the
Ingress specific code into syncIngresses(). The overall functionality
has not changed.
> Refactor syncVirtualServer into smaller functions

- docs/README.rst
- docs/_static/config_examples/ingress-with-health-monitors.yaml
- docs/_static/config_examples/name-based-ingress.yaml
- docs/_static/config_examples/simple-ingress-fanout.yaml
- docs/_static/config_examples/single-service-ingress.yaml
- docs/_static/config_examples/single-service-tls-ingress.yaml
Problem:
The product docs should document the addition of Ingress resource
support.
Solution:
Added the appropriate documentation, including example files.
Fixes #272
affects-branches: master, 1.1-stable
> Ingress resource annotations and behavior not documented

- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/kubernetes_one_iapp_expected.json
Transferred ownership to CCCL for how an iApp description is
formatted; the Container Connectors should not be responsible for
this. Updated unit-test expectations.
> Moved iApp data formatting to CCCL

- Jenkinsfile
Added a few options to the Jenkinsfile, including job timeout. This is based
on our systest Jenkinsfile.
> Add options to Jenkinsfile

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingressHealthMonitors.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/types.go
- python/bigipconfigdriver.py
- python/tests/kubernetes_invalid_svcs.json
- python/tests/kubernetes_invalid_svcs_expected.json
- python/tests/kubernetes_no_apps.json
- python/tests/kubernetes_no_apps_expected.json
- python/tests/kubernetes_one_iapp.json
- python/tests/kubernetes_one_iapp_expected.json
- python/tests/kubernetes_one_svc_four_nodes.json
- python/tests/kubernetes_one_svc_four_nodes_expected.json
- python/tests/kubernetes_one_svc_one_node.json
- python/tests/kubernetes_one_svc_one_node_expected.json
- python/tests/kubernetes_one_svc_two_nodes.json
- python/tests/kubernetes_one_svc_two_nodes_expected.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only.json
- python/tests/kubernetes_one_svc_two_nodes_pool_only_expected.json
- python/tests/test_bigipconfigdriver.py
- python/tests/test_k8scloudbigip.py
Moved all of the LTM config creation to the golang frontend, therefore
the python backend is just a pass-through to CCCL. Updated unit tests
too.
> CCCL Integration

- CONTRIBUTING.md
Problem: The Pull Requests section was missing some info about when container is pushed to dockerhub.
Solution: Make it clear that container is pushed only after pull request is accepted.
> Fix error in Pull Requests section of CONTRIBUTING.md

- docs/conf.py
Problem:
The version and path info need to be updated
Solution:
Updated all version and tags to point to 1.1.1
affects-branches: 1.1-stable
> Update version and path info

- docs/RELEASE-NOTES.rst
Problem:
Release notes were missing some bugfix information.
Solution:
Updated release notes to include bugfix information.
affects-branches: master, 1.1-stable
> Update release note with bugfixes

- docs/RELEASE-NOTES.rst
Add release notes for the upcoming 1.2 release of the controller.
Removed empty fields from previous release notes.
> Release notes for 1.2

- .travis.yml
- docs/conf.py
Problem:
Version information needs to be updated so that we have proper
version information in releast notes, and also publish the docs
to the proper location.
Solution:
Updated the version information to v1.2.
> Update version info

- pkg/appmanager/appManager_test.go
Add additional unit testing for recent Route bugs. These tests include:
-Updating a Route object to verify we aren't updating our internal store too early
(verifying we aren't using pointers)
-Creating Routes with the same name and Services with the same name in different namespaces
to verify we can handle configurations in these cases.
Fixes #343
> Further unit testing for Route bugs

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update CCCL version to incorporate the fix for CCCL Issue #152
(Rules are not visible through the BIG-IP GUI)
> Update CCCL for policy-rule bug fix

- pkg/appmanager/appManager_test.go
Problem: The DNS resolver unit tests checked for specific IP addresses, but this
is not reliable, as addresses change.
Solution: Generalize the tests to expect that an IP address exists, but don't check
the actual value, as it will change. System tests will be a better way to check
IP address value.
> Fix DNS unit tests to be more reliable

- Jenkinsfile
> Fix typo in 728ced2

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Pickup CCCL fix for invalid policy mode.
> Update CCCL SHA

- docs/README.rst
Cherry-picked from 6c3c313e9fbbc24ba737bfe9f40298beab94e22c
Merge pull request #374 from sjberman/docs_fixes
> Merge docs bugfix to release branch

- docs/RELEASE-NOTES.rst
Add release notes for the 1.3 release, including the added functionality, bugs that were fixed,
and any new limitations that were introduced.
> Release notes for 1.3

- build-tools/make-docs.sh
- docs/RELEASE-NOTES.rst
Miscellaneous commits to ensure docs are correctly built and all docs checks pass when running travis builds.
> Docs checks

- .github/ISSUE_TEMPLATE.md
- SUPPORT.md
Problem:
The repo is missing an issue template and customer support information.
Solution:
Add SUPPORT.md and ISSUE_TEMPLATE.md.
> Add issue template and customer support information.

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update CCCL to pickup the fix for this issue.
> CCCL Issue 184: Conflict with iApp policies

- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/kubernetes_one_udp_svc_two_nodes.json
- python/tests/kubernetes_one_udp_svc_two_nodes_expected.json
- python/tests/test_k8scloudbigip.py
- schemas/bigip-virtual-server_v0.1.5.json
Added UDP support via ConfigMaps and updated to CCCL version that
supports UDP Health Monitors.
> Add UDP support

- docs/README.rst
Problem:
Link to IPAM doc is broken
Solution:
Use the correct link
Fixes #431
affects-branches: master, 1.3-stable
> Fix broken link to IPAM doc

- python/bigipconfigdriver.py
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
- python/tests/test_k8scloudbigip.py
Set the iControl REST user-agent when instantiating CCCL.
> Moved user-agent config into the CCCL API

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update the CCCL version to incorprate the fix for the 'irule whitespace'
issue (https://github.com/f5devcentral/f5-cccl/issues/183)
> Update CCCL version for fix to irule-whitespace issue

- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update for resolution of CCCL Issue-198 (incorrect Virtual Server
comparison)
> Update for CCCL Virtual Server fix

- docs/RELEASE-NOTES.rst
Problem:
Release note formatting did not add route domain bullet list
Solution:
Updated formatting to show bullet lists
> Update formatting for Release notes

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/resourceConfig_test.go
- pkg/appmanager/routing.go
Adding A/B support for TLS-based deployments (passthrough is working; reencrypt is partially working).
> Add A/B For TLS-based routes (plus several bug fixes)

- docs/RELEASE-NOTES.rst
Problem: It is unclear how the controller will behave if it cannot
initially communicate with the BIG-IP.
Solution: Updated the documentation to indicate the behavior (a
limitation for now).
Fixes:  #438
> Updated release notes with startup behavior of the controller.

- docs/RELEASE-NOTES.rst
Problem:
Issue 471 was fixed but not mentioned in the release notes.
Solution:
Added issue 471 to the release notes for v1.4.1
affects-branches: master, 1.4-stable
> Added issue 471 to release notes

- docs/RELEASE-NOTES.rst
- python/k8s-build-requirements.txt
- python/k8s-runtime-requirements.txt
Update CCCL to get fix for BIG-IP Health Monitor compatibility
> Update for CCCL Issue #208

- python/bigipconfigdriver.py
Problem:
The retry callback cbs were logging success the first time that they
succeeded. This is incorrect since the first time the cb is called a
retry has not been made so the code executed without error so there is
not a need to log a successful outcome.
Solution:
Add a success logging flag that will only log success if the cb has
been called more than once in the backoff loop (which means that the
cb had failed at least once necessitating the success logging).
> Added log success flag.

- build-tools/Dockerfile.alpine.builder
- build-tools/Dockerfile.alpine.runtime
> Alpine 3.4 will soon be unsupported, uplift to latest version: 3.7

- requirements.txt
Problem:
Controller agent has been updated so the pointer to it is now pointing
to stale version.
Solution:
Upate agent pointer to point to latest.
> Update agent pointer.

- docs/RELEASE-NOTES.rst
Problem:
Release notes need to be updated to reflect added source address
translation configuration functionality.
Solution:
Add release notes to document this.
> Updated release notes.

- docs/_static/config_examples/ingress-with-health-monitors.yaml
- docs/_static/config_examples/sample-passthrough-route.yaml
- docs/_static/config_examples/source-addr-translation-ingress.yaml
- docs/_static/config_examples/source-addr-translation-route.yaml
- docs/_static/config_examples/source-addr-translation.configmap.yaml
Problem:
Current SNAT examples were interleaved with other examples which could
cause confusion to users.
Solution:
Create separate SNAT example files to avoid the confusion.
Fixes: #619
> Fixed SNAT examples.

- pkg/appmanager/profiles.go
Problem: When cleaning up profiles that no longer exist in a resource, we maintain a whitelist of profiles that don't come from any resource, so we know not to accidentally delete them. The client and server ssl profiles for Routes that are provided via CLI were not considered in this list.
Solution: Whitelist these two profiles to prevent them from being unnecessarily deleted. Also fixed an issue with the configuration of the server ssl profile name.
Fixes #636
> Whitelist Route default SSL profiles

- docs/RELEASE-NOTES.rst
Adding release notes for bug fixes in 1.5.
> Release notes for bug fixes

- docs/README.rst
- docs/RELEASE-NOTES.rst
- docs/conf.py
- Added installation section to README.md that links to k8s, openshift and helm options for installation.
- Added helm charts for controller and ingress resources to release notes.
> Helm docs and release notes

- docs/README.rst
- Fixes issue #539 
- light edits to further clarify/fix grammar for items in the general config parameters table
@alonsocamaro
> Fixes #539 

- docs/README.rst
merge pull request #642 from jputrino/doc_bugs
Fixes #539
(cherry picked from commit 650323c7b9b45a5d88c1ea0205e59dfa92b64bcf)
> Cherry-pick merge commit from master

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
Adds checks to the `--bigip-partition` parameter to disallow the common partition
> Fixes: #486

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- docs/README.rst
- docs/RELEASE-NOTES.rst
- pkg/appmanager/profiles.go
Cherry picking two bug fixes into 1.6-stable.
> Cherrypick 733, 747

- docs/RELEASE-NOTES.rst
- pkg/appmanager/routing.go
Cherry pick bug fixes to 1.7 stable
> V1.7.1 Bug fix release

- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
- build-tools/attributions-generator.sh
- docs/conf.py
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles_test.go
- requirements.txt
Updated conf.py to make compatible with Sphinx version 1.8.3
Added f5-cccl external dependency to requirements.txt
Change as per go fmt
Change Docker Repo for attrib generator
> Fix Builds due to process-dependency-links removal

- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
> Fix #718 - Namespaces that start with a number cause errors

- docs/RELEASE-NOTES.rst
Add release notes for 1.8.1 release
> Add 1.8.1 Release Notes

- .approvals.json
- .f5license
- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
- docs/README.rst
- docs/conf.py
- pkg/appmanager/appManager_test.go
- pkg/appmanager/profiles_test.go
- requirements.txt
Can we update 1.7-stable using cherry-pick and a manual modification to conf.py?
89bd21b7f is cherry-pick of PR #840 
2b5a6d2ab is manual update
Thanks!
> 1.7 Update Request

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/validateResources.go
1. appManager and ValidateResources are updated with logic to branchout for AS3 specific implementation.
2. Added a unit testcase to validate the change.
> Branch out the CC implementation for AS3 Specific implementation.

- pkg/appmanager/as3Manager.go
Add skeleton for developing user stories.
> Add AS3 Manager Design

- pkg/appmanager/as3Manager.go
This parser takes an AS3 template as input and return a map that has the parsed information related to Tenants, Applications ans Services.
Know Issues:
1. AS3 config is not being validated with respect to AS3 Schema.
> Add AS3 template Parser

- pkg/appmanager/as3Manager.go
This code builds the AS3 Declaration with pool members.
1.  I have created a new file with name buildAS3Declaration.go
2. There are no changes(Addition and Deletion) to the existing code
3. Unit tests will be added 
Known Issues:
1. I need to handle the scenario where user provide absolute reference path of the pool instead of pool name itself.
> Initial commit for source code to build as3 Declaration

- pkg/appmanager/as3Manager.go
Service discovery is loosely coupled with Kubernetes Service labels. A Kubernetes Service is treated as a match for an AS3 service, if the Kubernetes Service have the following labels and their values matches corresponding AS3 Object.
```
cis.f5.com/as3-tenant=<Tenant Name>
cis.f5.com/as3-app=<Application Name>
cis.f5.com/as3-service=<AS3 Service Name>
```
When a match is found, returns Node's Address and Service NodePort as pool members, if Controller is running in NodePort mode, else by default ClusterIP Address and Port are returned.
> Perform Service Discovery for AS3 Service

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
This code will POST AS3 declaration to Big-IP.
1. Implemented function postAS3Declaration to POST AS3 declaration to Big IP.
2. Created new generic function restCallToBigIP to handle all REST calls.
3. Created new file as3Manager_test.go to write unit test cases.
> POST as3 declaration to BigIP

- .approvals.json
- .f5license
- Godeps/Godeps.json
- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.rhel7.runtime
- build-tools/build-release-images.sh
- pkg/appmanager/as3Manager.go
- pkg/appmanager/schema.go
- schemas/as3-schema-3.9.0-3-cis.json
- vendor/github.com/xeipuuv/gojsonschema/.gitignore
- vendor/github.com/xeipuuv/gojsonschema/.travis.yml
- vendor/github.com/xeipuuv/gojsonschema/README.md
- vendor/github.com/xeipuuv/gojsonschema/draft.go
- vendor/github.com/xeipuuv/gojsonschema/errors.go
- vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
- vendor/github.com/xeipuuv/gojsonschema/glide.yaml
- vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
- vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
- vendor/github.com/xeipuuv/gojsonschema/locales.go
- vendor/github.com/xeipuuv/gojsonschema/result.go
- vendor/github.com/xeipuuv/gojsonschema/schema.go
- vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
- vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
- vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
- vendor/github.com/xeipuuv/gojsonschema/schemaType.go
- vendor/github.com/xeipuuv/gojsonschema/subSchema.go
- vendor/github.com/xeipuuv/gojsonschema/utils.go
- vendor/github.com/xeipuuv/gojsonschema/validation.go
This commit validates  as3 template using as3 schema
Known Issues: NA
Overall Changes:
1. Updated the gojsonschema to latest version.
2. Made below changes to AS3 schema.
1. Changed the minLimit of serverAddress from 1 to 0.
2. Changed the maximum repeat count from 65520 and 8192 to 1000.
3. Changed the URN reference of "$id" to URL.
3. Updated the build files to push as3 schema to container along with existing schemas. 
4. Introduced a new function to as3Manager.go(validateAS3) to validate schema.
Unit Tests: Passed
Regression: Passed
Controller Image created with these changes -> abhishekf5/k8s-bigip-ctlr:as3schemavalidation-1000
> This commit validates as3 template using as3 schema

- .approvals.json
Problem: 
Pending approval for gojsonschema package from the License Review Board
Solution:
Received the approval
feature.user-defined-as3
> Updating the license approval for gojsonschema

- docs/RELEASE-NOTES.rst
Update the Limitations for AS3. Hopefully this will be slightly more specific regarding:
- Pool declaration (and the members in the pool).
- ConfigMap instances (running state vs type of file).
> Update Limitations section

- docs/README.rst
- docs/RELEASE-NOTES.rst
- docs/conf.py
Add CIS updates to README and RELEASE-NOTES
> Update README and RN for CIS

- docs/RELEASE-NOTES.rst
In Added Functionality - Break single into two separate lines.
Move Bug Fixes up.
> update format error

- cmd/k8s-bigip-ctlr/main.go
Description changes for trusted-certs-cfgmap option
> Description changes for trusted-certs-cfgmap option

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Add custom event handlers for ConfigMap, Service, Endpoints events
> Add informers for Service and Endpoint Create/Update/Delete events

- docs/RELEASE-NOTES.rst
Added release notes content for 1.9.1
> Add Release notes for 1.9.1

- pkg/appmanager/as3Manager.go
- pkg/appmanager/types.go
Problem: CIS does not support openshift basic host route using AS3 declaration. 
Solution: Basic host fronted implementation of openshift route using AS3 declaration
affects-branches: feature.as3
> Host route implementation

- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Types.go
New feature: Health monitor routes implemented
Monitor type supported: HTTP and HTTPS
affects-branch: feature.as3
> Health monitor route implementation and refactoring

- docs/README.rst
- docs/openshift/example-openshift-custom-ssl-profile.yaml
- docs/openshift/example-openshift-default-ssl-profile.yaml
For some reason none of the _static content is making it to AWS. I've created a new openshift dir to test fixing this.
> Correct SSL profiles 

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
We are updating the VSQueueLen with list of services within the namespaces we are watching. This fixes the issue #810
> Calculate the vsQueueLen based on the Cluster state.

- pkg/appmanager/appManager.go
This reverts commit 5c5c9eed291c6d89e42875943d7fe8833fc3036c, reversing
changes made to 92ff56757929cd74c262a1e89f799046283f0551.
> Revert "Merge pull request #963 from veeramalla-f5/ignoremasternode"

- docs/RELEASE-NOTES.rst
Update 1.9.2 section and add next-release
> Update Release Notes

- .gitlab-ci.yml
- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.rhel7.builder
- build-tools/build-devel-image.sh
- build-tools/build-release-artifacts.sh
- build-tools/build-release-images.sh
- build-tools/entrypoint.builder.sh
- build-tools/make-docs.sh
- build-tools/rel-build.sh
- build-tools/run-in-docker.sh
- build-tools/version-tool
This CI only includes make prod changes, make verify and make docs are not run by this CI.
> Integrated git lab ci

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager_test.go
- pkg/appmanager/routing.go
Problem:
CIS does not support Path based routing for Reencrypt routes.
Solution:
Support Path based Routing for Reencrypt routes.
master
> Support Path based Routing for Reencrypt routes

- pkg/appmanager/as3Manager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
CIS support for AB deployment through open-shift routes implemented.
Based on weight.
affected branches: master
> Alternate backend supports for openshift routes

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: Deletion of AS3 configmap does not delete its corresponding configuration in unified as3 declaration(still remains stale configuration)
Solution: New delete config map event handler implemented to clear the stale configuration.
master
> Fix AS3 Configmap cleanup

- pkg/appmanager/as3Manager.go
Problem:
The BIG-IP response is not being captured properly. It results in inappropriate logs.
Solution:
Logging BIP-IP AS3 error response body for better readability and appropriate logs.
master
> Response body formate refactored

- pkg/appmanager/as3Manager.go
Problem: CIS logging sensitive data received from BIG-IP response
Solution: Disable logging data temporarily
affects-branches: master, 1.11-stable
docker-image: snatra27/k8s-bigip-ctlr:1.11.1_build_5
> Disable logging AS3 response Body from BIG-IP.

- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/validateResources.go
Problem: Improper as3 logging
Solution: Standardizing as3 logging
Affected-branches: 1.12 feature
Image: nitin24/standardizeas3logs:1.0
> standardizing as3 logs

- pkg/appmanager/appManager.go
Prometheus config map parse error bug fix
Issue resolved for the Prometheus metric status="parse-error" was showing wrong.
CONTCNTR-864
> Prometheus config map parse error log bug fix

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/as3Manager.go
Problem: CIS continuously logs this message "[INFO] Wrote 0 Virtual Server and 0 IApp configs"
Solution: Properly handled the AS3 members in CIS
docker-image: snatra27/k8s-bigip-ctlr:rel12_build_5
> In CCCL mode with AS3 CfgMap, CIS continuously logs "[INFO] Wrote 0 Virtual Server and 0 IApp configs"

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Types.go
- pkg/appmanager/resourceConfig.go
Problem: CIS uses CCCL to process Ingress resources.
Solution: CIS to use AS3 to process Ingress resource.
Branches-effected: master
> Support Ingress resource with AS3

- pkg/appmanager/as3Manager.go
Requirement: secure-serverssl is applied across ssl profile in AS3, so even if one route has secure-serverssl enabled, all the hosts that share same ssl profile will be validated with corresponding certificates.
Problem: With previous implementation setting of secure-serverssl depends on the order of processing the routes
Solution: Even if one route has secure-serverssl, all the certificates of hosts that share the same ssl profile will be validated
> Update secure-serverssl behaviour

- docs/RELEASE-NOTES.rst
Updated CIS v1.12 Release Notes
> CIS v1.12 Release Notes

- pkg/appmanager/as3Manager.go
Deleted CIS managed old partition bug fix when agent altered.
Docker image: amit49g/k8s-bigip-ctlr:rel12_build_14
> Deleted CIS managed old partition bug fix

- docs/RELEASE-NOTES.rst
Update Release notes for branch 1.12-stable
> Update Release notes for branch 1.12-stable

- docs/RELEASE-NOTES.rst
- pkg/appmanager/as3Manager.go
Problem: Data group was inconsistent when routes are created in multiple namespaces.
Solution: Fixed the issue while generating AS3 declaration for DG.
Image: amit49g/k8s-bigip-ctlr:dgFix
> Data group inconsistency issue fix

- .gitlab-ci.yml
Added the changes for running the test jobs only with schedules and allowed the failures in job
> Adding support for only nightly build

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Manager_test.go
- pkg/appmanager/as3Types.go
- pkg/appmanager/as3Utils.go
- pkg/appmanager/outputConfig.go
- pkg/appmanager/validateResources.go
- pkg/postmanager/postManager.go
Add responce handler to handle BIG-IP responce with code 503
Problem: Errors are being handled in different code paths through flags and input configuration such as userDefinedAS3 and routeConfig are being maintained different places.
Solution: Write a new package to take responsibility of posting declaration to BIG-IP and to handle all sorts of errors. Encapsulate all the input configuration and operations to be done to one new structure. 
> Refactor Code that posts AS3 Config to BIG-IP

- .gitlab-ci.yml
Fixed the exclude tag in pipeline
> Fixed the exclude tag in pipeline

- pkg/appmanager/routing.go
Problem:
CIS does not handle child paths for http to https redirect.
Example: Create a route for host foo.com and path /foo. CIS can handle the traffic for http://foo.com/foo but not for foo.com/foo/bar
Solution: 
Enhance the httpsredirectIrule to handle such cases.
master
> Enhance httpsredirect Irule to support childpaths

- pkg/postmanager/postManager.go
> Update Error logs for Response from BIG-IP

- pkg/appmanager/as3Manager.go
> Add AS3 validation for unified declaration

- pkg/appmanager/as3Manager.go
Problem: Vulnerability explained in article: https://support.f5.com/csp/article/K91382300
Solution: Adding additional action as specified in the article.
> Fix ASM vulnerability

- operator/README.md
- operator/build/Dockerfile
- operator/helm-charts/f5-bigip-ctlr/values.yaml
- operator/manifest/f5-bigip-ctlr-operator.v1.0.0.clusterserviceversion.yaml
Updating the docs and Image for Operator Changes.
> Updated Operator image and docs.

- pkg/appmanager/profiles.go
Problem: CIS in AS3 mode not picking up the default client-ssl profile provided through --default-client-ssl argument.
Solution: Add provided default client-ssl to RouteProfiles so that it will be picked up by AS3 formatting code later.
> Fix default-client-ssl argument

- pkg/appmanager/as3Manager.go
- pkg/appmanager/as3Utils.go
Fix virtual-server.f5.com/http-port ingress annotation issue with agent AS3.
affected-branch: master
Signed-off-by: Amit Gupta amit0658@gmail.com
> Fix virtual-server.f5.com/http-port ingress annotation issue with agent AS3

- build-tools/Dockerfile.debian.builder
- build-tools/Dockerfile.debian.runtime
- build-tools/Dockerfile.debug.runtime
- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
- build-tools/entrypoint.builder.sh
- docs/conf.py
- requirements.txt
Problem:
Controller using python version 2.7
Solution:
Upgrade the python version to 3.6
master
> changed the python version from 2.7 to 3.6

- docs/RELEASE-NOTES.rst
> CIS 1.14.0 ReleaseNotes

- build-tools/Dockerfile.rhel7.builder
- build-tools/Dockerfile.rhel7.runtime
- build-tools/entrypoint.builder.sh
Problem: Python 2 to 3 dependency for RHEL image
Solution: Removing the unnecessary python dependencies and providing fork for RHEL and Debian image creation(python support)
> rhel-atomic image fix

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/crManager.go
- pkg/crmanager/types.go
> Add Custom Resource Manager

- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/types.go
Prepare AS3 declaration from Resource Config.
> Prepare AS3 declaration from Resource Config

- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Add WorkQueue and Worker

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/basic/customresourcedefinition.yml
- docs/_static/config_examples/crd/basic/example-single-pool-virtual.yml
- docs/_static/config_examples/crd/basic/example-two-pool-two-virtual.yaml
- pkg/appmanager/validateResources.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
Handle VirtualServer Custom resource, check if it is created with valid configuration and populate the resource config with it. This Pull request does not handle the summing of all the individual resource config to consolidated resource configs.
> Handle VS Custom Resources and Populate ResourceConfig

- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/types.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
Add Event handlers for Service and Endpoints
> Add infomers for Service and Endpoints

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/postManager.go
- pkg/crmanager/pythonDriver.go
- pkg/crmanager/types.go
Add PythonDriver to run CCCL driver agent
> Add ConfigWriter to write ARP, FDB configuration

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Features:
1. Update PoolMembers for the pool of individual VirtualServer processed in the ResourceConfig.
2. Update ResourceConfigs with all the ResourceConfig(all virtualservers) also ResourceConfigMap.
3. Fix agent AS3 initialisation.
Note: PoolMembers will be populated with fake endpoints as we haven't implemented node polling till this point.
> Update PoolMembers for ResourceConfig

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/node_poll_handler.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Add VXLAN Manager

- pkg/crmanager/backend.go
- pkg/crmanager/pythonDriver.go
> Add Health Checker for Python Driver

- pkg/crmanager/worker.go
Problem:
CRD: Fix: Multiple PoolMembers are not populated
Solution:
Indexer(for looping) not in place,  Remove the return type as it is not used.
> CRD: Fix: Multiple PoolMembers are not populated

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
> Remove CR Manager dependency on agent parameter

- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
> Fix multiple namespaces informer issue

- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/node_poll_handler.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Add Control Logic to Push Config to BIG-IP

- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
- pkg/agent/as3/as3Utils_test.go
- pkg/agent/as3/as3manager_suite_test.go
- pkg/appmanager/appManager_test.go
- pkg/resource/resourcecfg_suite_test.go
Problem: Improve code coverage for CIS 2.0 configMap implementation 
Solution: Implemented Unit test cases for User-defined and Override AS3 config maps
> CIS 2.0 CfgMap Unit test cases

- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
> Update control logic for configuration push

- pkg/crmanager/worker.go
CRD Bug fix: Fix for CIS crashes when service does not exist.
> Service not found bug fix

- pkg/crmanager/routing.go
Problem: best-match algorithm in BIG-IP looks at all the Rules in a Policy to figure out best rule that matches the traffic. This can be improved.
Solution: Controller adopts the strategy to find best-match rule and sorts it to the first place, and so on. So that the first-match acts as best-match as rules are already sorted with best-match strategy. 
> Add Rule Sorting Algorithm

- pkg/crmanager/crManager.go
- pkg/crmanager/worker.go
Updated Worker and CRManager files with description and comments. This will help someone new to understand the application flow.
> Add Comments/Description for the newly created functions

- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
Bug fix for delete rule from policy, when rule is no longer used by this virtual server.
> Bug fix for delete rule from policy

- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
> Fix name format of pool

- pkg/crmanager/resourceConfig.go
> Fix remove pool config if pool is removed in VS spec

- pkg/crmanager/worker.go
> Code Cleanup for CRD feature

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Resource.go
- pkg/agent/as3/as3Types.go
- pkg/agent/as3/as3Utils.go
Problem: AS3 Controls userAgent data is not updated and properly formatted.
Solution: Format AS3 Controls userAgent data based on K8S/OCP and CIS versions.
Branch affected: master
> Update AS3 Controls userAgent data

- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Resource.go
- pkg/agent/as3/as3Utils.go
- pkg/agent/cccl/ccclManager.go
- pkg/appmanager/appManager.go
Problem: Agent 2.0 should not have unused imports, comments, etc. 
Solution: Code cleanup performed for Agent 2.0, removed unused imports, comments, and maintained consistency in variable usage.
Note: Only cosmetic code changes made as part of this PR
> 2.0 Agent code cleanup

- docs/_static/config_examples/openshift/HA/f5-k8s-bigip-ctlr-openshift-ose-bigip-01.yaml
- docs/_static/config_examples/openshift/HA/f5-k8s-bigip-ctlr-openshift-ose-bigip-02.yaml
- docs/_static/config_examples/openshift/HA/f5-kctlr-openshift-clusterrole.yaml
- docs/_static/config_examples/openshift/HA/f5-kctlr-openshift-hostsubnet-float.yaml
- docs/_static/config_examples/openshift/HA/f5-kctlr-openshift-hostsubnet-ose-bigip-01.yaml
- docs/_static/config_examples/openshift/HA/f5-kctlr-openshift-hostsubnet-ose-bigip-02.yaml
- docs/_static/config_examples/openshift/f5-k8s-bigip-ctlr-openshift.yaml
- docs/_static/config_examples/openshift/f5-kctlr-openshift-clusterrole.yaml
- docs/_static/config_examples/openshift/f5-kctlr-openshift-hostsubnet.yaml
Required YAML files for reference in docs to deploy
CIS on OpenShift multi node and HA setup.
> [DOCS] Deploying CIS on OpenShift and HA setup YAML

- pkg/agent/as3/as3Common.go
- pkg/agent/cccl/outputConfig.go
- pkg/appmanager/agentRequestHandler.go
- pkg/resource/types.go
Problem: CIS crashes after some time. due to race condition
Solution: Handled race condition in CIS while handling AS3 requests
> CIS crashes with fatal error after some time

- pkg/appmanager/routing.go
Problem:
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1160
Solution:
This was partially fixed in [1188](https://github.com/F5Networks/k8s-bigip-ctlr/pull/1188). Even after the fix https redirection was failing when customer trying to access the virtual server by using some common name.
Example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: f5ingress
namespace: default
annotations:
#nginx.ingress.kubernetes.io/rewrite-target: /
kubernetes.io/ingress.class: "f5"
virtual-server.f5.com/ip: "controller-default" # mgmt network
virtual-server.f5.com/partition: "k8s"
virtual-server.f5.com/balance: "least-connections-node"
virtual-server.f5.com/serverssl: 'Common/serverssl'
ingress.kubernetes.io/ssl-redirect: "true"
ingress.kubernetes.io/allow-http: "false" …
```
> Fix https redirection for ingress which accepts all common names

- docs/_static/config_examples/configmap/override-configmap/README.md
- docs/_static/config_examples/configmap/override-configmap/sample-override-bot-defense-profile-configmap.yaml
- docs/_static/config_examples/configmap/override-configmap/sample-override-dos-profile-configmap.yaml
- docs/_static/config_examples/configmap/override-configmap/sample-override-pool-members-configmap.yaml
- docs/_static/config_examples/configmap/override-configmap/sample-override-virtual-configmap.yaml
- docs/_static/config_examples/configmap/override-configmap/sample-override-waf-profile-configmap.yaml
- docs/_static/config_examples/configmap/override-configmap/sample-waf-policy-configmap.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/README.md
- docs/_static/config_examples/configmap/user-defined-configmap/deployments/create-f5-hello-world.md
- docs/_static/config_examples/configmap/user-defined-configmap/deployments/delete-f5-hello-world.md
- docs/_static/config_examples/configmap/user-defined-configmap/deployments/f5-hello-world-deployment.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/deployments/f5-hello-world-service.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/sample-end-to-end-ssl-waf.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/sample-end-to-end-ssl.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/sample-f5-waf-policy.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/sample-tenant-filtering-configmap.yaml
- docs/_static/config_examples/configmap/user-defined-configmap/sample-waf-configmap.yaml
AS3 ConfigMap in YAML format added in Docs
> [DOCS] AS3 ConfigMap documentation

- docs/RELEASE-NOTES.rst
Release notes updated for 2.0.
> Release notes update for 2.0

- docs/RELEASE-NOTES.rst
New release section "Next Upgrade Notes" added for next release informations.
> New release section "Next Upgrade Notes" added

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
- pkg/crmanager/node_poll_handler.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Addresses issue: https://github.com/F5Networks/k8s-bigip-ctlr/issues/1033
> Add NodeLabel support in VirtualServer CRD

- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Feature:
Process CRD TLSProfile with Kubernetes secret
> CRD Custom profile support using secret

- pkg/crmanager/node_poll_handler.go
Problem: CIS not processing virtual servers on updating nodes with the nodeLabel that is configured in the pool of the same virtual server.
Solution: Consider node labels as a parameter to identify change in cached Nodes in CIS.
> Fix Process VS for change in NodeLable Members

- config/apis/cis/v1/types.go
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
Feature added: health monitor support added in CRD.
> health monitor support added in CRD

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Create Datagroups and Irules for SSL based Routing
> Create Datagroups and Irules for SSL based Routing

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
Merge VirtualServer Custom Resource configurations into one BIG-IP Virtual Server configuration base on Host IP address.
> Merge Multiple VirtualServersi CRs into One BIG-IP VirutalServer

- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
> Fix handle when CIS fails to find TLS resources for a VS

- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
Problem:
CIS creates policies for httpTraffic none and redirect
Solution:
CIS should not create policies for httpTraffic none and redirect
Regards,
AV
> [CRD] CIS should not create policies for httpTraffic none and redirect

- pkg/agent/as3/as3Common.go
Bug Fix for not creating SSL profile for all route
> Fix for not creating SSL profile for all route

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
- pkg/agent/as3/as3Resource.go
- pkg/agent/as3/as3Utils.go
- pkg/agent/as3/l2l3agent.go
- pkg/agent/cccl/ccclManager.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/appManager.go
- pkg/resource/resourceConfig.go
- pkg/resource/types.go
Feature: Support Multiple UserDefined AS3 ConfigMaps
Regards,
> Support Multiple UserDefined AS3 ConfigMaps

- pkg/crmanager/node_poll_handler.go
Problem:
Node Label Change is not working when CIS watches all namespaces.
Solution:
Added logic to fetch list of virtual servers effected with the nodeLabel Change when CIS watches all namespaces.
Regards,
> [CRD] Fix issues with NodeLabel Changes

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Utils.go
AS3 label flag switching implementation
Support staging AS3 for configmap lable AS3=false
> AS3 label flag switching implementation

- pkg/agent/as3/as3Manager.go
Bugfix for retrying on error 422 response.
CIS was not re-trying to post AS3 declaration for 422 response from BIG-IP.
> Bugfix for retrying on error 422 response

- pkg/appmanager/appManager_test.go
- pkg/appmanager/routing.go
- pkg/crmanager/backend.go
Problem:
Issues with Passthrough IRule parsing HTTP Headers
Solution:
Made relevant changes to the passthrough IRule
Regards,
> Issues with Passthrough IRule parsing HTTP Headers

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/as3/as3Manager.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/appManager.go
Bugfix for not retrying on 422 error, removed user-defined-as3-configmap flag parameter and avoiding continuous pushing configmap resource into the channel.
> Bug fix for not retrying on 422 error with avoiding continuous deploying configmap resource without any change

- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Utils_test.go
- pkg/appmanager/appManager.go
Endpoint changes fix for configmap : Process configmap when changes in endpoint/service.
Fix for error 422 retrying.
> Endpoint changes fix for configmap and 422 error retrying

- build-tools/run-in-docker.sh
Issue: RHEL image build was failing.
Adduser command changes in docker script to resolve it.
> Adduser command changes in docker script

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/example-empty-AS3-declaration.yaml
> 2.1 Release Notes

- docs/RELEASE-NOTES.rst
Fix issues with release notes.
> Fix release notes

- docs/RELEASE-NOTES.rst
> Next release added

- pkg/agent/as3/as3ConfigMap.go
Problem:
Missed AS3 configmap logs in CIS 2.1.
Solution:
Added the missed AS3 configmap logs.
i.e.
[ERROR] [AS3] Error in processing the ConfigMap: /<configmap_name>
[AS3] Updating AS3 Template for tenant <tenant_name> app <app_name> pool <pool_name>
Docker image: nandakishoref5/k8s-bigip-ctlr:new_fix_v2
> Added error messages for AS3 Configmap

- pkg/crmanager/informers.go
Problem: Modification of virtualServerAddress in CRD is not working properly
Solution: 
nandakishoref5/k8s-bigip-ctlr:vip_modify_v5
> Fix for Modification of CRD VirtualAddress Spec

- docs/_static/config_examples/crd/CustomResource.md
- pkg/crmanager/profile.go
- pkg/crmanager/resourceConfig.go
Added logic to does not insert pool if the pool already exists.
> [Health Monitor] Does not insert pool if it already exists.

- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
Virtual Server CRD added required field for the monitor
> Virtual Server CRD added required field for monitor

- pkg/crmanager/worker.go
Process TLS profile for the same virtual host name only and for another way around.
affected branch: master
> Process TLS for same virtual host and vice versa

- pkg/crmanager/worker.go
Problem:
CIS does not process all the Virtual Servers with Same VirtualServerAddress, when one of them is changed.
Solution:
Fix the code to pick the Virtuals with Same VirtualServerAddress, when one of them is changed.
> CRD: Fix issues with TLSProcessing

- Makefile
- docs/README.rst
- docs/RELEASE-NOTES.rst
Fix Issues with Travis on Stable Branch. Travis is failing to create and publish docs to F5 CloudDocs.
> Fix Issues with Travis(release docs) on Stable Branch

- docs/_static/config_examples/crd/CustomResource.md
> CRD doc update

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/types.go
Support for TEEMS using CRDs
Docker image fixed: nandakishoref5/k8s-bigip-ctlr:teems_v5
> CRD TEEMs Integration

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
- docs/_static/config_examples/crd/tls/custom-virtual-address-port/README.md
- docs/_static/config_examples/crd/tls/custom-virtual-address-port/cusotm-http-port.yml
- docs/_static/config_examples/crd/tls/custom-virtual-address-port/custom-https-port.yml
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
Provided option to configure VirtualAddress port number in CRD.
> option to configure virtual address port

- docs/_static/config_examples/crd/MultiPortServices/README.md
- docs/_static/config_examples/crd/MultiPortServices/service.yaml
- docs/_static/config_examples/crd/MultiPortServices/virtual-server.yaml
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
Added support for multiple ports with a single service in Kubernetes.
affected branch: master
> Support for multiple ports in a single service.

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/basic/virtual-server-name/README.md
- docs/_static/config_examples/crd/basic/virtual-server-name/custom-virtual-name.yml
- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
Virtual server name option added to CRD.
> [CRD] Virtual server name option added

- pkg/appmanager/routing.go
- pkg/crmanager/routing.go
CONTCNTR-1942 Unwanted logs are produced by iRule on Big IP
> CONTCNTR-1942 Unwanted logs are produced by iRule on Big IP

- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/HealthMonitor/README.md
- docs/_static/config_examples/crd/HealthMonitor/health-monitored-pool-virtual-server.yaml
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- pkg/crmanager/resourceConfig.go
CRD health monitor enhancement: Support for health monitor for each pool member.
> [crd] Support for health monitor for each pool member

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/as3/postManager.go
- pkg/crmanager/crManager.go
- pkg/crmanager/postManager.go
To check if AS3-RPM is installed on BIG-IP in CRD  mode.
> To Verify if AS3 is Installed on BIGIP in CRD Mode

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
- docs/_static/config_examples/crd/waf/README.md
- docs/_static/config_examples/crd/waf/vs-with-waf.yaml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
Added WAF support in CRD.
Added doc and example.
Signed-off-by: Amit Kumar Gupta <amitg2812@gmail.com>
> [CRD] Added WAF support

- pkg/crmanager/informers.go
> Info log to Debug log changes

- docs/_static/config_examples/configmap/user-defined-configmap/sample-c3d.yaml
this adds additional detail on how to configure Constrained Certificate Delegation (C3D) to add X-Forwarded-For headers when mutual TLS is being used.
> more complete example of c3d and xff headers

- pkg/crmanager/worker.go
Problem: HTTP VS in BIG-IP is not getting created for HTTP VS CRD
Solution: Due to incomplete checking of HTTPS CRD VS this is happening. Add proper checks to fix.
> Fix HTTP VS is not getting created for HTTP CRD VS

- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/noHost/README.md
- docs/_static/config_examples/crd/noHost/noHost-single-pool-virtual.yaml
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
Enhancement: 
Create a Virtual Server without Host parameter.
Solution:
CIS will create a Virtual Server on BIG-IP and attaches a policy which forwards the traffic to pool when the required conditions are met.
Regards,
> Support for Virtual Server Custom Resource without Host Parameter

- pkg/appmanager/routing.go
- pkg/crmanager/routing.go
Added Error handling in i-rule and also typecasting the integers.
> Fixes for irule in CONTCNTR-2156

- .travis.yml
- build-tools/version-tool
Upgrading version-tool to python3
> Migrated to python3

- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/TransportServer/README.md
- docs/_static/config_examples/crd/TransportServer/transport-server.yaml
Doc update for Transport Server CRD.
> [CRD] Doc update for Transport Server

- pkg/agent/as3/as3Common.go
> Share nodes bugfix

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/nccWorker.go
- pkg/crmanager/node_poll_handler.go
- pkg/crmanager/types.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
> Add Feature Namespace Label support to CRD Controller

- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/PathRewrite/README.md
- docs/_static/config_examples/crd/PathRewrite/virtual-server.yaml
- docs/_static/config_examples/crd/basic/vs-customresourcedefinition.yml
> Fix Documentation bug for rewriteAppRoot

- schemas/as3-schema-3.23.0-5-cis.json
> Bug fix AS3 Schema id changes

- docs/_static/config_examples/crd/Install/clusterrole.yml
> Update Clusterrole with nginxcisconnectors

- pkg/crmanager/crManager.go
> Fix namespace handling issue

- requirements.txt
> Update CCCL to latest

- docs/_static/config_examples/crd/CustomResource.md
> Fix Custom Resource Document

- README.md
- docs/RELEASE-NOTES.rst
> Release Notes for 2.2.0

- docs/_static/config_examples/crd/basic/example-single-pool-virtual.yaml
- docs/_static/config_examples/crd/basic/virtual-server-name/custom-virtual-name.yml
- docs/_static/config_examples/crd/tls/custom-virtual-address-port/custom-http-port.yml
- docs/_static/config_examples/crd/tls/custom-virtual-address-port/custom-https-port.yml
- docs/_static/config_examples/crd/tls/reencrypt-bigip-reference/virtualserver.yml
- docs/_static/config_examples/crd/tls/singledomain-with-edge-reencrypt-combination/edge-tls.yaml
- docs/_static/config_examples/crd/tls/singledomain-with-edge-reencrypt-combination/reencrypt-tls.yml
- docs/_static/config_examples/crd/tls/singledomain-with-edge-reencrypt-combination/tea-virtual-server_reen.yaml
- docs/_static/config_examples/crd/tls/tls-with-health-monitor/reencrypt-tls.yaml
- docs/_static/config_examples/crd/tls/tls-with-health-monitor/virtualserver.yml
- docs/_static/config_examples/crd/tls/tls-with-httpredirect/reencrypt-tls.yml
- docs/_static/config_examples/crd/tls/tls-with-httpredirect/virtualserver.yml
- docs/_static/config_examples/openshift/routes/sample-edge-route.yaml
- docs/_static/config_examples/openshift/routes/sample-passthrough-route.yaml
- docs/_static/config_examples/openshift/routes/sample-reencrypt-route.yaml
- docs/_static/config_examples/openshift/routes/sample-route-ab.yaml
- docs/_static/config_examples/openshift/routes/sample-route-balance.yaml
- docs/_static/config_examples/openshift/routes/sample-route-basic.yaml
- docs/_static/config_examples/openshift/routes/sample-route-deployment.yaml
- docs/_static/config_examples/openshift/routes/sample-route-edge-ssl-waf.yaml
- docs/_static/config_examples/openshift/routes/sample-route-service.yaml
- docs/_static/config_examples/openshift/routes/sample-route-waf.yaml
- docs/_static/config_examples/openshift/routes/sample-unsecured-route.yaml
doc changes for github example automation
> Documentation updates

- pkg/crmanager/backend.go
- pkg/crmanager/nccWorker.go
- pkg/crmanager/types.go
[NCC] Change service type HTTP to TCP for 443 passthrough traffic
> ncc passthrough class update

- pkg/agent/as3/as3ConfigMap.go
- pkg/appmanager/appManager.go
- pkg/test/configs/as3config_valid_1.json
- pkg/test/configs/as3config_valid_2.json
Added support for multiport services in config-map
> Added support for multiport services in config-map

- pkg/appmanager/appManager.go
Problems: Unassociated services taking lot of time to be processed, due to endpoint processing.
Solution: Skip processing of endpoints for unassociated services.
> Improve performance while processing unassociated Services

- pkg/appmanager/appManager.go
- pkg/appmanager/profiles.go
- pkg/appmanager/validateResources.go
Fix for concurrent map read and write
> Concurrent Map Read and Write 

- pkg/appmanager/appManager.go
Fix for [Github-1391](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1391). Fix CIS crash when kubernetes api services are exposed
> Fix CIS crash when kubernetes api services are exposed

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/postManager.go
- pkg/crmanager/pythonDriver.go
- pkg/crmanager/types.go
Usage: 
--gtm-bigip-password string          Optional, password for the GMT Big-IP user account.
--gtm-bigip-url string               Optional, URL for the GTM Big-IP
--gtm-bigip-username string          Optional, user name for the GTM Big-IP user account.
--gtm-credentials-directory string   Optional, directory that contains the GTM BIG-IP username, password, and/or url files. To be used instead of username, password, and/or url arguments.
> Added new cli parameters for external gtm

- pkg/appmanager/appManager.go
Fix for [GITHUB-1527](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1527)
> Discovery member log

- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
> Redirect Termination Fix for CRD

- pkg/crmanager/backend.go
> Hostless CRD Fix

- pkg/crmanager/backend.go
- pkg/crmanager/pythonDriver.go
Added validation for GTM parameters
> Added validation for GTM parameters

- pkg/crmanager/backend.go
- pkg/crmanager/informers.go
- pkg/crmanager/worker.go
> Add UPDATE and DELETE support to CRD ExternalDNS

- pkg/appmanager/appManager.go
> Fix Pool Members not update not Service modification

- requirements.txt
F5-ctrl-agent and f5-cccl hash update
> F5-ctrl-agent and f5-cccl hash update

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/ExternalDNS/README.md
> CIS 2.2.1 release notes

- pkg/appmanager/routing.go
- pkg/crmanager/routing.go
Fixed the [GITHUB-1584](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1584)
> Fix variable validation in passthrough irule

- pkg/crmanager/resourceConfig.go
Global parameters needs to be updated by every Virtual server pointing to the same hostname
> global parameters needs to be updated by every vs pointing to same host

- pkg/crmanager/resourceConfig.go
Reverts F5Networks/k8s-bigip-ctlr#1609
> Revert "global parameters needs to be updated by every vs pointing to same host"

- pkg/crmanager/worker.go
Fix for Single Hostname with Duplicate Path in CRD
> Fix for Single Hostname with Duplicate Path in CRD

- pkg/appmanager/appManager.go
Validate invalid routes duplicate host and path.
> Validate invalid routes duplicate host and path

- pkg/crmanager/worker.go
Handles duplicate paths with multiple virtual server custom resources pointing to same hostname and virtualaddress.
Fixes gitlab #602
> handle duplicate path for same hostname

- pkg/vxlan/vxlanMgr.go
Problem: With flannel new versions cis fails to update fdb and arp for cluster mode.
Fixes Mac parsing to handle the new annotation format
change in flannel annotation with new versions:
flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":""}'
older versions:
flannel.alpha.coreos.com/backend-data: {"VtepMAC":""}
Fix issues:
Github #1480
> Fix mac address parsing

- pkg/appmanager/appManager_test.go
- pkg/appmanager/healthMonitors_test.go
- pkg/appmanager/profiles_test.go
- pkg/appmanager/routing_test.go
- pkg/appmanager/validateResources.go
Validate routes certificate and key.
> Validate routes certificate and key

- pkg/crmanager/backend.go
- pkg/crmanager/types.go
Problem: Arp not getting populated for custom resources.
> Fix arp updation with cr resources

- docs/RELEASE-NOTES.rst
> CIS 2.2.2 Release Notes

- docs/RELEASE-NOTES.rst
> CIS 2.2.3 Release Notes

- config/apis/cis/v1/types.go
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
Add allowVlans support for virtualserver resource
#1621
> Add allow vlans option for vs CRD

- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
Added missing option for automation installation
> Add allowVlans in docs/install

- pkg/appmanager/routing.go
- pkg/crmanager/routing.go
Problem: As mentioned in Github-1646, iRule wasn't compatible to CMP mode supporting all CPUs.
Solution: Made the changes in iRule according to CMP restrictions so that CMP mode support all CPUs.
> Fix for CMP restrictions in the BIG-IP system

- azure-pipelines.yaml
- build-tools/Dockerfile-int
**Description**:  update base image for build
**Fixes**:
> update base builder image

- build-tools/Dockerfile-int
**Description**: F5 CCCL and F5 SDK is not getting installed in current azure pipelines.
**Changes Proposed in PR**: Included the fix to install these packages.
> Fixing the build issues with respect to cccl installation

- pkg/crmanager/informers.go
- pkg/crmanager/worker.go
**Description**:  CIS was not updating/deleting hostSpec info on IPAM CR. 
**Changes Proposed in PR**: Bugfix to IPAM CR for hostSpec updates/delete by CIS.
> CIS update/delete to IPAM CR bug fix

- pkg/agent/as3/as3ConfigMap.go
- pkg/appmanager/appManager.go
**Description**:  adding logs to improve as3 template validation 
> log improvements

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/tls/passthrough/passthrough_tls.yaml
- docs/_static/config_examples/crd/tls/tls-customresourcedefinition.yml
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
**Description**:  _Add Issue/Feature description_: Added new feature Passthrough TLS Termination
**Changes Proposed in PR**: Configure LTM Policies to drive the live traffic
> Add Feature Passthrough TLS Termination

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/IngressLink/README.md
**Description**:  2.3 Release notes
> 2.3 Release Notes

- pkg/crmanager/postManager.go
- pkg/crmanager/profile.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  _Remove Unused code_
**Changes Proposed in PR**: Code removal
> Remove unused code from Custom Resource Manager

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/crd/CustomResource.md
- docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
- docs/_static/config_examples/crd/TransportServer/README.md
- docs/_static/config_examples/crd/TransportServer/tcp-transport-server.yaml
- docs/_static/config_examples/crd/TransportServer/udp-transport-server.yaml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
**Description**:  Support for type UDP Transport Server
**Changes Proposed in PR**: Added support for UDP Transport Server in crmanager 
**Fixes**: This PR resolves #1573
> Support UDP Transport Server

- pkg/crmanager/worker.go
**Description**:  CIS works properly when detects the CIDR change.
**Changes Proposed in PR**: Making syncvirtualserver host-centric and fix in requestIP to properly detect CIDR changes in hostSpecs
> CIDR Update for CIS

- pkg/crmanager/resourceConfig.go
**Description**: Transport Server service address bug fix
> Transport Server service address bug fix

- docs/RELEASE-NOTES.rst
- pkg/crmanager/backend.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  Added the health monitor support in ingressLink resource
**Changes Proposed in PR**:  health monitor support for ingressLink resource
> Added health monitor support in ingressLink resource

- docs/RELEASE-NOTES.rst
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/routing.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  _Datagroup is not getting removed when corresponding VirtualServer is removed_
**Changes Proposed in PR**: Reorganize internal Data Struct in such a way that Datagroups and iRules associated with a VirtualServer will be under the VirtualServer structure.
> Fix Stale Datagroup delete issue

- docs/_static/config_examples/crd/Install/clusterrole.yml
- docs/_static/config_examples/sample-rbac.yaml
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/eventNotifier.go
- pkg/crmanager/crManager.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Add API to update Ingress Status of a Service

- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  Support for implicit health monitor with ingressLink resource in nodeport mode
> Fix for implicit health monitor with ingressLink resource

- pkg/crmanager/worker.go
**Description**: CIS updates on IPAM CR Bugfix: Workaround for CIS IPAM Update issue.
**Fixes**: Delaying for next IPAM sync.
Signed-off-by: Amit Gupta amitg2812@gmail.com
> Workaround for CIS IPAM Update issue.

- pkg/crmanager/validate.go
- pkg/crmanager/worker.go
**Description**: CIS is deleting the BIGIP objects if ipamLabel is removed in the transport server
Signed-off-by: Amit Gupta amitg2812@gmail.com
> CIS Bug fix: CIS is deleting the BIGIP objects if ipamLabel is removed in the transport server

- docs/_static/config_examples/crd/CustomResource.md
**Description**:  Update Doc, CIS CRD supports service address feature and parameters
**Changes Proposed in PR**: updated examples for service address parameter in CustomResource.md 
> service-address-doc-update

- docs/RELEASE-NOTES.rst
- docs/_static/config_examples/example-service-type-lb.yaml
- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
**Description**:  _Add Feature Service Type LoadBalancer_
> Add Feature Service Type LoadBalancer with IPAM

- go.mod
- go.sum
- vendor/github.com/F5Networks/f5-ipam-controller/pkg/ipammachinery/ipam.go
- vendor/modules.txt
**Description**:  Update ipam controller package with latest commit hash and vendor package update.
> Update vendor package for ipam controller

- pkg/appmanager/profiles.go
**Description**:  CIS crash issue fix for invalid config provided.
> CIS crash issue fix for invalid config

- pkg/crmanager/worker.go
**Description**:  Multiple host-less virtual servers unable to process
> Multiple host-less virtual servers unable to process

- requirements.txt
Description: Vulnerability Fix for PyYAML and cryptography packages
Changes Proposed in PR:
Fixes: #1764
** CIS Image ** : nandakishoref5/k8s-bigip-ctlr:v2.4_cf_v1
> Fix Python Vulnerabilities in F5-CCCL repo

- pkg/crmanager/worker.go
> Fix Issue No Config Update on BIG-IP for Endpoionts Update

- pkg/crmanager/worker.go
**Description**:  Transport Server profile changes on BIGIP.
> TS Profile override bug fix

- pkg/crmanager/crManager.go
**Description**:  _Include BIG-IP IP address int the name of IPAM Resource so that each CIS controller will have a dedicated IPAM resource in HA mode_
> Update IPAM Resource Name Format to Fit for HA

- docs/_static/config_examples/crd/Install/clusterrole.yml
> Update Clusterrole for IPAM

- pkg/crmanager/informers.go
> Filter out other IPAM resources on Informer Events

- requirements.txt
**Changes Proposed in PR**: Update CCCL with PyYaml, crypto package version. https://github.com/f5devcentral/f5-cccl/pull/265
> Updated with latest CCCL commit

- docs/RELEASE-NOTES.rst
- pkg/crmanager/crManager.go
- pkg/crmanager/profile.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  Reorganise Internal Resource Data Structures for Custom Profiles
**Fixes**: #1808
> Reorganise Internal Resource Data Structures for Custom Profiles

- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/sample-headless-service-ingress.yaml
- pkg/appmanager/appManager.go
- pkg/crmanager/worker.go
**Description**: Fix Processing endpoint with node names when CIS in Cluster mode
**Changes Proposed in PR**: Removed the node check while adding the endpoints.
> Fix Processing endpoint with node names when CIS in Cluster mode

- operator/build/Dockerfile
- operator/helm-charts/f5-bigip-ctlr/Chart.yaml
- operator/helm-charts/f5-bigip-ctlr/README.md
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrolebinding.yaml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-customresourcedefinitions.yml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-serviceaccount.yaml
- operator/helm-charts/f5-bigip-ctlr/values.yaml
- operator/manifest/new-f5-bundle/1.7.0/manifests/f5-bigip-ctlr-operator.v1.7.0.clusterserviceversion.yaml
**Description**:   IBM Platform Certification - Linter issue fixes
**Changes Proposed in PR**: Updated the labels and required parameters for CIS deployment
> IBM Platform Certification - Linter issue fixes

- .github/pull_request_template.md
- azure-pipelines.yaml
- docs/RELEASE-NOTES.rst
**Description**:  Update 2.4.1 release notes, Add resolves keyword to automatically close GITHUB issues.
> Update 2.4.1 release notes

- docs/config_examples/crd/CustomResource.md
Added VirtualHTTPPort and VirtualHTTPSPort in CRD examples.
> Add virtualHTTPPort and virtualHTTPSPort in CRD examples.

- docs/RELEASE-NOTES.rst
- docs/config_examples/crd/serviceTypeLB/README.md
- docs/config_examples/crd/serviceTypeLB/multiport-serviceTypeLB.yaml
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/worker.go
**Description**:  Type LB support for multiport service
CIS build: nandakishoref5/k8s-bigip-ctlr:LB_MP_fin
> Type LB support for multiport service

- pkg/appmanager/appManager.go
**Description**:  Log message type changed when endpoint not found. Error type to debug type.
> Log message type changed when endpoint not found

- docs/RELEASE-NOTES.rst
- docs/config_examples/crd/serviceTypeLB/README.md
- docs/config_examples/crd/serviceTypeLB/healthMonitor-serviceTypeLB.yaml
- pkg/crmanager/crManager.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
**Description**:  HealthMonitor Support for ServiceTypeLB
Docker build: nandakishoref5/k8s-bigip-ctlr:LB_HM_fin
> HealthMonitor Support for ServiceTypeLB

- config/apis/cis/v1/doc.go
- config/client/clientset/versioned/clientset.go
- config/client/clientset/versioned/fake/clientset_generated.go
- config/client/clientset/versioned/fake/register.go
- config/client/clientset/versioned/scheme/register.go
- config/client/clientset/versioned/typed/cis/v1/cis_client.go
- config/client/clientset/versioned/typed/cis/v1/externaldns.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_cis_client.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_externaldns.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_ingresslink.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_tlsprofile.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_transportserver.go
- config/client/clientset/versioned/typed/cis/v1/fake/fake_virtualserver.go
- config/client/clientset/versioned/typed/cis/v1/ingresslink.go
- config/client/clientset/versioned/typed/cis/v1/tlsprofile.go
- config/client/clientset/versioned/typed/cis/v1/transportserver.go
- config/client/clientset/versioned/typed/cis/v1/virtualserver.go
- config/client/informers/externalversions/cis/v1/externaldns.go
- config/client/informers/externalversions/cis/v1/ingresslink.go
- config/client/informers/externalversions/cis/v1/tlsprofile.go
- config/client/informers/externalversions/cis/v1/transportserver.go
- config/client/informers/externalversions/cis/v1/virtualserver.go
- config/client/informers/externalversions/factory.go
- config/client/informers/externalversions/generic.go
- pkg/crmanager/worker.go
> Set CRD group name to proper one

- docs/RELEASE-NOTES.rst
- docs/config_examples/configmap/hubMode-enabled-configmap/sample-cm-with-hubmode.yaml
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager_test.go
- pkg/appmanager/appManager.go
- pkg/resource/resourceConfig.go
- pkg/resource/types.go
**Description**:  Configmap new label hubMode implementation to support configmap monitored service in different namespace
**Fixes**:
> Configmap new label hubMode implementation

- docs/RELEASE-NOTES.rst
- pkg/crmanager/worker.go
**Description**: Added support to process EDNS  when CIS is watching all namespaces
**Changes Proposed in PR**: Added support to process EDNS  when CIS is watching all namespaces
**Fixes**: internal <no id>
> Fix EDNS processing when CIS is watching all namespaces

- cmd/k8s-bigip-ctlr/main.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
- pkg/appmanager/validateResources.go
- pkg/resource/resourceConfig.go
- pkg/resource/types.go
**Description**:  Ingress Performance Improvements
> ingress performance improvements

- pkg/crmanager/routing.go
- pkg/resource/resourceConfig.go
- pkg/resource/resourceConfig_test.go
- pkg/teem/teem_test.go
Fix for CIS adds extra slash '/' when set rewrite-target-url annotation as '/'.
> Fix for CIS adds extra slash '/' when set rewrite-target-url annotation as '/'

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/crd/IngressLink/cis-config/cis_rbac.yaml
- docs/config_examples/crd/Install/clusterrole.yml
- docs/config_examples/ingress/networkingV1/example-default-ingress-class.yaml
- docs/config_examples/ingress/networkingV1/example-ingress-class-name.yaml
- docs/config_examples/ingress/networkingV1/ingress-with-health-monitors.yaml
- docs/config_examples/ingress/networkingV1/name-based-ingress.yaml
- docs/config_examples/ingress/networkingV1/sample-app-root-annotation.yaml
- docs/config_examples/ingress/networkingV1/sample-headless-service-ingress.yaml
- docs/config_examples/ingress/networkingV1/sample-url-rewrite-annotation.yaml
- docs/config_examples/ingress/networkingV1/simple-ingress-fanout.yaml
- docs/config_examples/ingress/networkingV1/single-service-ingress.yaml
- docs/config_examples/ingress/networkingV1/single-service-tls-ingress-2.yaml
- docs/config_examples/ingress/networkingV1/single-service-tls-ingress.yaml
- docs/config_examples/openshift/HA/f5-kctlr-openshift-clusterrole.yaml
- docs/config_examples/openshift/f5-kctlr-openshift-clusterrole.yaml
- docs/config_examples/sample-rbac.yaml
- operator/helm-charts/f5-bigip-ctlr/README.md
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
- operator/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-ingress-class.yaml
- operator/helm-charts/f5-bigip-ctlr/values.yaml
- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/ingress_test.go
- pkg/resource/types.go
- pkg/teem/teem_test.go
- pkg/vxlan/vxlanMgr.go
**Description**:  Added Support for IngressClass resource
> Added Support for IngressClass resource

- pkg/teem/teem_test.go
**Description**:  Remove teem positive test case
**Changes Proposed in PR**: Removed teem positive test case which pushes data into prod server
**Fixes**: internal
> Remove teem positive test case

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**:  Added support for deployment parameter periodic-sync-interval
> Added support for deployment parameter periodic-sync-interval

- config/apis/cis/v1/types.go
- docs/config_examples/crd/Install/customresourcedefinitions.yml
- docs/config_examples/crd/TransportServer/udp-transport-server.yaml
- pkg/crmanager/resourceConfig.go
**Description**:  Added irule Support for TS CRD
**Fixes**: resolves #1570
> Added irule Support for TS CRD

- pkg/appmanager/appManager.go
- pkg/appmanager/ingress.go
**Description**:  Fix continuous error logs with Ingress status update
Handle deleted Ingress status update error logs.
Fix the unnecessary goroutines being spawned for Ingress status update
> Fix continuous error logs with Ingress status update

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/ingress.go
- pkg/appmanager/validateResources.go
**Description**: Added informers for Kubernetes secrets
> Added informers for Kubernetes secrets

- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Manager_test.go
> Add Default Cipher Group for TLS V1.3 in AppManager

- cmd/k8s-bigip-ctlr/main.go
**Description**:  Updating the default periodic sync interval to 300 seconds
**Changes Proposed in PR**: Updating the default periodic sync interval to 300 seconds
> Updating the default periodic sync interval to 300 seconds

- docs/config_examples/crd/IngressLink/README.md
**Description**:  Updating the doc link for Integration with F5 Container Ingress Services
> Updating Ingresslink Document

- pkg/appmanager/appManager.go
- pkg/appmanager/eventNotifier_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/ingress_test.go
**Description**:  Add IngressClass informers.
Added  support for IngressClass informers.
> Add Ingressclass informers

- pkg/resource/resourceConfig.go
**Description**: Handle approot annotation for V1 Ingress
Added support for approot annotation for V1 Ingress
> support approot annotation for V1 Ingress

- docs/config_examples/crd/Install/customresourcedefinitions.yml
> Rename VS CRD Printable Parameters

- cmd/k8s-bigip-ctlr/main.go
- cmd/k8s-bigip-ctlr/main_test.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/configmap/user-defined-configmap/README.md
- docs/config_examples/configmap/user-defined-configmap/hubmode-configmap/deployments/create-f5-hello-world.md
- docs/config_examples/configmap/user-defined-configmap/hubmode-configmap/deployments/delete-f5-hello-world.md
- docs/config_examples/configmap/user-defined-configmap/hubmode-configmap/deployments/f5-hello-world-deployment.yaml
- docs/config_examples/configmap/user-defined-configmap/hubmode-configmap/deployments/f5-hello-world-service.yaml
- docs/config_examples/configmap/user-defined-configmap/hubmode-configmap/hubmode-cmap.yaml
- pkg/appmanager/appManager.go
- pkg/resource/resourceConfig.go
**Description**: Multiple and Single Namespace support for Configmap 
* Added new configuration parameter in CIS deployment `hubmode`
* Rewrites periodic-sync-interval to 30seconds when in hubmode 
* ConfigMap services can reside in unwatched namespaces ; endpoints will be updated dynamically when in cluster mode  
**Fixes**: JIRA CONTCNTR-2758
> HubMode support for configmaps

- pkg/appmanager/ingress.go
**Description**: Panic fix due to ingress class not found.
**Changes Proposed in PR**: Panic fix due to ingress class not found (Internal bug).
> Panic fix due to ingress class not found.

- go.mod
- go.sum
- vendor/github.com/F5Networks/f5-ipam-controller/pkg/ipamapis/apis/fic/v1/types.go
- vendor/modules.txt
**Description**: IPAM controller hash update with latest commit
> IPAM controller hash update with latest commit

- azure-pipelines.yaml
**Description**:  Added docker and redhat publish steps to azure pipeline
- Added triggers for tags 
- new service connection is needed for scan redhat repo 
- podman pull and push needs special authfile argument
> Added docker and redhat publish steps to azure pipeline

- azure-pipelines.yaml
**Description**:  Initialise docker tag to build version in azure pipeline
**Changes Proposed in PR**: Initialise docker tag to build version in azure pipeline
**Fixes**: resolves internal
> Initialise docker tag to build version in azure pipeline

- docs/config_examples/openshift/routes/sample-route-rewrite-app-root.yaml
- docs/config_examples/openshift/routes/sample-route-rewrite-target-url.yaml
**Description**:  Adding Route Examples
> Adding Route Examples

- docs/RELEASE-NOTES.rst
**Description**:  Added the new functionality introduced and bug fixes for CIS v2.5.0
> Release Notes for CIS v2.5.0

- docs/RELEASE-NOTES.rst
**Description**:  Minor changes to release notes
**Changes Proposed in PR**: Updated docs links and minor type fixes.
> Minor changes to release notes.

- docs/RELEASE-NOTES.rst
**Description**:  Minor changes to release notes
**Changes Proposed in PR**: reorganize release notes.
> Minor changes to release notes

- docs/RELEASE-NOTES.rst
**Description**:  Indentation issues with release notes.
- [*] Updated Added functionality/ bug fix in release notes
> fix Indentation issues with release notes

- azure-pipelines.yaml
**Description**:  Modify minor release docker push step azure pipeline
- Modified file to be compatible with azure platform. 
**Fixes**: internal
> Modify minor release docker push step azure pipeline

- docs/config_examples/sample-rbac.yaml
**Description**:  Update sample_rbac YAML with rule to list, get and watch secrets.
add secrets to apiGroup "" with verbs get, list and watch.
**Fixes**: resolves #1913
> Add secrets to ClusterRole example

- pkg/appmanager/appManager.go
- pkg/appmanager/ingress.go
- pkg/appmanager/validateResources.go
**Description**:  Added validation for single service ingress.
**Changes Proposed in PR**: Added validation for single service ingress while processing ingresses.
> Added validation for single service ingress

- pkg/crmanager/backend_test.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/resourceConfig_test.go
- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
- pkg/test/utils.go
> Add more Unit Testcases to Custom Resource Manager

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/crmanager/worker.go
- pkg/teem/teem.go
**Description**:  Fixing the unit testcase failures
**Changes Proposed in PR**: Commented the events checking in unit testcase and included the lock for map.
> Fixing the unit testcase failures

- pkg/crmanager/crManager.go
**Description**:  _Captial letters are not allowed to be there in the name of resource in the Kubernetes. If the BIGIP Partition has a capital letter in its name, creation of IPAM CR is failing_
**Changes Proposed in PR**: Convert the capital letter into a small case one, but append a `-` to the new small case letter so that there would not be any name collision, in case of multiple CIS controllers managing multiple partitions of same BIGIP.
> Change Name Format for IPAM Resource

- pkg/appmanager/validateResources.go
**Description**:  Fixing the CIS crash issue 
**Changes Proposed in PR**: Handled the error conditions if app-informer is returned as false.
> Fixing the CIS crash issue 

- Makefile
- build-tools/Dockerfile.debug
- docs/RELEASE-NOTES.rst
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
**Description**:  Fix VS processing sharing same IP different port
**Fixes**: resolves 1849
> Fix VS processing sharing same IP different port

- build-tools/Dockerfile.debian
- build-tools/Dockerfile.debug
- build-tools/Dockerfile.ubi
**Description**:  Fix ubi Dockerfile permissions to read CCCL API schema json
- changes to ubi dockerfile
- reordered some statements to be in sync with debian Dockerfile 
**Fixes**: - 
NA
> Fix ubi Dockerfile permissions to read CCCL API schema json

- Makefile
- azure-pipelines.yaml
- build-tools/vet.sh
- pkg/appmanager/validateResources.go
**Description**:  Added Azure-CI-Pipeline Pre-Checks for Go-fmt and make-verify
> Added Azure-CI-Pipeline Pre-Checks for Go-fmt and make-verify

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
**Description**:  Fix: CIS delete and create all objects it had created after CIS pod restart.
> Fix: CIS delete and create all objects CIS pod restart

- pkg/crmanager/crManager.go
Reverts F5Networks/k8s-bigip-ctlr#1920
> Revert "Fix:CIS not deleting old f5ipam cr which is not in use"

- docs/RELEASE-NOTES.rst
**Description**:  Release notes 2.5.1
**Changes Proposed in PR**: Added GITLAB reported bug details.
> 2.5.1 Release notes

- pkg/crmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
Reverts F5Networks/k8s-bigip-ctlr#1956
> Revert "Using strings.ReplaceAll to improve performance"

- docs/RELEASE-NOTES.rst
**Description**:  Updated the release notes
> Updating release notes

- docs/RELEASE-NOTES.rst
Reverts F5Networks/k8s-bigip-ctlr#1962
> Revert "Updating release notes"

- pkg/appmanager/appManager.go
> Rename Manager receiver for consistency

- requirements.txt
**Description**: f5-ctlr-agent hash update to latest
> f5-ctlr-agent hash update to latest

- pkg/resource/types.go
> Expose Host parameter in Ingress Annotation Profile

- pkg/teem/teem.go
> Format struct literal as per go fmt

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
**Description**:  Updating the bigip-url & gtm-bigip-url parameter validation
> Updating the bigip-url & gtm-bigip-url parameter validation

- go.mod
- go.sum
- vendor/golang.org/x/net/html/parse.go
- vendor/golang.org/x/net/http2/ascii.go
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/go115.go
- vendor/golang.org/x/net/http2/headermap.go
- vendor/golang.org/x/net/http2/not_go115.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/write.go
- vendor/golang.org/x/net/idna/idna10.0.0.go
- vendor/golang.org/x/net/idna/idna9.0.0.go
- vendor/golang.org/x/net/internal/socket/mmsghdr_unix.go
- vendor/golang.org/x/net/internal/socket/msghdr_linux.go
- vendor/golang.org/x/net/internal/socket/rawconn_mmsg.go
- vendor/golang.org/x/net/internal/socket/rawconn_msg.go
- vendor/golang.org/x/net/internal/socket/sys_posix.go
- vendor/modules.txt
**Description**:  Upgrade golang.org/x/net for CVE-2021-33194
> Upgrade golang.org/x/net 

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**:  Bug Fix: cccl resource delete on restart 
**Fixes**: resolves #1911
> Bug Fix: cccl resource cleanup on restart

- cmd/k8s-bigip-ctlr/main.go
- requirements.txt
> Add new parameter to control CCCL log level

- go.mod
- go.sum
- pkg/teem/teem.go
- vendor/github.com/f5devcentral/go-bigip/f5teem/f5teem.go
- vendor/github.com/google/uuid/hash.go
- vendor/github.com/google/uuid/null.go
- vendor/github.com/google/uuid/sql.go
- vendor/github.com/google/uuid/uuid.go
- vendor/github.com/google/uuid/version4.go
- vendor/modules.txt
**Description**:  Update Teem vendor dependency
updated teem vendor dependency
**Fixes**: internal
> Update Teem vendor dep

- requirements.txt
> Update to latest f5-ctlr-agent

- cmd/k8s-bigip-ctlr/main.go
**Description**:  Removing unnecessary logs
> Removing unnecessary logs

- pkg/appmanager/appManager.go
**Description**:  Fix Ingress resource delete properly on restart
> Bug Fix Internal: Ingress resource delete

- config/apis/cis/v1/types.go
- docs/config_examples/crd/Install/clusterrole.yml
- docs/config_examples/crd/Install/customresourcedefinitions.yml
**Description**:  Policy support added on VS and TS schema
> Policy support added on VS and TS schema

- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/types.go
**Description**:  Added Policy CRD informers
> Added Policy CRD informers

- docs/config_examples/crd/Install/customresourcedefinitions.yml
- docs/config_examples/crd/Policy/policy-crd.yaml
- docs/config_examples/crd/Policy/sample-policy.yaml
- pkg/crmanager/crManager.go
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Add Processing Policy CRD

- requirements.txt
**Changes Proposed in PR**: Updated the f5-ctlr-agent package
**Fixes**: resolves #2032
> Fix EDNS issues in GTM Agent and Update to latest agent

- docs/RELEASE-NOTES.rst
**Description**:  Release notes for 2.6.1 release
> Release notes for 2.6.1 release

- docs/RELEASE-NOTES.rst
- docs/config_examples/crd/ExternalDNS/README.md
- docs/config_examples/crd/ExternalDNS/externaldns-tcp-monitor.yaml
- docs/config_examples/crd/Install/customresourcedefinitions.yml
- pkg/crmanager/worker.go
**Description**:  GSLB TCP support and doc update to GSLB pool tcp monitor support
> GSLB TCP support and doc update to GSLB pool tcp monitor support

- config/apis/cis/v1/types.go
- docs/config_examples/crd/Install/customresourcedefinitions.yml
- docs/config_examples/crd/basic/virtual-with-hostGroup/README.md
- docs/config_examples/crd/basic/virtual-with-hostGroup/virtual-with-hostGroup.yaml
- docs/config_examples/crd/basic/vs-customresourcedefinition.yml
> Add new parameter hostsGroup to VirtualServr Spec

- f5-bigip-ctlr-operator/Dockerfile
- f5-bigip-ctlr-operator/licenses/apache.txt
**Description**: Adding Redhat Certification requirements for operator image
> "Adding Redhat Certification requirements for operator image"

- config/apis/cis/v1/types.go
- docs/config_examples/customResource/Policy/sample-policy.yaml
- docs/config_examples/customResourceDefinations/customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Support profiles for VS and TS resource using PolicyCRD

- requirements.txt
**Description**:  F5-ctlr-agent hash update with latest commit.
> F5-ctlr-agent hash update

- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
**Description**:  _VirtualServers are grouped based on hostGroup and will be processed as one unit_
> Add feature virtualservers grouping by hostGroup

- docs/config_examples/customResource/IngressLink/ingress-example/cafe-ingress.yaml
- docs/config_examples/ingress/networkingV1/sample-headless-service-ingress.yaml
**Description**:  docs update.
> Updating ingress examples to v1 api 

- pkg/crmanager/informers.go
- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
**Description**: CIS multihost support integration with FIC
> CIS multihost support integration with FIC

- config/apis/cis/v1/types.go
- docs/config_examples/customResourceDefinations/customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/crManager.go
- pkg/crmanager/crManager_suit_test.go
- pkg/crmanager/postManager.go
- pkg/crmanager/postManager_test.go
- pkg/crmanager/responseHandler.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
> Updating StatusOK of VS CRDs

- pkg/crmanager/informers.go
- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
Reverts F5Networks/k8s-bigip-ctlr#2109
> Revert "CIS multihost support integration with FIC"

- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/VirtualServer/virtual-with-wildcard-domain/README.md
- docs/config_examples/customResource/VirtualServer/virtual-with-wildcard-domain/tls-with-wildcardhost.yaml
- docs/config_examples/customResource/VirtualServer/virtual-with-wildcard-domain/virtual-with-wildcardhost.yaml
- docs/config_examples/customResourceDefinations/customresourcedefinitions.yml
- pkg/crmanager/backend.go
- pkg/crmanager/postManager.go
- pkg/crmanager/postManager_test.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/responseHandler.go
- pkg/crmanager/routing.go
- pkg/crmanager/worker.go
**Description**:  wildcard support for virtualserver
wildcard domain support for TLSProfile and VirtualServer.
**Fixes**: resolves #2006
> wildcard domain support for virtualserver

- docs/config_examples/customResourceDefinations/customresourcedefinitions.yml
**Description**:  Added ipam label in additional fields for transport server
**Changes Proposed in PR**: Added ipam label in additional fields for transport server
> Added ipam label in additional fields for transport server

- pkg/appmanager/ingress.go
**Description**:  Fix crash with ingressclass
> Fix crash with ingressclass

- .github/pull_request_template.md
- pkg/crmanager/worker.go
**Description**:  _Enhanced Debug logs for updating TS and VS Status_
> Enhanced Debug logs for updating TS and VS Status

- pkg/crmanager/worker.go
**Description**:  Bugfix: CIS is posting the declaration if policy CRD is not found
> Bugfix:CIS is posting the declaration if policy CRD is not found

- pkg/agent/as3/l2l3agent.go
**Description**: Fix for ARP entries with ingress resource
**Changes Proposed in PR**: Changed the logic for tenant filter based arp entries push
> Fix for ARP entries with ingress resource

- cmd/k8s-bigip-ctlr/main.go
- pkg/agent/agent.go
- pkg/agent/agentAS3.go
- pkg/agent/agentCCCL.go
- pkg/agent/as3/postManager.go
- pkg/crmanager/postManager.go
- pkg/teem/teem.go
**Description**:  Teems data update to include BigIP reg key
> Teems data update to include BigIP reg key

- docs/RELEASE-NOTES.rst
- docs/config_examples/ingress/networkingV1/single-service-namedport-ingress.yaml
- docs/config_examples/ingress/single-service-namedport-ingress.yaml
- pkg/appmanager/ingress.go
- pkg/appmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
**Description**:  Support named service port reference for ingresses
- Ingress v1 and v1beta resource to support service named port reference processing
**Fixes**: resolves #2031
> Support named service port reference for ingresses

- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Types.go
- pkg/appmanager/profiles.go
- pkg/resource/types.go
> Remove ECDSA cert SNI support for OpenShift Routes

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Support SNIServerName for GTM HTTPS Monitor and Handling GTM Exceptions
**Fixes**: resolves #2025
> Support SNIServerName for GTM HTTPS Monitor and Handling GTM Exceptions

- pkg/crmanager/worker.go
**Description**:  Fix VS processing with multihost mode
- return and log error only when it is non-nil
**Fixes**: internal 792
> Fix VS processing with multihost mode

- pkg/crmanager/worker.go
Fix for CIS is posting the declaration if policy CRD is not found for  transport server
> Fix for CIS is posting the declaration if policy CRD is not found for  transport server

- cmd/k8s-bigip-ctlr/main.go
- pkg/crmanager/backend.go
- pkg/crmanager/types.go
**Description**:  disable cccl for ipv6 cluster
> disable cccl for ipv6

- pkg/crmanager/responseHandler.go
**Description**: Handle VS,TS status update when they are not found
- break when there are error 
**Fixes**: internal 794
> Handle VS,TS status update when they are not found

- pkg/crmanager/backend.go
- pkg/crmanager/backend_test.go
**Description**:  Fix datgroup for ipv6
> Fix datgroup for ipv6

- pkg/crmanager/routing.go
**Description**:  Fix irule for wildcard
> Fix irule for wildcard 

- pkg/crmanager/backend_test.go
- pkg/crmanager/informers.go
- pkg/crmanager/resourceConfig.go
- pkg/crmanager/resourceConfig_test.go
- pkg/crmanager/types.go
- pkg/crmanager/worker.go
- pkg/crmanager/worker_test.go
> Refactor Pool Members data to improve performance

- go.mod
- go.sum
- vendor/modules.txt
**Description**:  Update go mod with latest FIC changes
- Update go mod, sum, vendor/modules.txt with latest FIC commit
> Update go mod with latest FIC changes

- azure-pipelines.yaml
- helm-charts/f5-bigip-ctlr/Chart.yaml
**Description**:  Updated helm chart version and CRD install paths
- update charts version 
- fix CRD install path in azure pipeline
> Updated helm chart version and CRD install paths

- docs/RELEASE-NOTES.rst
**Description**:  2.7 Release notes
- Added/formatted release notes
> 2.7 Release notes

- cmd/k8s-bigip-ctlr/main.go
**Description**:  Fix for fetching the bigip registration key as per teems flag
> Fix for fetching the bigip registration key as per teems flag

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/agent/agent.go
- pkg/agent/agentAS3.go
- pkg/agent/agentCCCL.go
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/l2l3agent.go
- pkg/agent/as3/postManager.go
**Description**:  Fix processing FilterTenants
> Fix processing FilterTenants

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Manager.go
> Fix AS3 Post Delay in case of Error

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Fix recreating ARPs when CIS restarts
**Fixes**: resolves #2077
> Fix recreating ARPs when CIS restarts

- build-tools/Dockerfile.debian
- build-tools/Dockerfile.debug
- build-tools/Dockerfile.ubi
- requirements.txt
**Description**:   upgrade python to 3.8
> python upgrade

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/ingress.go
- pkg/appmanager/ingress_test.go
- pkg/appmanager/validateResources.go
> Fix Go vet formatting

- docs/RELEASE-NOTES.rst
- pkg/crmanager/worker.go
**Description**: Added support for UDP protocol in Services of type LoadBalancer
**Fixes**: resolves #1872
> Added support for UDP protocol in Services of type LoadBalancer

- pkg/crmanager/worker.go
**Description**:  Fix for crash observed in CR mode
> Fix for crash observed in CR mode

- docs/RELEASE-NOTES.rst
- pkg/crmanager/worker.go
**Description**:  _Endpoint address node is not being checked for nil value_
**Changes Proposed in PR**: Add additional check for nil value in endpoint address node
**Fixes**: resolves #2172
> Fix Endpoints processing issue

- requirements.txt
**Description**:  update latest ctlr-agent hash with commit https://github.com/f5devcentral/f5-ctlr-agent/commit/225709697567d718c47ff3346533a2359418cc8b
> update latest ctlr-agent hash

- docs/troubleshooting.md
**Description**:   Adding troubleshoot doc for CIS
> Adding troubleshoot doc

- docs/RELEASE-NOTES.rst
**Description**:  Release notes for CIS 2.7.1
> Release Notes CIS 2.7.1

- f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
**Description**: Operator Bundle 1.10.0 release
> Operator Bundle 1.10.0 release

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/node_poll_handler.go
- pkg/controller/node_poll_handler_test.go
- pkg/controller/postManager.go
- pkg/controller/postManager_test.go
- pkg/controller/profile.go
- pkg/controller/profile_test.go
- pkg/controller/pythonDriver.go
- pkg/controller/pythonDriver_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/responseHandler.go
- pkg/controller/routing.go
- pkg/controller/types.go
- pkg/controller/validate.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
> Rename files and structures

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/controller.go
- pkg/controller/node_poll_handler.go
- pkg/controller/types.go
- pkg/controller/worker.go
> Rename pool member mode

- pkg/controller/controller.go
- pkg/controller/types.go
> Add Route Client

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/profile.go
- pkg/controller/profile_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**: Reorganised custom profiles in controller
- removed custom profile filed form ResourceConfigRequest 
- modified processCustomProfilesForAS3 to accept rsCfgs 
- modified UT's
> Reorganised custom profiles in controller

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
> Refactor Resource Store

- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/postManager.go
**Description**:  Stop reposting AS3 declaration for 422 status code. When the change is done by the user, CIS gets an update event and CIS processes that request, this would fix the problem.
**Fixes**: resolves #2210
> Stop retrying 422 Status Code when filter-tenants enabled.

- pkg/teem/teem.go
**Description**:  Move teem logs to debug
> Move teem logs to debug

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/controller_suit_test.go
- pkg/controller/types.go
**Description**:  Agent changes for multi partition support in controller package
- Updated agent createAS3Declaration processing
- activeDecl now contains a map of tenant and corresponding config
- newDecl maintains the config which needs to be posted. Once the post is successful, tenants declarations in activeDecl will be updated 
- This PR does not handle unsuccessful As3 posts. {TBD}
**Fixes**: internal CONTCNTR-2856
> Agent changes for multi partition support

- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3Common.go
- pkg/agent/cccl/outputConfig.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/appManager.go
- pkg/appmanager/resourceConfig.go
- pkg/appmanager/routing.go
- pkg/resource/types.go
**Description**: Added fix for cis crash with routes
**Changes Proposed in PR**: Using the mutex lock for iRuleMap to avoid the concurrent read/write
> Added fix for concurrent read/write of iRuleMap

- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
> Fix Unit test cases

- pkg/controller/backend.go
- pkg/controller/postManager.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Handling Delete Request for VSStatus
**Fixes**: resolves #2221
> Handling Delete Request for VSStatus and TSStatus 

- pkg/controller/profile.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/types.go
Code restructuring for processing TLS profiles/certs from group of routes
**Changes Proposed in PR**:  Restructured the code for processing TLS profiles/certs from group of routes
> Code restructuring for processing TLS profiles/certs from group of routes

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/constants.go
- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResources.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
> Add skeleton for Next Gen Controller

- pkg/controller/backend.go
- pkg/controller/types.go
**Description**:  Supporting None for Persistence Profile
> Supporting None for Persistence Profile

- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/resourceConfig.go
- pkg/resource/resourceConfig.go
- pkg/resource/types.go
**Description**:  Updated the fix for processing oldest route when same host and path in routes
> Updated the fix for processing oldest route when same host and path in routes

- pkg/controller/backend.go
- pkg/controller/backend_test.go
- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/postManager.go
- pkg/controller/postManager_test.go
- pkg/controller/pythonDriver.go
- pkg/controller/types.go
**Description**:  Agent changes for multi-partition support
- added new retry decl map to post failed/accepted tenant decl
- abv map maintains as3 resp code of requests 
- retry will be done in a goroutine
- new stopChan for communicating with retry goroutine 
- modified function capabilities once Postconfig is invoked from worker.go 
Pending: 
Fixing Unit Tests
> Agent changes for multi-partition support

- pkg/controller/backend.go
- pkg/controller/postManager.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Handling CR Status Delete Operation by moving business logic to respChan Handler.
> Handling CR Status Delete Operation

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/types.go
> Add provision for RouteSpecConfigmap

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/ExternalDNS/README.md
- docs/config_examples/customResource/ExternalDNS/externaldns-multiple-monitors.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
- requirements.txt
**Description**:  Added support for multiple Health monitors in EDNS resource
> Added support for multiple Health monitors in EDNS resource

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/IngressLink/ingresslink.yaml
- docs/config_examples/customResource/TransportServer/ts-with-hostname.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/worker.go
**Description**: Added support for host in TransportServer and IngressLink CR
> Added support for host in TransportServer and IngressLink CR.

- pkg/controller/types.go
> Add data stuctures to hold extened spec of Routes

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/constants.go
- pkg/controller/controller.go
- pkg/controller/nativeResources.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routes.go
- pkg/controller/routing.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Native controller insecure routes
- insecure routes in native controller 
- made few methods generic to handle VS and routes
> Native controller insecure routes

- pkg/controller/backend.go
- pkg/controller/postManager.go
* Retry posting config continuously on AS3 201 response
* Fix crash while reading response body on 201
> Retry posting config continuously on AS3 201 response

- docs/config_examples/appsExample/SecuredApp/openshift-secured-deployment.yaml
- docs/config_examples/appsExample/SecuredApp/secured-deployment.yaml
- docs/config_examples/appsExample/SecuredApp/secured-service.yaml
- docs/config_examples/appsExample/TCPApp/openshift-tcp-deployment.yaml
- docs/config_examples/appsExample/TCPApp/tcp-deployment.yaml
- docs/config_examples/appsExample/TCPApp/tcp-service.yaml
- docs/config_examples/appsExample/UDPApp/openshift-udp-deployment.yaml
- docs/config_examples/appsExample/UDPApp/udp-deployment.yaml
- docs/config_examples/appsExample/UDPApp/udp-service.yaml
- docs/config_examples/appsExample/UnSecuredApp/openshift-unsecured-deployment.yaml
- docs/config_examples/appsExample/UnSecuredApp/unsecured-deployment.yaml
- docs/config_examples/appsExample/UnSecuredApp/unsecured-service.yaml
**Description**:  Added Config Apps Examples
> Added Config Apps Examples

- pkg/controller/nativeResources.go
- pkg/controller/types.go
**Description**:   Custom iRule support for NextGen Routes
**Changes Proposed in PR**: Added Support for custom iRule
>  Custom iRule support for NextGen Routes

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/NodePortLocal/README.md
- docs/config_examples/NodePortLocal/deployment.yaml
- docs/config_examples/NodePortLocal/ingress.yaml
- docs/config_examples/NodePortLocal/service.yaml
- docs/config_examples/NodePortLocal/virtual-server.yaml
- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
- pkg/test/utils.go
**Description**:  Added Support for NodePortLocal(Antrea CNI) feature with CIS.
> Adding NPL support

- docs/config_examples/NodePortLocal/README.md
- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/controller/worker_test.go
Adding unit tests for NPL feature
Doc updates for NPL
> Adding unit tests for NPL feature

- pkg/agent/as3/postManager.go
**Description**: Fix for CIS is not retrying when AS3 response code is 422
**Changes Proposed in PR**: Fix for CIS is not retrying when AS3 response code is 422
> Fix for CIS not retrying when AS3 response code is 422

- docs/RELEASE-NOTES.rst
- helm-charts/f5-bigip-ctlr/Chart.yaml
- helm-charts/f5-bigip-ctlr/templates/NOTES.txt
**Description**: Updating the chart release version for CIS 2.8.0 release
> Updating the chart release version for CIS 2.8.0 release

- docs/RELEASE-NOTES.rst
- pkg/controller/informers.go
**Description**:  Supporting Grafana service in CRDs
**Fixes**: resolves #2233
> Supporting Grafana service in CRDs

- pkg/controller/nativeResources.go
> Fix RouteGroup config issue

- pkg/appmanager/appManager.go
- pkg/controller/worker.go
**Description**:  Fix crash with NPL on service delete
> Fix crash with NPL

- pkg/controller/backend.go
- pkg/controller/nativeResources.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Added support for secure routes
**Changes Proposed in PR**: Added support for secure routes
> Added support for secure routes

- docs/RELEASE-NOTES.rst
**Description**: CIS 2.8.0 Release notes
> CIS 2.8.0 Release notes

- pkg/controller/backend.go
- pkg/controller/postManager.go
**Description**: Block incoming post requests on 201
- Fixed removing task Id from map and subsequently stop retries upon success  
**Fixes**:  internal CONTCNTR-3185
> Block incoming post requests on 201

- docs/upgradeProcess.md
**Description**:   Added the document for the upgrade process of CIS and IPAM
**Changes Proposed in PR**: Added the document for the upgrade process of CIS and IPAM
> CIS and IPAM Upgrade Document

- docs/config_examples/customResource/IngressLink/README.md
- docs/config_examples/customResource/IngressLink/cis-config/cis_rbac.yaml
**Description**:  For https://jira.pdsea.f5net.com/browse/CONTCNTR-3077 
**Changes Proposed in PR**: Updates cis_rbac.yaml and some edits to the README
> doc edits to IngressLink section

- go.mod
- go.sum
- pkg/controller/backend_test.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/postManager.go
- pkg/controller/postManager_test.go
- pkg/controller/profile_test.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/worker_test.go
- pkg/test/crd_utils.go
- vendor/modules.txt
> Add Unit tests for Native Controller

- pkg/controller/resourceConfig.go
**Description**:  Fix for re-encrypt routes processing
> Fix for re-encrypt routes processing

- docs/RELEASE-NOTES.rst
- pkg/appmanager/ingress.go
- pkg/appmanager/resourceConfig.go
**Description**:  Fix for changes on Ingress Resource Service Port not reflected on BIGIP
**Fixes**: resolves #2030
> Fix for changes on Ingress Resource Service Port not reflected on BIGIP

- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Updating Status of all VS, TS CRDs properly when multiple resources are added simultaneously
Test Image: nandakishoref5/k8s-bigip-ctlr:VStatus_fv3
**Fixes**: resolves #2220
> Updating Status of all VS,TS CRDs when multiple resources are added simultaneously

- pkg/controller/constants.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
**Description**:  Fix to ensure correct partition in used in iRule
**Changes Proposed in PR**: Fix to ensure correct partition in used in iRule
> Fix to ensure correct partition in used in iRule

- pkg/controller/nativeResourceWorker.go
> Fix Route delete issue

- pkg/controller/informers.go
- pkg/controller/nativeResourceWorker.go
> Fix watch all namespaces and informers issue

- cmd/k8s-bigip-ctlr/pythonDriver.go
Fix issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/2164
The idea is enlarging the scanner buffer to double when the scanner fails to handle the large log message(with `ErrTooLong` reported).
**Fixes**: resolves #2164
> Fix issue 2164 debug log level issue.

- pkg/agent/as3/as3ConfigMap.go
**Description**:  CM error message Modified for readability
**Fixes**: resolves #2209
> CM error message Modified for readability

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Fix iapp continuous updates with no backend pods
> Fix iapp continuous updates with no backend pods

- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Updating Status of all VS/TS CRDs
Similiar PR in master: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2330
> Updating Status of all VS/TS CRDs

- pkg/controller/constants.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
> Add Route Admit Status

- docs/RELEASE-NOTES.rst
- requirements.txt
**Description**:  Fix for issue 2205
**Changes Proposed in PR**: Fix for deleting multiple EDNS resources
**Fixes**: resolves #2205
> Fix for deleting multiple EDNS Resources

- pkg/controller/constants.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
> Refactor Route and pool member handling

- pkg/controller/resourceConfig.go
**Description**:  Fix for correct partition in https redirect iRule
> Fix for correct partition in https redirect iRule

- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Restoration after posting bad EDNS
**Changes Proposed in PR**: Restoration after posting bad EDNS
> Restoration after bad EDNS

- pkg/controller/informers.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
> Stabilise Local Configmap and resources

- docs/config_examples/customResource/CustomResource.md
- docs/config_examples/customResourceDefinitions/crd_update.md
**Description**:  Updating CRD documentation
- new upgrade document
> Updating CRD documentation

- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Manager.go
- pkg/appmanager/appManager.go
- pkg/vxlan/vxlanMgr.go
Performance improvement for as3 body validation.
This PR use `AS3Manager.as3Validated` to check the provided template already validated or not.
"Trade space for time".
**Fixes**: 
No issue ID, but performance related.
Related PRs
#2194 
#2292
> Avoid duplicate as3 body validation.

- config/apis/cis/v1/types.go
- config/apis/cis/v1/zz_generated.deepcopy.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/TransportServer/tcp-transport-server.yaml
- docs/config_examples/customResource/TransportServer/ts-with-hostname.yaml
- docs/config_examples/customResource/TransportServer/ts-with-service-address.yaml
- docs/config_examples/customResource/TransportServer/udp-transport-server.yaml
- docs/config_examples/customResource/VirtualServer/LoadBalancingMethod/README.md
- docs/config_examples/customResource/VirtualServer/LoadBalancingMethod/vs-with-loadBalancingMethod.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  LoadBalancingMethod support for VirtualServer and TransportServer CRs.
**Fixes**: resolves #2224
> LoadBalancingMethod support for VS,TS CRs

- docs/config_examples/nativeResources/README.md
**Description**: Doc update for NextGen Controller
> Doc update for NextGen Controller

- Makefile
- build-tools/crdcodegen.Dockerfile
> Add CRD code autogen support

- pkg/controller/controller.go
- pkg/controller/controller_suit_test.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**: Added fix for proper route admit status
**Changes Proposed in PR**: Added support for route admit status for rejected routes and also fixed the logic for updating the route admit status.
> Added fix for proper route admit status

- pkg/controller/constants.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/node_poll_handler.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Include event type in resource queue
- Included type of triggered event resource queue
- Perf improvements will be part of another PR.
**Fixes**: internal CONTCNTR-3250
> Include event type in resource queue

- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/IngressLink/README.md
**Description**:  Fixed file and examples links in ingresslink document
**Fixes**: resolves #2323
> Fixed file and examples links in ingresslink document

- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
> Improve performance during initialization

- docs/config_examples/customResource/CustomResource.md
**Description**: Updating the CRD ReadMe file
> Updating the CRD ReadMe file

- pkg/controller/nativeResourceWorker.go
**Description**:  Editing error log for local ConfigMap
**Changes Proposed in PR**: Editing error log for local ConfigMap
> Editing error log for local ConfigMap

- docs/RELEASE-NOTES.rst
- pkg/controller/backend.go
**Description**:  Added support for SCTP protocol in Services of type LoadBalancer
**Changes Proposed in PR**: Added support for SCTP protocol in Services of type LoadBalancer
> Added support for SCTP protocol in Services of type LoadBalancer

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/sample-policy.yaml
- docs/config_examples/customResource/TransportServer/tcp-transport-server-mode-performance.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  ProfileL4 Support for TS and Policy CR
> ProfileL4 Support for TS and Policy CR

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
- pkg/controller/backend.go
- pkg/controller/responseHandler.go
- pkg/controller/worker.go
- pkg/resource/types.go
**Description**: Fix for copy of iRuleMutex lock
> Fix for copy of iRuleMutex lock

- docs/RELEASE-NOTES.rst
- pkg/appmanager/appManager.go
**Description**: Fix for adding unique pool members only to as3 declaration with as3 configmap
**Fixes**: resolves #2151
> Fix for adding unique pool members only to as3 declaration

- cmd/k8s-bigip-ctlr/main.go
- docs/RELEASE-NOTES.rst
- pkg/agent/as3/as3ConfigMap.go
- pkg/agent/as3/as3Manager.go
- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
- pkg/controller/worker.go
- pkg/resource/types.go
**Description**:  Add NPL support for configmap
**Fixes**: resolves #2326
> Add NPL support for configmap

- azure-pipelines.yaml
- pkg/controller/backend.go
**Description**:  Making make verify as mandatory to merge the code
> Making make verify as mandatory to merge the code

- docs/config_examples/nativeResources/README.md
- pkg/appmanager/appManager_test.go
- pkg/appmanager/validateResources.go
- pkg/controller/backend.go
- pkg/resource/types.go
> fix unit tc

- pkg/appmanager/appManager.go
- pkg/appmanager/appManager_test.go
- pkg/appmanager/validateResources.go
- pkg/controller/informers.go
- pkg/controller/worker_test.go
**Description**:  exclude core service pods from NPL processing
> exclude core service pods from NPL processing

- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
> Fix multiple extended Route Specs update issue

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/sample-policy.yaml
- docs/config_examples/customResource/Policy/transportserver-with-policy.yaml
- docs/config_examples/customResource/Policy/virtualserver-with-policy.yaml
- docs/config_examples/customResource/TransportServer/tcp-transport-server.yaml
- docs/config_examples/customResource/TransportServer/udp-transport-server.yaml
- docs/config_examples/customResource/VirtualServer/BotDefense/README.md
- docs/config_examples/customResource/VirtualServer/BotDefense/vs-with-profileBotDefense.yaml
- docs/config_examples/customResource/VirtualServer/DOS/README.md
- docs/config_examples/customResource/VirtualServer/DOS/vs-with-profileDoS.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  Support for Dos Protection Profile and Bot Defense Profile
> Support for Dos Protection Profile and Bot Defense Profile

- pkg/appmanager/appManager.go
- pkg/controller/controller.go
- pkg/controller/types.go
**Description**:  Fixed the code for endpoint processing
> Fixed the code for endpoint processing

- docs/RELEASE-NOTES.rst
- pkg/appmanager/agentResponseHandler.go
- pkg/appmanager/appManager.go
- pkg/appmanager/validateResources.go
- pkg/controller/controller.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/types.go
- pkg/test/utils.go
**Description**: Added fix for proper route admit status
**Changes Proposed in PR**: Added support for route admit status for rejected routes and also fixed the logic for updating the route admit status.
> Added support for route admit status for rejected routes

- pkg/controller/backend.go
- pkg/controller/responseHandler.go
- pkg/controller/types.go
- Multi-partition support for updating resource status
- handles retried tenant cases
**Fixes**: resolves CONTCNTR-3350
> Multi-partition support for updating resource status

- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**: Performance improvement while processing endpoint events
- maintain service to resource name map for VS, TS, IngressLink, ServiceTypeLB resources
- Handles create, update and delete events. When a CRD pool backend service is updated, we initiate a delete + create event.
> Performance improvement while processing endpoint events

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/sample-policy.yaml
- docs/config_examples/customResource/TransportServer/tcp-transport-server.yaml
- docs/config_examples/customResource/VirtualServer/Profiles/TCP/README.md
- docs/config_examples/customResource/VirtualServer/Profiles/TCP/vs-with-profileTCP.yaml
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- docs/upgradeProcess.md
- pkg/controller/backend.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker_test.go
**Description**:  TCP Client and Server profile support added for VirtualServer, TransportServer and Policy CRs
> TCP Client and Server profile support added for VirtualServer, TransportServer and Policy CRs

- docs/RELEASE-NOTES.rst
- pkg/controller/worker.go
**Description**:   Fix for service with named ports and NAT ports with service TypeLB and NodePort
**Changes Proposed in PR**: Fix for service with named ports and NAT ports with service TypeLB and NodePort
**Fixes**: resolves #2294
> fix for service with named ports

- pkg/controller/informers.go
- pkg/controller/informers_test.go
**Description**:  Fixed the issue of virtual server CR not getting processed on update
**Changes Proposed in PR**:  Fixed the issue of virtual server CR not getting processed on update
> Fixed the issue of virtual server CR not getting processed on update

- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
**Description**:  Extended support for snat in policy for VS and TS
**Changes Proposed in PR**: Extended support for snat in policy for VS and TS
> Extended support for snat in policy for VS and TS

- pkg/controller/resourceConfig.go
- requirements.txt
**Description**:  Fix EDNS processing
> Fix EDNS processing

- pkg/appmanager/appManager.go
> Fix Cluster mode Endpoints issue for Hubmode configmap

- Makefile
- build-tools/Dockerfile.debug
> Add new dbg tag for debug build image

- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**: Fixed issue with deletion if incorrect virtual server with custom port.
**Changes Proposed in PR**: Fixed issue with deletion if incorrect virtual server with custom port.
> Wrong virtual deletion fix

- pkg/controller/nativeResourceWorker.go
**Description**:  Fix VS update issue
- handle delete event
> Fix VS update issue

- pkg/controller/worker_test.go
**Description**:  UT to handle Readding VS
> UT to handle Re-adding VS

- pkg/appmanager/appManager.go
- pkg/controller/informers.go
- pkg/controller/nativeResourceWorker.go
**Description**: Fix for map update when route is deleted
> Fix for map update when route is deleted

- pkg/controller/worker.go
Reverts F5Networks/k8s-bigip-ctlr#2437
> Revert "Handling VS Delete event."

- pkg/controller/worker.go
**Description**:  Handling VS Delete Event
> Handling VS Delete Event

- pkg/controller/worker.go
- pkg/controller/worker_test.go
**Description**: Fixed Ingresslink deletion issue
**Changes Proposed in PR**: Fixed Ingresslink deletion issue
> Fixed Ingresslink deletion issue

- pkg/controller/worker.go
**Description**:  Fix for Endpoint processing issue for serviceLB
**Changes Proposed in PR**: Fix for Endpoint processing issue for serviceLB
> Fix for Endpoint processing issue for serviceLB

- docs/RELEASE-NOTES.rst
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Fix for different service Port and target port with CRs
> Fix for different service Port and target port with CRs

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/teem/teem.go
- pkg/teem/teem_test.go
**Description**:  teems support for nativeResources
**Changes Proposed in PR**: teems support for nativeResources
> teems support for nativeResources

- docs/RELEASE-NOTES.rst
- helm-charts/f5-bigip-ctlr/Chart.yaml
- helm-charts/f5-bigip-ctlr/README.md
- helm-charts/f5-bigip-ctlr/values.yaml
**Description**: Fix for inconsistent use of value in helm chart
**Fixes**: resolves #2387
> Fix for inconsistent use of value in helm chart

- pkg/controller/backend.go
**Description**: Removed AS3 declaration printing in logs
> Removed AS3 declaration printing in logs

- pkg/controller/backend.go
> Fix invalid removal of primary partition

- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
> Fix PoolName issue while frame policy rules

- pkg/appmanager/validateResources.go
- pkg/controller/worker.go
**Description**:  Moving NPL log to debug.
**Fixes**: resolves #2457
> Move log to debug

- azure-pipelines.yaml
- build-tools/helm-clusterrole-gen.py
- build-tools/py-requirements.txt
**Changes Proposed in PR**: Done pipeline integration to generate yaml 
> Helm clusterrole - Azure Pipeline Integration

- requirements.txt
**Description**: Updating the f5-cccl repo and f5-ctlr-agent repo
> Updating the f5-cccl repo and f5-ctlr-agent repo

- pkg/agent/as3/as3Common.go
- pkg/agent/as3/as3Manager.go
- pkg/agent/as3/as3Resource.go
- pkg/appmanager/agentRequestHandler.go
- pkg/appmanager/appManager.go
- pkg/vlogger/log.go
- pkg/vxlan/vxlanMgr.go
This PR is used to calculate function level execution time.
Effects:
```
2022/01/24 06:58:49 [DEBUG] /root/workspace/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/agent/as3/as3Resource.go 28 github.com/F5Networks/k8s-bigip-ctlr/pkg/agent/as3.(*AS3Manager).prepareAS3ResourceConfig (0 ms): 
2022/01/24 06:58:53 [INFO] github.com/F5Networks/k8s-bigip-ctlr/pkg/agent/as3.(*AS3Manager).postAS3Declaration (3961 ms): 
```
Refer to `Timeit` function.
**Fixes**: 
No issue ID but performance related.
> Add Timeit function for timecost calculations.

- pkg/agent/as3/as3Manager.go
**Description**:  Fixed ARP entries cleanup issue after resource deletion with tenant filtering enabled
**Changes Proposed in PR**: Fixed ARP entries cleanup issue after resource deletion with tenant filtering enabled
> Fixed ARP entries cleanup issue after resource deletion with tenant filtering enabled

- helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
**Description**:  Fix securityContext block for helm
> Fix securityContext block for helm 

- helm-charts/f5-bigip-ctlr/values.yaml
**Description**:  Update links in helm values.yaml documentation
- Update links in helm values.yaml documentation 
**Fixes**: resolves #2433
> Update links in helm values.yaml documentation

- docs/RELEASE-NOTES.rst
- helm-charts/f5-bigip-ctlr/Chart.yaml
**Description**:  Updating the charts version for next release
> Updating the charts version for next release

- helm-charts/f5-bigip-ctlr/values.yaml
**Description**:  Helm install values.yaml results in a bad image format
**Changes Proposed in PR**: enabled version parameter in values.yaml 
**Fixes**: resolves #2434
> enabled version parameter and set to default value - latest in values.yaml

- docs/config_examples/as3-api-reference.md
**Description**:  AS3 API useful for CIS
> AS3 API reference

- pkg/controller/resourceConfig.go
**Description**:  Fix WildCard Domain Support
> Fix WildCard Domain Support

- pkg/controller/worker.go
> Fix VS update/delete issue with IPAM Processing

- docs/RELEASE-NOTES.rst
- docs/upgradeProcess.md
**Description**:  CIS 2.9.1 Release Notes
> CIS 2.9.1 Release Notes

- azure-pipelines.yaml
**Description**:  Fixing the version for docker and redhat repo
> Fixing the version for docker and redhat repo

- pkg/teem/teem.go
**Description**:  Data sent by teems is stopped along with retries in case of network failure
> Data sent by teems is stopped in case of network failure

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/CustomResource.md
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
**Description**:  Alias Port support in monitor
**Fixes**: resolves #2361
> Alias Port support in monitor

- config/apis/cis/v1/types.go
- docs/RELEASE-NOTES.rst
- docs/config_examples/customResource/Policy/sample-policy.yaml
- docs/config_examples/customResource/VirtualServer/allowSourceRange/README.md
- docs/config_examples/customResource/VirtualServer/allowSourceRange/vs-with-allowSourceRange
- docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
- pkg/controller/backend.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/resourceConfig.go
- pkg/controller/routing.go
- pkg/controller/types.go
**Description**:  Added support for the AllowSourceRange feature in  VS CR and Policy CR but is only applicable to VS CR.
> AllowSourceRange support for VS CR

- pkg/teem/teem.go
**Description**:  Added locks for teems data
**Fixes**: resolves #2509
> Added locks for teems data

- docs/RELEASE-NOTES.rst
- docs/config_examples/nativeResources/README.md
- docs/config_examples/nativeResources/configmap/extendedRouteConfigWithNamespaceLabel.yaml
- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig.go
- pkg/controller/types.go
- pkg/controller/worker.go
**Description**:  Added support for namespace-label in nextGen routes
> Added support for namespace-label in nextGen routes

- Makefile
- pkg/controller/backend.go
- pkg/controller/controller.go
- pkg/controller/resourceConfig.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/routing.go
- pkg/controller/types.go
**Description**:  irule changes to support AllowSourceRange in VS CR
> irule changes to support AllowSourceRange in VS CR

- pkg/controller/controller.go
- pkg/controller/informers.go
- pkg/controller/informers_test.go
- pkg/controller/nativeResourceWorker.go
- pkg/controller/nativeResourceWorker_test.go
- pkg/controller/resourceConfig_test.go
- pkg/controller/types.go
- pkg/controller/worker.go
- pkg/controller/worker_test.go
> Added support for namespace-label informers

- pkg/agent/as3/as3Manager.go
**Description**:  Updating the As3 schema version
> Updating the As3 schema version

- docs/RELEASE-NOTES.rst
- docs/config_examples/next-gen-routes/README.md
**Description**:  Fix doc links
> Fix doc links

- cmd/k8s-bigip-ctlr/main.go
- pkg/controller/backend.go
- pkg/controller/types.go
**Description**:  Skip starting Python Driver in NodePort and AS3 Mode
> Skip starting Python Driver in NodePort Mode and Agent AS3
