F5Networks/k8s-bigip-ctlr

pkg/vxlan/vxlanMgr.go

**Description**:  Adding Emtpy ARP Block For cilium in case of CRDs

Add Emtpy ARP Block For cilium in case of CRDs

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/backend.go
pkg/controller/types.go

Reverts F5Networks/k8s-bigip-ctlr#2530

Revert "Skip starting Python Driver in NodePort Mode and Agent AS3"

---

pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/appmanager/ingress_test.go
pkg/appmanager/profiles_test.go
pkg/resource/types.go

**Description**:  Update poolmembers in nodeport mode only when there's node update

Update poolmembers in nodeport mode only when there's node update

---

docs/config_examples/next-gen-routes/README.md
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/controller_suit_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/postManager.go
pkg/controller/postManager_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**: Added support for tenant priorities

Add support for AS3 tenant priorities

---

docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfig.yaml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/profile.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go

**Description**:  Add base config block for TLScipher for NextGen Routes

Add base config block for TLSCipher for NextGen Routes

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServer/virtual-with-pool-svc-different-ns/vs-with-pool-svc-diff-ns.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/worker.go

**Description**:   VirtualServer pool service from different namespace
**Changes Proposed in PR**: Added namespace field to Pool.
**Fixes**: resolves #1933

VirtualServer pool service from different namespace

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/monitors-transport-server.yaml
docs/config_examples/customResource/VirtualServer/HealthMonitor/monitors-virtual-server.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**: Add TCP health Monitor for VS CR and Monitors support for VS and TS CRs

Add TCP health Monitor for VS CR and Monitors support for VS and TS CRs

---

docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/worker.go

**Description**:   CRD schema update
**Fixes**: resolves #2413

schema update

---

pkg/controller/backend.go

**Description**:  Currently, when AS3 returns 422 we keep retrying every 30s for failed tenants. So even if config is updated to correct reference, currently CIS not processing the new update.
422 Unprocessable Entity response status code indicates invalid config.Client should not repeat this request without modification.So remove the tenant config from retry map.

Remove invalid config from retry tenant map

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/routes/route-with-load-balance.yaml
pkg/controller/informers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig_test.go

**Description**:  Add support for Load Balancing feature in nextGen Routes

Add support for Load Balancing feature in nextGen Routes for Pools

---

docs/RELEASE-NOTES.rst
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  VS CR HealthMonitor Name Format Change , Appending DomainName and Path instead of HM Send string
**Fixes**: resolves #2507

VS CR HealthMonitor Name Format Change

---

pkg/controller/resourceConfig.go

**Description**:  Remove extra underscore from CRD HM Name

Remove extra underscore from CRD HM Name

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithAllowSourceRange.yaml
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:  Add support for AllowSourceRange in NextGen Routes

Add support for AllowSourceRange in NextGen Routes

---

build-tools/Dockerfile.ubi

**Description**:  Add UBI 8 Support

Add UBI 8 Support

---

docs/RELEASE-NOTES.rst
pkg/resource/resourceConfig.go
pkg/resource/resourceConfig_test.go

**Description**:  Fix Crash due to Route Profiles
**Changes Proposed in PR**:  Ensured safe concurrent usage of RouteProfs map.
**Fixes**: resolves #2345

Fix Crash due to Route Profiles

---

pkg/controller/backend.go
pkg/controller/backend_test.go

Remove AS3 based GTM

---

docs/RELEASE-NOTES.rst
f5-bigip-ctlr-operator/Dockerfile
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
f5-bigip-ctlr-operator/bundle/metadata/annotations.yaml

**Description**:  Add support openshift operator in openshift v4.10
**Fixes**: resolves #2543

Add support openshift operator in openshift v4.10

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/appmanager/ingress.go
pkg/appmanager/ingress_test.go

**Description**:  Fix CIS continuous processing of ingress belonging to unmanaged ingress class
**Changes Proposed in PR**: Skip processing ingress belonging to unmanaged ingress class

Fix CIS continuous processing of ingress belonging to unmanaged ingress class

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/README.md
docs/config_examples/customResource/TransportServer/sctp-transport-server.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/validate.go

**Description**:  Add SCTP support for Transport Server Custom Resource

Add SCTP support for Transport Server Custom Resource

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/routes/sample-route-ab.yaml
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/types.go

Add AB Deployment support for NextGen Routes

---

pkg/controller/controller.go

**Description**: Enable share nodes with multi-partition support only

Enable share nodes with multi-partition support only

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/backend.go
pkg/controller/controller.go

**Description**:  Fixes the intermittent issue of AS3 version

Fixes the intermittent issue of AS3 version

---

pkg/controller/backend.go

**Description**:  Retry posting after 422

Retry posting after 422

---

pkg/controller/controller.go

**Description**:  crd ns informer fix

crd ns informer fix

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

**Description**:  Fix trafficGroup regex
**Changes Proposed in PR**: Updated trafficGroup regex pattern in CR schema.
**Fixes**: resolves #2549

Fix trafficGroup regex

---

build-tools/Dockerfile.ubi
pkg/controller/informers.go

**Description**: Print only RouteName in DebugMode

Print only RouteName in DebugMode

---

docs/RELEASE-NOTES.rst
pkg/controller/resourceConfig.go
pkg/controller/routing.go

Fix poolname inconsistency issue for VS

---

docs/config_examples/next-gen-routes/routes/path-rewrite.yaml
docs/config_examples/next-gen-routes/routes/sample-route-ab.yaml
docs/config_examples/next-gen-routes/routes/simple-insecure-route.yaml
docs/config_examples/routes/sample-custom-ssl-profile.yaml
docs/config_examples/routes/sample-edge-route.yaml
docs/config_examples/routes/sample-passthrough-route.yaml
docs/config_examples/routes/sample-reencrypt-route.yaml
docs/config_examples/routes/sample-route-ab.yaml
docs/config_examples/routes/sample-route-balance.yaml
docs/config_examples/routes/sample-route-basic.yaml
docs/config_examples/routes/sample-route-edge-ssl-waf.yaml
docs/config_examples/routes/sample-route-waf.yaml
docs/config_examples/routes/sample-unsecured-route.yaml

**Description**:  Update apiVersion of Route Resource

Update apiVersion of Route Resource

---

docs/RELEASE-NOTES.rst
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**: Fix for TLSProfile doesn't get updated when K8s secret changes
**Fixes**: resolves #2570

Fix for TLSProfile doesn't get updated when K8s secret changes

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go

**Description**: Fix for invalid property name with serviceAddress
**Fixes**: resolves #2596

Fix for invalid property name with serviceAddress

---

pkg/controller/resourceConfig.go
pkg/controller/worker.go

**Description**:  Fix svcPort support
**Fixes**: resolves #2582 resoves #2253

Fix svcPort support

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

Converge GTM and LTM config to same partition

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServer/virtual-with-hostGroup/README.md
docs/config_examples/customResource/VirtualServer/virtual-with-hostGroup/hostgroup-ns-support.yaml
pkg/controller/worker.go

**Description**:  Support for grouping vs by hg across namespaces
**Fixes**: resolves #2469

Support for grouping vs by hg across namespaces

---

pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**:  Handled processing of custom resources in OpenShift mode

Handled processing of custom resources in openshift mode

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/routes/route-path-based-ab-deploy.yaml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go

**Description**:  Support Path based A/B deployment for Re-encrypt termination
**Changes Proposed in PR**: Added support for A/B deploy in NextGen for Re-encrypt termination

Support Path based A/B deployment for Re-encrypt termination

---

pkg/controller/responseHandler.go

**Description**:  Fix CIS crash when service associated with VS is deleted.
**Changes Proposed in PR**: Handled nil pointer dereference error.

Fix CIS crash when service for VS is removed

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  targetport support for string values in NPL mode
**Fixes**: resolves #2609

Named targetport support for NPL

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add Support for CCCL and AS3 GTM Agent

Add Support for CCCL and AS3 GTM Agent

---

docs/RELEASE-NOTES.rst
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go

**Description**:  Process ingressLink on k8s node update
**Changes Proposed in PR**: Process ingressLink on k8s node update
**Fixes**: resolves #2626

Process ingressLink on k8s node update

---

build-tools/Dockerfile.ubi

**Description**:  Fix for build failure
**Changes Proposed in PR**: Removed the package reference which are not installed in UBI anymore

Fix for build failure

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/sample-policy.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go

**Description**:  allowVlans support with policy CR

allowVlans support with policy CR

---

pkg/controller/informers.go
pkg/controller/worker.go

**Description**:  code cleanup

code cleanup

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
pkg/controller/controller_suit_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  GSLB support for routes
**Changes Proposed in PR**: Support for GSLB in NextGen routes

GSLB support for routes

---

pkg/agent/as3/as3Common.go
pkg/agent/as3/as3Types.go

**Description**:  Add support for recv property in https monitor

Add support for recv property in https monitor

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/ts-with-nodeMemberLabel.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

**Description**: Support for nodeMemberLabel in Transport Server pool
**Fixes**: resolves #2420

Support for nodeMemberLabel in Transport Server pool

---

pkg/controller/worker_test.go

**Description**:  Added unit test cases for updatePoolMembersForNodePort function

Added unit test cases for updatePoolMembersForNodePort function

---

docs/RELEASE-NOTES.rst
docs/config_examples/ingress/networkingV1/ingress-with-translate-address.yaml
pkg/agent/as3/as3Common.go
pkg/agent/as3/as3Types.go
pkg/appmanager/appManager.go
pkg/appmanager/ingress.go
pkg/appmanager/ingress_test.go
pkg/resource/resourceConfig.go
pkg/resource/types.go
requirements.txt

**Description**:  Add support to set Address Translation flag from ingress annotation

Add support to set Address Translation flag from ingress annotation

---

pkg/resource/types.go

**Description**:Fix translateAddress property for configmap

Fix translateAddress property for configmap

---

cmd/k8s-bigip-ctlr/main.go

**Description**:  Modify Naming Convention for ccclGTMAgent parameter

Modify naming convention for ccclGTMAgent parameter

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md

**Description**:  Add example for GSLB NextGen routes
**Changes Proposed in PR**: Add example for GSLB NextGen routes

Add example for GSLB NextGen routes

---

README.md
docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfig.yaml
docs/config_examples/next-gen-routes/migration-guide.md

**Description**:  Release 2.11.0

Release 2.11.0

---

pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/types.go

**Description**:  Support None value for Persistence Profile

Support None value for Persistence Profile

---

docs/config_examples/next-gen-routes/README.md
pkg/controller/nativeResourceWorker.go

**Description**:  Fix for configMap processing when cis starts

Fix for configMap processing when cis starts

---

pkg/controller/contstants.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:   default routeGroup support added to help legacy route migration to nextgen routes.

default routeGroup support

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/VirtualServer/HealthMonitor/monitors-virtual-server.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/upgradeProcess.md

**Description**:  Fix CRD schema parameter inputs to allow 'hypen'
**Fixes**: resolves #2657

Fix CRD schema parameter inputs

---

docs/config_examples/next-gen-routes/configmap/extendedRouteConfig.yaml
docs/config_examples/next-gen-routes/configmap/extendedRouteConfigWithNamespaceLabel.yaml
docs/config_examples/next-gen-routes/configmap/extendedRouteConfigwithBaseConfig.yaml
docs/config_examples/next-gen-routes/routes/path-rewrite.yaml
docs/config_examples/next-gen-routes/routes/simple-insecure-route.yaml

docs update

---

cmd/k8s-bigip-ctlr/main_test.go
pkg/controller/controller_suit_test.go
pkg/controller/informers_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/pythonDriver_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Add Unit Test cases for Code Coverage

Add Unit Test cases for Code Coverage

---

build-tools/Dockerfile.ubi
docs/RELEASE-NOTES.rst

**Description**: Upgrading base image to UBI9 & Python39

Upgrading base image to UBI9 & Python39

---

docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

**Description**:  Schema Pattern Fix

Schema Pattern Fix

---

pkg/resource/resourceConfig_test.go
pkg/test/utils.go

**Description**:  Add UnitTests for Resource Pkg

Add UnitTests for Resource Pkg

---

pkg/agent/agentAS3_test.go
pkg/agent/agentCCCL_test.go
pkg/agent/agent_suit_test.go
pkg/agent/as3/as3ConfigMap.go
pkg/agent/as3/as3Manager.go
pkg/agent/as3/as3Manager_test.go
pkg/agent/as3/as3Resource_test.go
pkg/agent/as3/l2l3agent.go
pkg/agent/as3/postManager.go
pkg/agent/as3/postManager_test.go
pkg/test/configs/as3_multi_cm_unified_nodeport_local.json
pkg/test/utils.go

**Description**:  Adding unit tests for agent & as3 package

Adding unit tests for agent & as3 package

---

pkg/agent/as3/as3Common.go
pkg/agent/as3/as3Resource.go
pkg/agent/as3/as3Utils.go
pkg/appmanager/agentResponseHandler_test.go
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/appmanager/healthMonitors_test.go
pkg/appmanager/ingress_test.go
pkg/appmanager/profiles_test.go
pkg/appmanager/validateResources.go
pkg/appmanager/validateResources_test.go
pkg/controller/controller.go
pkg/controller/resourceConfig.go
pkg/controller/worker.go
pkg/health/health.go
pkg/prometheus/prometheus.go
pkg/resource/resourceConfig_test.go
pkg/test/utils.go
pkg/vlogger/doc.go
pkg/vlogger/log.go
pkg/vlogger/log_null.go
pkg/vlogger/logger.go

**Description**:  Add UnitTests for Appmanager pkg

Add UnitTests for Appmanager pkg

---

docs/RELEASE-NOTES.rst
docs/user_guides/README.md

**Description**:  Add UserGuides 

Add UserGuides 

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
pkg/agent/as3/as3Utils.go
pkg/agent/as3/postManager_test.go
pkg/appmanager/appManager_test.go
pkg/appmanager/ingress_test.go
pkg/appmanager/routing.go
pkg/appmanager/validateResources_test.go
pkg/controller/worker_test.go

**Description**:  Adding unit tests

Adding unit tests

---

docs/upgradeProcess.md

**Description**:  Add CIS UBI Versions

Add CIS UBI Versions

---

pkg/appmanager/appManager_test.go
pkg/appmanager/ingress_test.go
pkg/controller/controller_suit_test.go
pkg/controller/node_poll_handler_test.go

**Description**:   unit tc for node informer

ut for node informer

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServer/HttpMrfRoutingEnabled/vs-with-mrfrouting-enabled.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:   Support for HttpMrfRoutingEnabled with virtualserver crd.
**Fixes**: resolves #2682

Support for HttpMrfRoutingEnabled with vs

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/sample-policy.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:  Support for ipIntelligencePolicy with policy CR

Add support for ipIntelligencePolicy with policy CR

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/routes/sample-route-rewrite-app-root.yaml
pkg/controller/constants.go
pkg/controller/contstants.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go

**Description**:  Add Support for rewrite-app-root annotation in routes

Add Support for rewrite-app-root annotation in routes

---

docs/RELEASE-NOTES.rst
pkg/controller/resourceConfig.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Support host group having multiple hosts with EDNS
**Changes Proposed in PR**: Support host group having multiple hosts with EDNS
**Fixes**: resolves #2703

Support host group having multiple hosts with EDNS

---

docs/RELEASE-NOTES.rst
pkg/appmanager/ingress.go
pkg/appmanager/resourceConfig.go

**Description**:  Add wildcard character validation for ingress path

Add wildcard character validation for ingress path

---

pkg/appmanager/ingress.go
pkg/appmanager/resourceConfig.go
pkg/appmanager/validateResources.go

**Description**:  Add ingress name in error logs

Add ingress name in error logs

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/routes/sample-route-with-waf-annotation.yaml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/routing.go
pkg/controller/types.go

**Description**:  Add WAF annotation support for NextGenRoutes
**Changes Proposed in PR**:  Add WAF annotation support for NextGenRoutes

Add WAF annotation support for NextGenRoutes

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/serviceNamespace/README.md
docs/config_examples/customResource/TransportServer/serviceNamespace/ts-with-serviceNamespace.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/worker.go

**Description**: Add support for serviceNamespace in transport server
**Fixes**: resolves #2737

Add support for serviceNamespace in transport server

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/ts-with-named-port.yaml
docs/config_examples/customResource/VirtualServer/virtual-with-named-port/README.md
docs/config_examples/customResource/VirtualServer/virtual-with-named-port/sample-deployment.yaml
docs/config_examples/customResource/VirtualServer/virtual-with-named-port/sample-service.yaml
docs/config_examples/customResource/VirtualServer/virtual-with-named-port/virtual-with-service-port-name.yaml
docs/config_examples/customResource/VirtualServer/virtual-with-named-port/virtual-with-target-port-name.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:   Add named port support for vs, ts resources
**Fixes**: resolves #2729

named port support for CRD

---

helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-ingress-class.yaml

**Description**: Fix for ingressClass name in helm chart

Fix for ingressClass name in helm chart

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/controller/node_poll_handler.go

**Description**:  Fix prometheus metrics broken in v2.11.1
**Fixes**: resolves #2726

Fix prometheus metrics broken in v2.11.1

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/routes/sample-route-with-allow-source-range.yaml
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go

**Description**:  Add Allow source range annotation support for NextGenRoutes
**Changes Proposed in PR**: Add Allow source range annotation support for NextGenRoutes

Add Allow source range annotation support for NextGenRoutes

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServer/HostRewrite/README.md
docs/config_examples/customResource/VirtualServer/HostRewrite/virtual-server.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/routing.go
pkg/controller/worker_test.go

**Description**:  Support for Host header rewrite in VirtualServer CR
**Fixes**: resolves #2744

Support for Host header rewrite in VirtualServer CR

---

docs/config_examples/customResource/CustomResource.md

**Description**: Updating the virtual Server documentation

Updating the virtual Server documentation

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/routes/route-with-target-port-health-monitor.yaml
pkg/controller/nativeResourceWorker.go

**Description**:  Support for targetPort in route's health monitors

Support for targetPort in route's health monitors

---

pkg/controller/worker.go

**Description**:  fix named target port with nodeport

fix named target port nodeport

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/VirtualServer/pool-waf/README.md
docs/config_examples/customResource/VirtualServer/pool-waf/vs-with-waf-based-pool.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/nativeResourceWorker.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Support Pool Based WAF for VS CR
**Fixes**: resolves #2752

Support Pool Based WAF for VS CR

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/ExternalDNS/externaldns-pool-ratio.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  support to configure ratio on GSLB pool

support to configure ratio on GSLB pool

---

docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/migration-guide.md

**Description**:  Update NextGen Controller Documenation for GA

Update NextGen Controller Documenation

---

docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/migration-guide.md

**Description**:  Add NextGen Migration Tool

Add NextGen Migration Tool

---

docs/RELEASE-NOTES.rst
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go

**Description**: Fix wrong pool member port configured
**Fixes**: resolves #2767

Fix wrong pool member port configured

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/policy-with-iRules-none.yaml
docs/config_examples/customResource/VirtualServer/iRules/README.md
docs/config_examples/customResource/VirtualServer/iRules/vs-with-iRules-none.yaml
docs/config_examples/customResource/VirtualServer/iRules/vs-with-iRules.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Support to eliminate adding iRules by default
**Fixes**: resolves #2764

Support to eliminate adding iRules by default

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/controller/pythonDriver.go
pkg/prometheus/prometheus.go

**Description**:  Fix for http client prometheus metrics

Fix for http client prometheus metrics

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go

**Description**:  ltm policy fix for default http and https port

ltm policy fix for controller mode

---

Makefile
build-tools/Dockerfile.debian
build-tools/rel-build.sh

**Description**:  Update Ginkgo version

Update Ginkgo version

---

build-tools/Dockerfile.debug

**Description**:  Update DockerFile.debug to golang 1.19

Update DockerFile.debug to golang 1.19

---

pkg/controller/worker.go

Fix host check go1.19

---

docs/config_examples/customResource/CustomResource.md
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/migration-guide.md

**Description**:  Update SSL precedence in NextGen

NextGen Doc update

---

pkg/controller/nativeResourceWorker_test.go
pkg/controller/routing.go

**Description**:  Sort policy rules in lexicographic order.
**Changes Proposed in PR**: Sort policy rules in lexicographic order.

Sort policy rules

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/routes/route-with-ab-waf.yaml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/types.go

**Description**:  WAF support with A/B routes
**Changes Proposed in PR**: Support given for waf with a/b routes 

WAF support with A/B routes

---

pkg/appmanager/agentResponseHandler.go

**Description**:  Fix unwatched namespace log
**Changes Proposed in PR**: Fix unwatched namespace log

Fix unwatched namespace log

---

pkg/controller/informers.go
pkg/controller/informers_test.go

**Description**:  Skip processing VS and TS on status update
**Changes Proposed in PR**: Skip processing VS and TS on status update.

Skip processing VS and TS on status update

---

docs/user_guides/README.md

**Description**:  Userguide for AWS BIGIP-HA multi az

Userguide for AWS BIGIP-HA multi az

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/resourceConfig.go

**Description**:  Support for referencing /Common/Shared objects with vs resource 
**Fixes**: resolves #2797 #2793

Support for referencing /Common/Shared objects with vs resource

---

pkg/appmanager/validateResources.go

**Description**:  fix host check legacy routes

fix host check legacy routes

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/informers_test.go
pkg/controller/postManager.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Handle all resource updates during AS3 post delay
**Changes Proposed in PR**:  Handle all resource updates during AS3 post delay and handled partition change bug.
**Fixes**: resolves #2789

Handle all resource updates during AS3 post delay

---

docs/RELEASE-NOTES.rst
pkg/controller/informers_test.go
pkg/controller/responseHandler.go
pkg/controller/worker.go

**Description**:  Support for ExternalIP update of associated services of Type LB in TS CR
**Changes Proposed in PR**: This PR contains following changes-
- Support for ExternalIP update of associated services of Type LB in TS CR
- CIS not processing the updates when serviceTypeLB is modified.
**Fixes**: resolves #2816

Support for ExternalIP update of associated services of Type LB in TS CR

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Fix EDNS not working when deployed before TS
**Changes Proposed in PR**: Fix EDNS not working when deployed before TS
**Fixes**: #2796

Fix EDNS not working when deployed before TS

---

pkg/appmanager/appManager.go

**Description**:  Fix multiple posts on init for legacy routes

Fix multiple posts on init for legacy routes

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  support new partition for gtm in as3 mode
**Changes Proposed in PR**: support new partition for gtm in as3 mode

support new partition for gtm in as3 mode

---

docs/config_examples/customResource/CustomResource.md
docs/upgradeProcess.md

**Description**:  edns doc changes and release notes #
**Changes Proposed in PR**: edns doc changes and release notes #

edns doc changes and release notes

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md

**Description**:  CIS Release 2.12.1

CIS Release 2.12.1

---

pkg/controller/responseHandler.go

**Description**: Fix for priority update of deleted partition

Fix for priority update of deleted partition

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/controller/informers.go
pkg/controller/worker.go

**Description**:  Skip processing oscp system services

Skip processing oscp system services

---

docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster.yaml
docs/config_examples/multicluster/kube-config-secret-example.yaml
pkg/clustermanager/clustermanager.go
pkg/clustermanager/types.go
pkg/controller/controller.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Handle multi cluster configs
**Changes Proposed in PR**: Handle multi cluster configs using Extended Configmap

Handle multi cluster configs

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/policy-with-multiple-irules.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/worker_test.go

**Description**:  policy CR support to configure multiple irules on http/htttps virtual on bigip

policy CR support to configure multiple irules

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/sample-policy.yaml
docs/config_examples/customResource/VirtualServer/http2/README.md
docs/config_examples/customResource/VirtualServer/http2/vs-with-profilehttp2.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/upgradeProcess.md
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Add Support of ServerSide HTTP2 Profile in Policy CR and VS CR

Add Support of ServerSide HTTP2 Profile in Policy CR and VS CR

---

docs/config_examples/next-gen-routes/README.md

**Description**:  Update nextGenRoute documentation
**Changes Proposed in PR**: Update nextGenRoute documentation

Update nextGenRoute documentation

---

pkg/controller/backend.go
pkg/controller/node_poll_handler.go
pkg/controller/types.go
requirements.txt

**Description**:  Fix to improper ARPs updation in config.json
**Changes Proposed in PR**: Skip ARPs updation in config.json If disableARP is set to true.

Fix to improper ARPs updation in config.json

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/policy-with-autoLastHop.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Add support for Auto Last Hop in NextGen
**Changes Proposed in PR**: Add support for Auto Last Hop in NextGen

Add support for Auto Last Hop in NextGen

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/policy-with-httpMrfRouter.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Add support for http mrf router in NextGen
**Changes Proposed in PR**: Add support for http mrf router in NextGen

Add support for http mrf router in NextGen

---

pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**:  Fix for processing route's multi-cluster annotation

Fix for processing route's multi-cluster annotation

---

pkg/controller/node_poll_handler.go

**Description**:  Fix for node update processing

Fix for node update processing

---

pkg/controller/nativeResourceWorker.go

**Description**:  Fix multicluster config cleanup
**Changes Proposed in PR**: Clean up all the multicluster related configs in CIS if multicluster configs are removed from GCM.

Fix multicluster config cleanup

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/virtual-with-alternatebackends/README.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/virtual-with-alternatebackends/edge-tls.yaml
docs/config_examples/customResource/VirtualServerWithTLSProfile/virtual-with-alternatebackends/virtual-with-ab.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add A/B support for virtual server

Add A/B support for virtual server

---

docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation.yaml
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Fix for service port update processing

Fix for service port update processing

---

pkg/appmanager/appManager.go
pkg/controller/constants.go
pkg/controller/node_poll_handler.go

https://github.com/F5Networks/k8s-bigip-ctlr/issues/2861
add Cilium node annotation detection in static route mode
**Fixes**: resolves #2861

Add Cilium CNI for static route mode

---

pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go

**Description**:  Fix for processing route without service

Fix for processing route without service

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go

**Description**:  Add support for additionalVirtualAddresses with serviceAddress config
**Fixes**: resolves #2821

Add support for additionalVirtualAddresses with serviceAddress config

---

requirements.txt

**Description**:  Handle StaticRoute Update incase of podCIDR udpate

Handle StaticRoute Update incase of podCIDR udpate

---

build-tools/Dockerfile.ubi
cmd/k8s-bigip-ctlr/main.go
docs/config_examples/multicluster/extendedConfigmap/global-config-with-primary-cluster-health-probe.yaml
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/postManager.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Liveness probe feature for Primary Cluster 

Liveness probe feature for Primary Cluster 

---

cmd/k8s-bigip-ctlr/main.go
docs/config_examples/multicluster/README.md
pkg/clustermanager/types.go
pkg/controller/controller.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Fix for monitoring services of HA cluster pair
**Changes Proposed in PR**: Fix for monitoring services of HA cluster pair

Fix for monitoring services of HA cluster pair

---

build-tools/Dockerfile.ubi
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/Policy/README.md

Documentation fixes

---

azure-pipelines.yaml
junit.tpl

**Description**:  Adding trivy scan for source code and container image

Adding trivy scan for container image

---

requirements.txt

**Description**:  Handle error handling while creating GTM HealthMonitors

Handle error handling while creating GTM HealthMonitors

---

pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/worker.go

**Description**:  Fix pool members issue when services are shared
**Changes Proposed in PR**: Fix pool members issue when services are shared

Fix pool members issue when services are shared

---

pkg/controller/worker.go

**Description**:  Handle pod processing error for external clusters
**Changes Proposed in PR**: Handle pod processing error for external clusters

Handle pod processing error for external clusters

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md

**Description**:  Updating the kubernetes support matrix

Updating the kubernetes support matrix

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  Fix hostless VS with IPAM to work with hostgroup
**Changes Proposed in PR**: Fix hostless VS with IPAM to work with hostgroup
**Fixes**: #2778

Fix hostless VS with IPAM to work with hostgroup

---

docs/RELEASE-NOTES.rst
pkg/appmanager/agentResponseHandler.go
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/controller/nativeResourceWorker.go

**Description**:  Fix for route processing and panic handling for route status update
**Fixes**: resolves #2908

Fix for route processing and panic handling for route status update

---

docs/config_examples/multicluster/README.md

**Description**:  Add Type Column for MultiCluster Parameters

Add Type Column for MultiCluster Parameters

---

pkg/controller/informers.go

**Description**:  Limit printing Pod and Configmap Definition

Limit printing Pod and Configmap Definition

---

docs/config_examples/customResource/VirtualServer/hostless-vs-with-ipam-hostgroup/hostless-vs-with-ipam-hostgroup.yaml
pkg/controller/worker.go

**Description**:  Add validations for hostless VS with IPAM and hostgroup
**Changes Proposed in PR**: Add validations for hostless VS with IPAM and hostgroup

Add validations for hostless VS with IPAM and hostgroup

---

pkg/controller/resourceConfig.go

**Description**:  Fix issue of empty pool member with defaultRouteGroup
**Changes Proposed in PR**:  Fix issue of empty pool member with defaultRouteGroup

Fix issue of empty pool member with defaultRouteGroup

---

pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go

**Description**:  Fix Multicluster config processing
1. Process HA config even when multiClusterConfig is not specified
2. Fix for handling multiple services specified in multiClusterServices annotations in routes.

Fix Multicluster config processing

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/pythonDriver.go

**Description**:  Enbale metrics with ipv6
**Fixes**: resolves #2912

Enbale metrics with ipv6

---

pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/nativeResourceWorker.go

**Description**:  Improve Debug Messages for MultiCluster HACluster

Improve Debug Messages for MultiCluster HACluster

---

pkg/controller/informers.go
pkg/controller/worker.go

**Description**:  Update PoolMembers properly for scaledown Scenarios in CIS cluster Mode.
**Changes Proposed in PR**: It handles when app Selector is updated

Update PoolMembers properly for scaledown Scenerios

---

pkg/controller/nativeResourceWorker.go

**Description**: Added support for cluster name validation in route annotation

Added support for cluster name validation in route annotation

---

pkg/controller/backend.go
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Fix issue with multiple get calls to bigip in CIS secondary mode
**Changes Proposed in PR**: Fix issue with multiple get calls to bigip in CIS secondary mode

Fix issue with multiple get calls to bigip in CIS secondary mode

---

pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/nativeResourceWorker.go

**Description**:  Fix HA config update processing
**Changes Proposed in PR**: Update HA config parameters only in case of actual config update in the GCM.

Fix HA config update processing

---

pkg/controller/backend.go

**Description**:  Handle duplicate pool members
**Changes Proposed in PR**: Remove duplicate pool members while creating the AS3 declaration.

Handle duplicate pool members

---

docs/config_examples/next-gen-routes/routes/edge-route-with-bigip-reference-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/edge-route-with-k8s-secret-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/reencrypt-route-with-bigip-reference-in-ssl-annotaion.yaml
docs/config_examples/next-gen-routes/routes/reencrypt-route-with-k8s-secret-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/route-with-target-port-health-monitor.yaml

**Description**:   Remove path field from health monitor annotation
**Changes Proposed in PR**: Remove path field from health monitor annotation

Remove path field from health monitor annotation

---

pkg/controller/backend.go
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**: Fix healthProbe mutex and priority partition issues
**Changes Proposed in PR**: Fix healthProbe mutex and priority partition issues

Fix healthProbe mutex and priority partition issues

---

cmd/k8s-bigip-ctlr/main.go

**Description**:  fix nodeport cccl not posting config

fix nodeport cccl not posting config

---

docs/config_examples/next-gen-routes/routes/edge-route-with-bigip-reference-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/edge-route-with-k8s-secret-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/reencrypt-route-with-bigip-reference-in-ssl-annotaion.yaml
docs/config_examples/next-gen-routes/routes/reencrypt-route-with-k8s-secret-in-ssl-annotation.yaml
docs/config_examples/next-gen-routes/routes/route-with-target-port-health-monitor.yaml

**Description**:  Remove path field from health monitor annotation examples
**Changes Proposed in PR**: Remove path field from health monitor annotation examples

Remove path field from health monitor annotation examples

---

pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**:  Fix for acitve-active mode without multiClusterConfigs
**Changes Proposed in PR**: Fix for acitve-active mode without multiClusterConfigs

Fix for acitve-active mode without multiClusterConfigs

---

pkg/controller/worker.go

**Description**:  fix eps issue with external clusters in cluster mode

fix eps issue with external clusters

---

pkg/controller/constants.go
pkg/controller/node_poll_handler.go
pkg/controller/worker.go

**Description**:  static route support for multicluster

static route support for multicluster

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Support PERSISTENCE capability for service published through EDNS

Support PERSISTENCE capability for service published through EDNS

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

Reverts F5Networks/k8s-bigip-ctlr#2950
As 2.13.1 is not released. Would like to recreate PR once 2.13.1 is released.

Revert "Support PERSISTENCE capability for service published through EDNS"

---

docs/RELEASE-NOTES.rst

**Description**:  Release notes 2.13.1

Release notes 2.13.1

---

config/apis/cis/v1/types.go
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/customResource/transportServer/ts-with-external-services.yaml
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services.yaml
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation.yaml
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/types.go

**Description**:  Extend VS and TS CRD schema to support multiClusterServices
**Changes Proposed in PR**: Extend VS and TS CRD schema to support multiClusterServices

Extend VS and TS CRD schema to support multiClusterServices

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/ExternalDNS/externaldns.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add EDNS Persistence Support

Add EDNS Persistence Support

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/serviceTypeLB/service-type-lb-with-hostname.yaml
pkg/controller/controller.go
pkg/controller/worker.go

**Description**:  support for host in service typeLB 
**Fixes**: resolves #2785

support for host in service typeLB

---

docs/config_examples/multicluster/README.md
pkg/controller/nativeResourceWorker.go

**Description**:  Handle scenario where HA cluster used as external cluster
**Changes Proposed in PR**: Handle scenario where HA cluster used as external cluster

Handle scenario where HA cluster used as external cluster

---

pkg/controller/resourceConfig.go

**Description**:  Optimize monitor logic for CRD
**Changes Proposed in PR**: Optimize monitor logic for CRD

Optimize monitor logic for CRD

---

pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**: Handle VS and TS processing on configMap update.
**Changes Proposed in PR**:  
1. Process configMap updates.
2. Handle configMap deletion.
3. Process VS and TS resources on configMap update.

Handle VS and TS processing on configmap update

---

pkg/controller/controller.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/node_poll_handler.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go
pkg/vxlan/vxlanMgr.go

**Description**:  Code Refactoring for endpoint processing

Code Refactoring for endpoint processing

---

docs/RELEASE-NOTES.rst
pkg/agent/as3/as3ConfigMap.go
pkg/agent/as3/as3Manager.go
pkg/test/configs/as3_multi_cm_unified_nodeport_local.json
pkg/test/configs/as3_route_cfgmap_declaration.json
pkg/test/configs/as3config_valid_1.json

**Description**:  Support AS3 logLevel and persist parameters in configmap
**Changes Proposed in PR**: Support AS3 logLevel and persist parameters in configmap

Support AS3 logLevel and persist parameters in configmap

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  fix for same svc name in different ns in NPL mode
**Fixes**: resolves #2941

fix for same svc name in different ns

---

docs/RELEASE-NOTES.rst
pkg/agent/as3/as3Common.go
pkg/agent/as3/as3Resource_test.go
pkg/appmanager/appManager.go
pkg/appmanager/eventNotifier.go
pkg/appmanager/healthMonitors.go
pkg/appmanager/ingress.go
pkg/resource/resourceConfig.go
pkg/resource/resourceConfig_test.go
pkg/resource/types.go
pkg/test/utils.go

Support for default pool using the single-service ingress

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/ExternalDNS/externaldns-client-subnet-preferred.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  client subnet support in EDNS
**Changes Proposed in PR**: client subnet support in EDNS

client subnet support in EDNS

---

pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go

crd support for mc

---

cmd/k8s-bigip-ctlr/main.go

**Description**:  fix npl cccl

fix npl cccl

---

docs/RELEASE-NOTES.rst
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/worker.go

**Description**:  fix crash issue with missing configmap or invalid endpoint type
**Changes Proposed in PR**: fix crash issue with missing configmap or invalid endpoint type

fix crash issue with missing configmap or invalid endpoint type

---

config/apis/cis/v1/types.go
docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation-and-ab.yaml
pkg/clustermanager/types.go
pkg/controller/controller.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add support for cluster ratio in multiCluster mode
**Changes Proposed in PR**: Add support for cluster ratio in multiCluster mode

Add support for cluster ratio in multiCluster mode

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/backend.go
pkg/controller/types.go
pkg/controller/worker.go
requirements.txt

**Description**:  static routes shared support write to common

static routes shared support

---

docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/multiClusterHealthProbeManager.go

**Description**:  Modify Service pattern to align with Kubernetes native service resource name 

Modify Service pattern

---

pkg/controller/responseHandler.go

**Description**:  fix ts crash

fix ts crash

---

docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

**Description**:  Add mandatory parameter for TS resource. CIS is unable to set the service.Class in case of absence of mode parameter, which resulted in 422 AS3 status code.

Add mandatory parameter for TS resource

---

pkg/controller/nativeResourceWorker.go

**Description**:  fix crash issue with invalid cm config

fix crash issue with invalid cm config

---

docs/config_examples/multicluster/README.md
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Fix multiCluster service update handling and add external service validation
1. Validate external services in route, VS and TS.
2. Handle HA cluster service update.
3. Handle external services endpoint updates.

Fix multiCluster service update handling and add external service validation

---

pkg/controller/node_poll_handler.go
pkg/controller/worker.go

**Description**:  fix static routes creation on cis restart with mc

fix static routes creation on cis restart with mc

---

cmd/k8s-bigip-ctlr/main.go
pkg/appmanager/appManager.go
pkg/controller/controller.go

**Description**:  support reading CNI data from orchestration-cni arg

support reading CNI data from orchestration-cni arg

---

docs/RELEASE-NOTES.rst
docs/config_examples/NodePortLocal/README.md
pkg/controller/controller.go
pkg/controller/worker.go

**Description**:  Support TransportServer NPL

support ts npl

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/backend.go
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/pythonDriver.go
pkg/controller/types.go
requirements.txt

**Description**:  dont push cccl config when cis is in secondary mode

dont push cccl config when cis is in secondary mode

---

docs/config_examples/multicluster/README.md
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/routing.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Handle processing of resources with invalid extended services
**Changes Proposed in PR**:  Process VS/TS/Routes with invalid extendedExternalServices while logging error for the misconfigured extended service.

Handle processing of resources with invalid extended services

---

docs/upgradeProcess.md

**Description**:  Add steps for Transitioning from CCCL GTM to AS3 GTM Agent

Documentation for Transitioning from CCCL GTM to AS3 GTM Agent

---

pkg/controller/informers.go
pkg/controller/worker.go

**Description**:  Fix for node removal when app is scaled down to zero in non multi cluster mode

Fix for node removal when app is scaled down to zero in non multi cluster mode

---

pkg/controller/worker.go

**Description**:  fix cis init for when no resources present on init

fix cis init for no resources

---

cmd/k8s-bigip-ctlr/main.go
docs/config_examples/multicluster/README.md
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/pythonDriver.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go
requirements.txt

**Description**: Renaming the cis-type to multi-cluster-mode

Renaming the cis-type to multi-cluster-mode

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/ExternalDNS/external-dns-with-lbModeFallback
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/types.go
pkg/controller/worker.go
requirements.txt

**Description**:  externalDNS support for fallbacklb mode
**Fixes**: resolves #3004

externalDNS CRD  support for configuring lbModeFallback

---

pkg/controller/worker.go

**Description**:  Handle Virtual Servers CRs with same IP and different hosts and terminations
**Changes Proposed in PR**: Handle Virtual Servers CRs with same IP and different hosts and terminations

Handle Virtual Servers CRs with same IP and different hosts and terminations

---

pkg/controller/worker.go
pkg/teem/teem.go

**Description**:  Adding teems support for multi-cluster

Add teems support for multi-cluster

---

pkg/controller/worker.go

**Description**:  Fix for Secondary CIS posting while Primary CIS is running
**Changes Proposed in PR**: Fix for Secondary CIS posting while Primary CIS is running

Fix for Secondary CIS posting while Primary CIS is running

---

pkg/controller/resourceConfig.go
pkg/controller/routing.go

**Description**:  Handle cluster ratio with path based nextGenRoutes in multiCluster mode
**Changes Proposed in PR**: Handle cluster ratio with path based nextGenRoutes in multiCluster mode

Handle cluster ratio with path based nextGenRoutes in multiCluster mode

---

pkg/controller/resourceConfig.go

**Description**:  Fix pool member processing for VS with serviceNamespace parameter

Fix pool member processing for VS with serviceNamespace parameter

---

config/apis/cis/v1/types.go
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

…meter
**Description**:  Support clientSubnetPreferred spec parameter for older AS3 versions

Support clientSubnetPreferred spec parameter for older AS3 versions

---

config/apis/cis/v1/types.go
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services-and-ab.yaml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add support for cluster ratio for Virtual server in multiCluster mode
**Changes Proposed in PR**: Add support for cluster ratio for Virtual server in multiCluster mode

Add support for cluster ratio for Virtual server in multiCluster mode

---

pkg/controller/multiClusterWorker.go

**Description**:  Fix service not found issue on Route re-creation
**Changes Proposed in PR**: Skip removing HA peer cluster informers if route is deleted.

Fix service not found issue on Route re-creation

---

pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/worker.go

**Description**:  Fixes for issues related to multiCluster ratio
**Changes Proposed in PR**: Following 
* Fix for handling external cluster ratio updation
* Improve service weight and cluster ratio calculation
* Log cluster ratios used

Fixes for issues related to multicluster ratio

---

pkg/controller/multiClusterInformers.go

**Description**:  Add MultiCluster InformerLogs for Readability

Add MultiCluster InformerLogs for Readability

---

pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**: Code clean up for svcResourceCache

Code clean up for svcResourceCache

---

pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/worker.go

**Description**: Minor code refractor changes
**Changes Proposed in PR**: Minor code refractor changes

Minor code refractor changes

---

docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Description**:  Fix CRD schema
**Changes Proposed in PR**: Restored CRD from 2.13.1 release and updated CRD in the incubator directory.

Fix CRD schema

---

pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Fix for service caching in defaultPool

Fix for service caching in defaultPool

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/ExternalDNS/externaldns-client-subnet-preferred.yaml
docs/config_examples/customResource/ExternalDNS/externaldns.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Description**:  Fix CRDSchemaDefinition for PersistenceValues

Fix CRDSchemaDefinition for PersistenceValues

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/informers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/node_poll_handler.go
pkg/controller/worker.go

**Description**:  Update multiCluster specific logs
**Changes Proposed in PR**: Update multiCluster specific logs

Update multiCluster specific logs

---

docs/config_examples/multicluster/README.md

**Description**:  update multicluster docs

update multicluster docs

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/upgradeProcess.md
helm-charts/f5-bigip-ctlr/Chart.yaml

**Description**:  CIS 2.14.0 Release

CIS 2.14.0 Release

---

pkg/controller/nativeResourceWorker.go

**Description**:  Fix for AB deployment while using insecure termination with routes

Fix for AB deployment while using insecure termination with routes

---

pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go

**Description**:  Fix for AB deployment while using insecure termination with VS CR

Fix for AB deployment while using insecure termination with VS CR

---

pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Add unit test cases
**Changes Proposed in PR**: Add unit test cases

Add unit test cases

---

docs/RELEASE-NOTES.rst
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/worker.go

**Description**:  Stable pool name in multi cluster mode
**Changes Proposed in PR**: Stable pool name in multi cluster mode
**Fixes**: resolves #3061

Stable pool name in multi cluster mode

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/policy-with-pool-settings.yaml
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**: support pool reselect settings in policy cr
**Fixes**: resolves #3057

support pool settings in policy cr

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/controller_suit_test.go
pkg/controller/gtmBackend.go
pkg/controller/gtmBackend_test.go
pkg/controller/informers_test.go
pkg/controller/postManager.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Adding a new AS3 GTM post manager to post the GTM declaration on separate  GTM server.

Support for AS3 GTM agent with separate GTM server

---

pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Fix external cluster pool members empty issue in ratio mode
**Changes Proposed in PR**: Fix external cluster pool members empty issue in ratio mode

Fix external cluster pool members empty issue in ratio mode

---

pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Fix livenessprobe update issue
**Changes Proposed in PR**: Fix livenessprobe update issue

Fix livenessprobe update issue

---

pkg/controller/backend.go

**Description**: Limit continuous GET AS3 Declaration

Limit continuous GET AS3 Declaration

---

docs/RELEASE-NOTES.rst
docs/config_examples/multicluster/README.md

**Description**:  Add Known Issue for MultiCluster

Add Known Issue for MultiCluster

---

pkg/controller/informers.go
pkg/controller/node_poll_handler.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Fix processing svc target port update

Fix processing svc target port update

---

pkg/controller/multiClusterInformers.go

**Description**:  Fix CIS getting blocked during start-up in MultiCluster mode when external cluster's API server is not responding
* To avoid CIS getting blocked indefinitely, a timeout of 30 seconds has been introduced for informer cache syncing. 
* If cache sync doesn't get completed in 30 seconds then that can mean some issue with the API server, so CIS proceed further after logging warning message indicating which cluster is having issues.
* However, since the informers haven't been stopped, if the affected API server starts responding later on then CIS will start processing the events as and when it receives those from the affected cluster.

Fix CIS getting blocked during start-up in MultiCluster mode when external cluster's API server is not responding

---

docs/config_examples/StaticRoute/README.md

**Description**:  static routing mode doc updtae

static routing mode doc updtae

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go

**Description**:  Fix AS3 config map multi port service issue
**Changes Proposed in PR**: #3073 

Fix AS3 config map multi port service issue

---

docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation.yaml
pkg/clustermanager/types.go
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/resource/types.go

**Description**:  Add support for cluster AdminState
**Changes Proposed in PR**: Add support for cluster AdminState
**Fixes**: resolves #3072

Add support for cluster AdminState

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
docs/config_examples/StaticRoute/README.md
docs/config_examples/StaticRoute/cis-deployment-ovn-k8s-mnic.yaml
pkg/appmanager/appManager.go
pkg/controller/constants.go
pkg/controller/controller.go
pkg/controller/node_poll_handler.go
pkg/controller/types.go

**Description**:  Support for configuring node network for ovn-k8s CNI with staticroutingmode

Support for configuring node network for ovn-k8s CNI 

---

pkg/controller/backend_test.go
pkg/controller/postManager_test.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker_test.go

**Description**:  Unit tests for controller package
**Changes Proposed in PR**: Added unit tests for code coverage in controller package

#JRA-4151 Add unit tests for code coverage

---

docs/RELEASE-NOTES.rst
pkg/controller/controller.go
pkg/health/health.go

**Description**:  New /ready health endpoint for primary CIS in multi-cluster environment
**Fixes**: resolves #2985

Add support for /ready health endpoint for CIS

---

docs/config_examples/multicluster/README.md
pkg/controller/resourceConfig.go

**Description**:  strip underscore suffix for poolname

Strip underscore suffix for poolname

---

docs/RELEASE-NOTES.rst
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/routes/sample-route-with-pod-concurrent-connections-annotation.yaml
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/controller.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/resource/types.go

**Description**:  Added support for pod-concurrent-connections
**Fixes**: resolves #3086

Added support for pod-concurrent-connections

---

pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Fix for local cluster health monitor name in multiCluster ratio mode
**Changes Proposed in PR**: Fix for local cluster health monitor name in multiCluster ratio mode

Fix for local cluster health monitor name in multiCluster ratio mode

---

pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/resourceConfig_test.go

**Description**:  Error when no health monitors are provided
**Changes Proposed in PR**: Added type to the default values

Fix for default minimumMonitor value

---

docs/config_examples/multicluster/README.md

**Description**:  multiCluster doc update

multiCluster doc update

---

pkg/controller/resourceConfig.go

**Description**:   fix target port issue observed on 2.14

fix target port

---

build-tools/Dockerfile.ubi
requirements.txt

**Description**:  Bump urllib3 to 1.26.17

Bump Requests to 2.31.0, urllib3 to 1.26.18, Certifi to 2023.7.22

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  fix vs address status with hg
**Fixes**: resolves #3126

fix vs address status with hg

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md
pkg/agent/as3/as3Manager.go
pkg/agent/as3/as3Manager_test.go
pkg/controller/controller.go
pkg/test/configs/as3_multi_cm_unified_nodeport_local.json
pkg/test/configs/as3_route_cfgmap_declaration.json
pkg/test/configs/as3_route_declaration.json
pkg/test/configs/as3_route_declaration_overridden.json
pkg/test/configs/as3config_multi_cm_unified.json
schemas/as3-schema-3.48.0-10-cis.json

**Description**: Add support for AS3 3.48 minor v10
**Changes Proposed in PR**: Add support for AS3 3.48 minor v10

Add support for AS3 3.48 minor v10

---

docs/RELEASE-NOTES.rst
docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-with-cluster-admin-state.yaml

**Description**:  Update docs and add cluster adminState example for multiCluster
**Changes Proposed in PR**:  Update docs and add cluster adminState example for multiCluster

Update docs and add cluster adminState example for multiCluster

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/upgradeProcess.md
helm-charts/f5-bigip-ctlr/Chart.yaml

**Description**:  CIS 2.15.0 Release
**Changes Proposed in PR**: CIS 2.15.0 Release

CIS 2.15.0 Release

---

f5-bigip-ctlr-operator/Dockerfile
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
f5-bigip-ctlr-operator/bundle/metadata/annotations.yaml

**Description**:  Updating the operator version for operator release 1.15.0
**Changes Proposed in PR**: Updating the operator version for operator release 1.15.0

Updating the operator version for operator release 1.15.0

---

docs/RELEASE-NOTES.rst
docs/config_examples/multicluster/Policy/policy-with-ab-persistence.yaml

**Description**:  add example for a/b multicluster persistence
**Changes Proposed in PR**: add example for a/b multicluster persistence

add example for a/b multicluster persistence

---

docs/config_examples/customResource/IngressLink/README.md

**Description**:  Update ingressLink link in Readme doc

Update ingressLink link in Readme doc

---

pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go

**Description**:  Fix pool name in multicluster active-active mode
**Changes Proposed in PR**: Fix pool name in multicluster active-active mode
**Fixes**: resolves #3129

Fix pool name in multicluster active-active mode

---

docs/cis-3.x/install/k8s/sample-k8s-bigip-ctlr.yaml
docs/cis-3.x/rbac/clusterrole.yaml

**Description**:  Add sample manifests for cluster role, cluster role binding, service account, and deployment.
**Changes Proposed in PR**: Added sample manifests for cluster role, cluster role binding, service account, and deployment. 

add manifests for cis 3.0

---

pkg/controller/controller.go
pkg/controller/types.go
pkg/tokenmanager/tokenmanager.go
pkg/tokenmanager/tokenmanager_suite_test.go
pkg/tokenmanager/tokenmanager_test.go

**Description**:  Add token manager to manage CM token
**Changes Proposed in PR**: Add token manager to manage CM token

Add token manager

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/IngressLink/README.md
docs/config_examples/multicluster/Policy/policy-with-ab-persistence.yaml
f5-bigip-ctlr-operator/Dockerfile
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
f5-bigip-ctlr-operator/bundle/metadata/annotations.yaml
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go

2.x changes

---

cmd/k8s-bigip-ctlr/main.go
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/gtmBackend.go
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/postManager.go
pkg/controller/pythonDriver.go
pkg/controller/worker.go

**Description**:  Updating log messages for user friendliness
**Fixes**: resolves #3118

Updating log messages for user friendliness

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/controller.go
pkg/controller/types.go
pkg/tokenmanager/tokenmanager.go
pkg/tokenmanager/tokenmanager_test.go

**Description**:  Add trusted cert support for token manager
**Changes Proposed in PR**: Add trusted cert support for token manager

Add trusted cert support for token manager

---

pkg/controller/routing.go

**Description**:  Fix iRule logic for passthrough
**Changes Proposed in PR**: Fix iRule logic for passthrough
**Fixes**: resolves #3133

Fix iRule logic for passthrough

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Description**: Removed unsupported parameters in deploy config CR

Removed unsupported parameters in deploy config CR

---

azure-pipelines.yaml
build-tools/Dockerfile.debian
build-tools/Dockerfile.debug
build-tools/Dockerfile.ubi
cmd/k8s-bigip-ctlr/main.go
go.mod
go.sum
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/gtmBackend.go
pkg/controller/gtmBackend_test.go
pkg/controller/informerManager.go
pkg/controller/informers_test.go
pkg/controller/metrics.go
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/postManager.go
pkg/controller/postManager_test.go
pkg/controller/requestHandler.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

Added Agent initialization per bigip label

Implement Reuqesthandler

---

docs/config_examples/multicluster/README.md

**Description**:  MultiCluster Doc Improvement

MultiCluster Doc Improvement

---

pkg/controller/constants.go
pkg/controller/controller_suit_test.go
pkg/controller/informerManager.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/postManager.go
pkg/controller/requestHandler.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  resource store changes are handled. TransportServer resource config processed and added to bigipMap.

resource store changes to handle mapping of resource config to bigipLabel

---

cmd/k8s-bigip-ctlr/main.go
docs/config_examples/rbac/clusterrole.yaml

**Description**: Add check, Update clusterrole(rbac) and modified parameter name properly

Add check, Update clusterrole(rbac) and modified parameter name properly

---

pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informers_test.go
pkg/controller/metrics.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/requestHandler.go
pkg/controller/requestHandler_test.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  new agent handle per bigip

new agent handle per bigip

---

build-tools/Dockerfile.debug
cmd/k8s-bigip-ctlr/main.go
pkg/controller/controller.go
pkg/controller/postManager.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Fix cis crash and minor issues
**Changes Proposed in PR**: Fix cis crash and minor issues

Fix cis crash and minor issues

---

pkg/controller/postManager.go
pkg/controller/responseHandler.go

**Description**:  Update TS status on successful posting
**Changes Proposed in PR**: Update TS status on successful posting

Update TS status on successful posting

---

docs/cis-3.x/rbac/clusterrole.yaml
docs/config_examples/rbac/clusterrole.yaml

**Description**:  RBAC update and fix CIS 2.x config

RBAC update and fix CIS 2.x config

---

pkg/controller/postManager.go
pkg/controller/requestHandler.go

update the logs for post manager and request handler

---

docs/multicluster_userguides/README.md

**Description**:  Add multicluster userguides

Add multicluster userguides

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go

**Description**:  Add required argument check

Add required argument check

---

pkg/tokenmanager/tokenmanager.go

**Description**: stop retry for token with invalid credentials

stop retry for token with invalid credentials

---

build-tools/Dockerfile.debian
cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
pkg/tokenmanager/tokenmanager.go

**Description**:  Stop retry fetching Token

Stop retry fetching Token

---

pkg/controller/informers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**: Improved the context for few logs
**Fixes**: resolves #3210 
#3209 
#3207

Improved the context for few logs

---

build-tools/Dockerfile.ubi

**Description**:  Remove Git dependency Perl packages

Remove Git dependency Perl packages

---

pkg/controller/as3PostManager.go
pkg/controller/types.go
pkg/tokenmanager/tokenmanager.go

**Description**:  remove unsupported as3 schema
**Changes Proposed in PR**: remove unsupported as3 schema

remove unsupported as3 schema

---

docs/RELEASE-NOTES.rst
f5-bigip-ctlr-operator/Dockerfile
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
f5-bigip-ctlr-operator/bundle/metadata/annotations.yaml

**Description**:  Updating the operator version for operator release 1.16.0
**Changes Proposed in PR**: Updating the operator version for operator release 1.16.0

Updating the operator version for operator release 1.16.0

---

config/apis/cis/v1/types.go
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-ssl-renegotiation-disabled/README.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-ssl-renegotiation-disabled/tls-ssl-secrets-renegotiation-disabled.yaml
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-ssl-renegotiation-disabled/virtualserver.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/profile.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:  support renegotiationEnabled on ssl custom profiles

support renegotiationEnabled on ssl custom profiles

---

requirements.txt

**Description**:  Fix f5-icontrol-rest Info Log Issue
**Changes Proposed in PR**: Improve log f5-icontrol-rest  message 
**Fixes**: resolves #3190

Fix f5-icontrol-rest Info Log Issue

---

cmd/k8s-bigip-ctlr/main.go

**Description**:  Fix pool member empty issue
**Changes Proposed in PR**: Fix pool member empty issue

Fix pool member empty issue

---

docs/cis-3.x/README.md
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/cis-3.x/install/k8s/sample-k8s-bigip-ctlr.yaml
pkg/controller/constants.go
pkg/controller/postManager.go

**Description**:  Fix crash with master

Fix crash with master build

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
config/apis/cis/v1/types.go
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/controller.go
pkg/controller/informerManager.go
pkg/controller/types.go
pkg/controller/worker.go

streamline CNI logic

---

pkg/appmanager/appManager.go

**Description**:   Fix error log for hub mode
**Fixes**: resolves #3231

Fix error log for hub mode

---

docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-ssl-renegotiation-disabled/tls-ssl-secrets-renegotiation-disabled.yaml

**Description**:  fix doc example

fix doc example

---

pkg/controller/worker.go

**Description**:  fix arp issue on deployment scale down
**Changes Proposed in PR**: fix arp issue on deployment scale down

fix arp issue on deployment scaledown

---

docs/cis-3.x/README.md

**Description**:  Add CIS 3.x Deployment Parameters

Add CIS 3.x Deployment Parameters

---

pkg/controller/postManager.go

**Description**:  show complete response from AS3 on Post
**Changes Proposed in PR**: Updated and called the logAS3Response function for both success and failure Post calls with debug log level.
**Fixes**: resolves #3232

#3232 show raw response from BIG IP on both success and failure

---

config/apis/cis/v1/types.go
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/customResource/transportServer/ts-with-external-services.yaml
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services-and-ab.yaml
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services.yaml
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation-and-ab.yaml
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation.yaml
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/postManager.go
pkg/controller/validate.go

Revert the changes in 2.15-stable branch

revert the commits

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-health-monitor/virtualserver.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/next-gen-routes/routes/route-with-target-port-health-monitor.yaml
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:  support sslProfile in https monitor
**Fixes**: resolves #3236

support sslProfile in https monitor

---

pkg/controller/postManager.go

**Description**:  show complete response from AS3 on Post
**Changes Proposed in PR**: Updated and called the logAS3Response function for both success and failure Post calls with debug log level.
**Fixes**: resolves #3232

show raw response from BIG IP on both success and failure

---

pkg/controller/backend.go
pkg/controller/types.go

**Description**:  fix default value of sslProfile

fix default value of sslProfile to none

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/config_examples/multicluster/customResource/transportServer/ts-with-external-services.yaml
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services-and-ab.yaml
docs/config_examples/multicluster/customResource/virtualServer/vs-with-extended-services.yaml
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation-and-ab.yaml
docs/config_examples/multicluster/routes/route-with-multicluster-service-annotation.yaml
pkg/controller/nativeResourceWorker_test.go
pkg/controller/validate.go
pkg/controller/validate_test.go

**Description**:  Update the params serviceName and port to service and servicePort in extendedServiceReferences
**Changes Proposed in PR**:  Updated the params in the CRD, Types and modified the validation messages.

update params for extended service and multi cluster references

---

config/apis/cis/v1/types.go
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/cis-3.x/install/k8s/sample-k8s-bigip-ctlr.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/constants.go
pkg/controller/controller.go
pkg/controller/informerManager.go
pkg/controller/informerManager_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/networkmanager/networkmanager.go
pkg/networkmanager/networkmanager_suite_test.go
pkg/networkmanager/networkmanager_test.go
pkg/tokenmanager/tokenmanager.go
pkg/tokenmanager/tokenmanager_test.go

**Description**:  Support for static routes via central manager
**Changes Proposed in PR**: Added a new network manager to handle all the networking requests

Support for static routes via central manager

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
docs/RELEASE-NOTES.rst
docs/config_examples/Install/openshift/HA/README.md
docs/config_examples/PoolType-Auto/README.md
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go
pkg/resource/types.go

**Description**:  pool member type auto support
**Changes Proposed in PR**: pool member type auto support

pool member type auto support

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  Fix for wildcard support with hosts array in tlsProfile

Fix for wildcard support with hosts array in tlsProfile

---

pkg/controller/resourceConfig.go

**Description**:  fix wildcard for tls hosts array

fix wildcard for tls hosts array

---

config/apis/cis/v1/types.go
docs/cis-3.x/README.md
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/constants.go
pkg/controller/node_poll_handler.go
pkg/controller/worker.go

**Description**:  Add static routing mode to network config. Add description for deployconfig cr fields

Add static routing mode to network config

---

pkg/controller/informers.go
pkg/networkmanager/networkmanager.go

fix duplicate l3 events

---

cmd/k8s-bigip-ctlr/main_test.go
pkg/controller/requestHandler.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  add unit test coverage

ut coverage

---

docs/RELEASE-NOTES.rst
pkg/controller/nativeResourceWorker.go

**Description**: Fix Improve log when admitting route status
**Fixes**: resolves #3266

Fix Improve log when admitting route status

---

docs/RELEASE-NOTES.rst
pkg/controller/nativeResourceWorker.go
pkg/controller/routing.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Fix Improve log for certificate host name validation
**Fixes**: resolves #3267

Fix Improve log for certificate host name validation

---

docs/RELEASE-NOTES.rst
pkg/agent/as3/as3ConfigMap.go
pkg/appmanager/appManager.go

**Description**:  Fix for Additional PoolMember properties in ConfigMap not preserved
**Fixes**: resolves #3277

Fix for Additional PoolMember properties in ConfigMap not preserved

---

pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**: fix share node issue with auto mode
**Changes Proposed in PR**: fix share node issue with auto mode

fix share node issue with auto mode

---

cmd/k8s-bigip-ctlr/main.go
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/node_poll_handler.go
pkg/controller/postManager.go

**Description**:  Add support for multi-cluster for transport server CR

Add support for multi-cluster for transport server CR

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/README.md
docs/config_examples/customResource/Policy/policy-with-default-pool.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go

**Description**:  support for setting default pool via policy CR
**Fixes**: resolves #3295

support for setting default pool via policy CR

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
docs/config_examples/configmap/trusted-certs-configmap/README.md
docs/config_examples/configmap/trusted-certs-configmap/trusted-certs-cm.yaml
docs/upgradeProcess.md

**Description**:  trusted cert support in crd and nextgen
**Changes Proposed in PR**: trusted cert support in crd and nextgen

trusted cert support in crd and nextgen

---

docs/RELEASE-NOTES.rst
pkg/controller/postManager.go

**Description**:  Fix CIS 2.15 crashes due to interface conversion panic
**Fixes**: resolves #3312

Fix CIS 2.15 crashes due to interface conversion panic

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/worker_test.go

**Description**:  Improved unit test coverage

Improved unit test coverage

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/agent/as3/as3Manager.go
pkg/agent/as3/as3Resource.go
pkg/health/health.go

**Description**:  #3279 default partition to be disabled
**Fixes**: resolves #3279

#3279 disable default partition

---

pkg/controller/as3PostManager.go
pkg/controller/constants.go
pkg/controller/postManager.go
pkg/controller/postManager_test.go
pkg/controller/requestHandler_test.go
pkg/controller/worker.go

**Description**: Updating the declare api URI for CM

Updating the declare api URI for CM

---

pkg/controller/as3PostManager.go
pkg/controller/constants.go
pkg/controller/postManager.go

**Description**: Fixes for declare api

Fixes for declare api

---

pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Fix Policy for Hostless VS

Fix Policy for Hostless VS

---

pkg/controller/as3PostManager.go
pkg/controller/backend.go
pkg/controller/constants.go
pkg/controller/requestHandler_test.go
pkg/controller/routing.go

**Description**:  Added support for per application deployment, so that we can utilise the per app deployment feature on central manager.

Added support for per application deployment

---

docs/config_examples/customResource/serviceTypeLB/example-service-type-lb-staic-ip.yaml
pkg/controller/constants.go
pkg/controller/informers.go
pkg/controller/worker.go

**Description**:  service type lb support
**Changes Proposed in PR**: service type lb support

service type lb support

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/serviceTypeLB/README.md
docs/config_examples/customResource/serviceTypeLB/example-service-type-lb-staic-ip.yaml
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  static ip support with service type lb
**Changes Proposed in PR**: static ip support with service type lb

static ip support with service type lb

---

cmd/k8s-bigip-ctlr/main.go
config/apis/cis/v1/types.go
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/config_examples/PoolType-Auto/README.md
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/constants.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/resourceConfig.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go
pkg/ipmanager/ipmanager.go

**Description**:  Refactored the IPAM code and moved to ipmanager package

Refactored the IPAM code and moved to ipmanager package

---

pkg/controller/node_poll_handler.go
pkg/networkmanager/networkmanager.go
pkg/networkmanager/networkmanager_test.go

**Description**:  Fix for traffic not working in cluster mode

Fix for traffic not working in cluster mode

---

docs/cis-3.x/rbac/clusterrole.yaml
docs/config_examples/customResource/IngressLink/ingressLink-with-iRule-reference-from-cm/ingresslink-with-iRule-reference-from-cm.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/as3PostManager.go
pkg/controller/controller.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Add support for ingressLink in CIS 3.x
1. Added support for ingressLink
2. Added support for cm iRule with ingressLink.

Add support for ingressLink

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/gtmBackend.go
pkg/controller/postManager.go

fix to post latest config in retry scenario

---

config/apis/cis/v1/types.go
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/informers.go
pkg/controller/responseHandler.go
pkg/controller/validate.go
pkg/controller/worker.go

support for resource status update

---

config/apis/cis/v1/types.go
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
pkg/controller/informers.go
pkg/controller/responseHandler.go
pkg/controller/worker.go

**Description**:  support for il status update in response handler"
**Changes Proposed in PR**: support for il status update in response handler"

support for il status update in response handler

---

docs/RELEASE-NOTES.rst
requirements.txt

**Description**:  Fix CCCL auth error
**Changes Proposed in PR**: Fix CCCL auth error
**Fixes**: resolves #3335

Fix CCCL auth error

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md

**Description**:  Release notes 2.16.1

Release notes 2.16.1

---

docs/RELEASE-NOTES.rst
pkg/controller/routing.go

**Description**:  Fix irule for oneconnect profile
**Changes Proposed in PR**: Fix irule for oneconnect profile
**Fixes**: resolves #3371

Fix irule for oneconnect profile

---

cmd/k8s-bigip-ctlr/main.go
config/apis/cis/v1/types.go
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml
docs/cis-3.x/install/k8s/sample-k8s-bigip-ctlr.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/worker.go

**Description**: Documentation and code refactoring

Documentation and code refactoring

---

pkg/controller/postManager.go

**Description**:  Fix CIS crashes due to interface conversion panic
**Changes Proposed in PR**: Fix CIS crashes due to interface conversion panic

Fix CIS crashes due to interface conversion panic

---

pkg/controller/postManager.go

**Description**:  Fix AS3 response parsing for new response format
**Changes Proposed in PR**: Fix AS3 response parsing for new response format

Fix AS3 response parsing for new response format

---

pkg/controller/worker.go

**Description**:  Add policyCR support for svcTypeLB

Add policyCR support for svcTypeLB

---

pkg/controller/informers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go
pkg/test/utils.go

**Description**:  Fix for crash due to concurrent map access
**Fixes**: resolves SR: 00598177

Fix for crash due to concurrent map access

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  Fix EDNS pool member empty
**Changes Proposed in PR**: Fix EDNS pool member empty

Fix EDNS pool member empty

---

docs/RELEASE-NOTES.rst
docs/config_examples/StaticRoute/README.md
pkg/controller/constants.go
pkg/controller/node_poll_handler.go

**Description**:  Add support for static routes with Calico CNI
**Fixes**: resolves #3363

Add support for static routes with Calico CNI

---

docs/cis-3.x/README.md
docs/cis-3.x/deploy-config/cis-deploy-config-cr.yaml

**Description**:  Documentation improvements

Documentation improvements

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/postManager.go

**Description**:  Fix logging and CRD
**Changes Proposed in PR**: Fix logging and CRD

Fix logging and CRD

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/policy-with-profileAccess.yaml
docs/config_examples/customResource/VirtualServer/accessProfile-per-request-policy/README.md
docs/config_examples/customResource/VirtualServer/accessProfile-per-request-policy/access-profile-per-reqeust-policy.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/types.go

**Description**:  Support for access profile and per request policy in policy CRD and VS CRD
**Changes Proposed in PR**: Support for access profile and per request policy in policy CRD and VS CRD

Support for access profile and per request policy in policy CRD and VS CRD

---

pkg/ipmanager/ipmanager.go

**Description**:  Fix for IPAM CR cleanup issue
**Changes Proposed in PR**: Fix for IPAM CR cleanup issue

Fix for IPAM CR cleanup issue

---

pkg/controller/informers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go
pkg/test/utils.go

Reverts F5Networks/k8s-bigip-ctlr#3394

Revert "Fix for crash due to concurrent map access"

---

pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informerManager.go
pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/postManager.go
pkg/controller/requestHandler.go
pkg/controller/requestHandler_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**: Fix for concurrent map access

Fix for concurrent map access

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/constants.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Improve CRD validations and logging
**Changes Proposed in PR**:  Improve CRD validations and logging
**Fixes**: resolves #3414

Improve CRD validations and logging

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go

**Description**:  Fix crash in CIS startup after using namespace-label parameter
**Fixes**: resolves #3434

Fix crash in CIS startup after using namespace-label parameter

---

pkg/controller/controller.go

**Description**:  Fix ipam initialization issue
**Changes Proposed in PR**: Fix ipam initialization issue

Fix ipam initialization issue

---

docs/cis-3.x/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/controller.go
pkg/controller/node_poll_handler.go
pkg/networkmanager/networkmanager.go
pkg/tokenmanager/tokenmanager.go

**Description**:  set defaultL3Network based on CM version

set defaultL3Network based on CM version

---

docs/RELEASE-NOTES.rst
docs/config_examples/Install/openshift/HA/README.md
docs/config_examples/Install/openshift/StandAlone/README.md
docs/config_examples/configmap/user-defined-configmap/README.md
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/IngressLink/README.md
docs/config_examples/customResource/VirtualServer/http2/README.md
docs/config_examples/customResource/VirtualServer/http2/vs-with-profilehttp2.yaml
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/migration-guide.md

**Description**:  Fix for documentation broken links

Fix for documentation broken links

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Description**:  Fix for CRD validation

Fix for CRD validation

---

pkg/statusmanager/statusmanager.go

**Description**:  Fix deployConfigCR status update
**Changes Proposed in PR**: Fix deployConfigCR status update

Fix deployConfigCR status update

---

pkg/networkmanager/networkmanager.go
pkg/networkmanager/networkmanager_test.go

Fix L3Network task endpoint

---

pkg/controller/worker.go

fix crash issue with namespace delete

---

build-tools/Dockerfile.ubi
requirements.txt

**Description**:  Fix python vulnerability
**Changes Proposed in PR**: Removed python from CIS 3.x UBI based image.

Fix python vulnerability

---

README.md
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/IngressLink/README.md
docs/config_examples/customResourceDefinitions/crd_update.md
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/next-gen-routes/README.md
docs/config_examples/next-gen-routes/migration-guide.md
docs/config_examples/rbac/k8s_rbac.yml
docs/config_examples/rbac/openshift_rbac.yaml
docs/upgradeProcess.md
f5-bigip-ctlr-operator/Dockerfile
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
f5-bigip-ctlr-operator/bundle/metadata/annotations.yaml
f5-bigip-ctlr-operator/config/manifests/bases/f5-bigip-ctlr-operator.clusterserviceversion.yaml
helm-charts/f5-bigip-ctlr/Chart.yaml
helm-charts/f5-bigip-ingress/Chart.yaml

**Description**:  Upgrade openshift to 4.15 and 2.17.0 release

2.17.0 release with openshift 4.15

---

docs/RELEASE-NOTES.rst

**Description**:  2.17 release
**Changes Proposed in PR**: Fixed the release notes format

fix format

---

pkg/controller/worker.go

fix LB Services stay stuck in Pending state with IPAM

---

docs/RELEASE-NOTES.rst
pkg/controller/informers.go

**Description**:  Fix static route creation in namespace label mode
**Changes Proposed in PR**: Fix static route creation in namespace label mode
**Fixes**: resolves #3424

Fix static route creation in namespace label mode

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md
pkg/controller/controller.go
pkg/controller/worker.go

fix issue with ipam-cluster-label

---

docs/RELEASE-NOTES.rst
docs/config_examples/appsExample/SecuredApp/secured-service.yaml
docs/config_examples/appsExample/UnSecuredApp/unsecured-service.yaml
docs/config_examples/ingress/networkingV1/example-ingress-class-name.yaml
docs/upgradeProcess.md
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
helm-charts/f5-bigip-ctlr/Chart.yaml
helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml

**Description**:  Fix to enable ingressClass in CIS deployment
**Fixes**: resolves #3405

Fix to enable ingressClass in CIS deployment

---

azure-pipelines.yaml

**Description**:  Adding the CIS version in image tag

Adding the CIS version in image tag

---

build-tools/Dockerfile.ubi

Reverts F5Networks/k8s-bigip-ctlr#3461

Revert "Upgrade python version to 3.9.19"

---

pkg/controller/as3PostManager.go
pkg/controller/constants.go
pkg/controller/postManager.go

**Description**:  Comment document API as it is not supported currently

comment document api for code coverage as it is currently supported

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

**Description**: Release note CIS 2.17.1

Release notes CIS 2.17.1

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  fix scaling issue in nodeport local mode
**Changes Proposed in PR**: fix scaling issue in nodeport local mode

fix scaling issue in nodeport local mode

---

docs/RELEASE-NOTES.rst
requirements.txt

**Description**:  Unexpected error messages from controller agent.
**Changes Proposed in PR**: Logged the exceptions meaningfully in controller agent
**Fixes**: resolves #3432

log ctlr agent exception messages

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Support for ipam-namespace deployment parameter
**Fixes**: resolves #3430

Support for ipam-namespace deployment parameter

---

docs/RELEASE-NOTES.rst
docs/config_examples/configmap/user-defined-configmap/sample-as3-cm-with-pool-member-disable.yaml
docs/config_examples/rbac/clusterrole.yaml
docs/config_examples/rbac/k8s_rbac.yml
docs/config_examples/rbac/openshift_rbac.yaml
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/resource/resourceConfig.go
pkg/resource/resourceConfig_test.go
pkg/resource/types.go

**Description**:  Support to disable members based on deployments for AS3 Configmaps
**Changes Proposed in PR**: Support to disable members based on deployments for AS3 Configmaps

Support to disable members based on deployments for AS3 Configmaps

---

pkg/appmanager/appManager.go

**Description**:  Fix for disable members update in AS3 configmap
**Changes Proposed in PR**: Fix for disable members update in AS3 configmap

Fix for disable members update in AS3 configmap

---

docs/RELEASE-NOTES.rst
pkg/agent/as3/postManager.go
pkg/controller/postManager.go

improve message handling when getting HTTP/401 from AS3

---

docs/RELEASE-NOTES.rst
pkg/controller/backend.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  support passthrough vs without default ssl profile
**Changes Proposed in PR**: support passthrough vs without default ssl profile

support passthrough vs without default ssl profile

---

docs/cis-3.x/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/cis-3.x/config_examples/customResourceDefinitions/stable/customresourcedefinitions.yml

Fixing the CRD schema

---

build-tools/Dockerfile.debian

Updating the golang version for debian image

---

docs/config_examples/customResource/VirtualServer/virtual-with-bigipRouteDomain/virtual-with-bigipRouteDomain.yaml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Support for bigiproutedomain domain in vs, ts and ingresslink
**Changes Proposed in PR**: Added support in nodeport mode
**Fixes**: resolves #3418

support for bigip route domain in nodeport mode

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-tlsCipher/README.md
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-tlsCipher/virtualserver-with-disbaleTLSVersions.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/next-gen-routes/README.md
pkg/controller/backend.go
pkg/controller/backend_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  support to disable tls version in tlsprofile and base route config
**Changes Proposed in PR**: support to disable tls version in tlsprofile and base route config

support to disable tls version in tlsprofile and base route config

---

build-tools/Dockerfile.debug

Fixed the deubg image

---

docs/config_examples/customResource/serviceTypeLB/README.md
docs/config_examples/customResource/serviceTypeLB/service-type-lb-with-policyname.yaml

Updating the service type lb documentation

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/IngressLink/ingressLink-with-bigipRouteDomain/README.md
docs/upgradeProcess.md

Fix 2.18 release notes

---

docs/cis-3.x/RELEASE-NOTES.rst

3.0.0 Release Notes

---

requirements.txt

**Description**:  Updated f5-cccl and f5-ctlr-agent versions to fix vulnerabilities.
**Changes Proposed in PR**: Updated f5-cccl and f5-ctlr-agent versions to fix vulnerabilities.

Update f5-cccl and f5-ctlr-agent versions

---

docs/RELEASE-NOTES.rst

[Release Notes] Add support for Operator

---

docs/config_examples/configmap/user-defined-configmap/sample-as3-cm-with-pool-member-disable.yaml
docs/config_examples/rbac/clusterrole.yaml
docs/config_examples/rbac/k8s_rbac.yml
docs/config_examples/rbac/openshift_rbac.yaml

**Description**:  Remove deployment resource rule from RBAC and document this requirement
**Changes Proposed in PR**: Remove deployment resource rule from RBAC and document this requirement

Remove deployment resource rule from RBAC and document this requirement

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
docs/cis-3.x/README.md

**Description**:  Removing the disable teems parameter
**Changes Proposed in PR**: Removing the disable teems parameter

Removing the disable teems parameter

---

pkg/controller/metrics_test.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker_test.go

Improve Unit Test Coverage

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/VirtualServerWithTLSProfile/tls-with-http2-profile/README.md
pkg/appmanager/appManager.go

**Description**:  [LOGS] improve log message Finished syncing virtual servers xxx in namespace yyy(199.218µs), 1/7
**Changes Proposed in PR**: Corrected the log message according to the requirement
**Fixes**: resolves #3520

[LOGS] improve log message Finished syncing virtual servers xxx in namespace yyy(199.218µs), 1/7

---

docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/appmanager/ingress.go
pkg/resource/resourceConfig.go
pkg/resource/resourceConfig_test.go

**Description**: Fix for ingress processing when same backend is used with multiple ingresses
**Fixes**: resolves #3507

Fix for ingress processing when same backend is used with multiple ingresses

---

docs/RELEASE-NOTES.rst
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/nativeResourceWorker.go

**Description**:  Fix CIS not watching external cluster namespaces with namespace-label
**Changes Proposed in PR**: Fix CIS not watching external cluster namespaces with namespace-label
**Fixes**: resolves #3535

Fix CIS not watching external cluster namespaces with namespace-label

---

docs/RELEASE-NOTES.rst
pkg/controller/routing.go

**Description**:  Fix for CIS with oneconnect and TLS breaks some connections
**Fixes**: resolves #3501

Fix for CIS with oneconnect and TLS breaks some connections

---

all_attributions.txt
build-tools/Dockerfile.attribution
build-tools/attributions-generator.sh

**Description**:  Adding attributions

Adding attributions

---

docs/RELEASE-NOTES.rst
docs/config_examples/multicluster/customResource/transportServer/ts-with-extended-service-ha-svcs.yaml
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/validate.go
pkg/controller/validate_test.go
pkg/controller/worker.go

**Description**:  support ha services in extendedServiceReference
**Changes Proposed in PR**: support ha services in extendedServiceReference

support ha services in extendedServiceReference

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/postManager.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Resource status for Vs, TS and, IL
**Changes Proposed in PR**: Supported resource status
**Fixes**: resolves #3536

#3536 show resource status for VS, TS and IL

---

azure-pipelines.yaml
build-tools/Dockerfile.debian
build-tools/Dockerfile.debug
build-tools/Dockerfile.ubi
go.mod
pkg/controller/metrics_test.go

**Description**:  Upgrading the golang to 1.22.7

Upgrading the golang to 1.22.7

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/nativeResourceWorker.go
pkg/controller/validate.go

**Description**: Add validations for auto mode in multiCluster
**Changes Proposed in PR**: Add validations for auto mode in multiCluster

Add validations for auto mode in multiCluster

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/serviceTypeLB/README.md
docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/policy-with-pool-settings.yaml
docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/service-type-lb-with-poolsettings-in-policycr.yaml
docs/config_examples/customResource/serviceTypeLB/service-type-lb-with-custom-partition.yaml
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Add support custom partition and pool settings for ServiceTypeLB
**Changes Proposed in PR**: Add support custom partition and pool settings for ServiceTypeLB

Add support custom partition and pool settings for ServiceTypeLB

---

docs/RELEASE-NOTES.rst
pkg/controller/multiClusterInformers.go
pkg/controller/resourceConfig.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Support for traffic distribution with weights in multiClusterServices in default mode for TS
**Changes Proposed in PR**: Support for traffic distribution with weights in multiClusterServices in default mode for TS

Support for traffic distribution with weights in multiClusterServices in default mode for TS

---

config/apis/cis/v1/types.go
pkg/controller/informers_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Adding the error status for resource status

Adding the error status for resource status

---

pkg/controller/validate.go

**Description**:  Log message enhancement
**Changes Proposed in PR**: Log message enhancement

Log message enhancement

---

pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Update monitor name for TS multicluster

update monitor name for TS

---

pkg/controller/multiClusterInformers.go
pkg/controller/worker.go

**Description**:  Fix for namespace label issues

Fix for namespace label issues

---

pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go

**Description**:  Fix for pool members not updating when service port and target ports are different

Improved service discovery in default mode

---

azure-pipelines.yaml
build-tools/Dockerfile.debian
build-tools/Dockerfile.debug
build-tools/Dockerfile.ubi
build-tools/rel-build.sh
config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/serviceTypeLB/README.md
docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/policy-with-pool-settings.yaml
docs/config_examples/customResource/serviceTypeLB/ServiceTypeLBWithPoolSettings/service-type-lb-with-poolsettings-in-policycr.yaml
docs/config_examples/customResource/serviceTypeLB/service-type-lb-with-custom-partition.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
go.mod
pkg/controller/backend.go
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/postManager.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Minor enhancements
**Changes Proposed in PR**: Minor enhancements

Minor enhancements

---

build-tools/Dockerfile.debian
docs/config_examples/multicluster/ServiceTypeLB/README.md
docs/config_examples/multicluster/ServiceTypeLB/sample-policy.yaml
docs/config_examples/multicluster/ServiceTypeLB/sample-policy2.yaml
docs/config_examples/multicluster/ServiceTypeLB/svc-lb1.yaml
docs/config_examples/multicluster/ServiceTypeLB/svc-lb2.yaml
docs/config_examples/multicluster/extendedConfigmap/global-spec-config-for-multicluster-default-mode-svcLB.yaml
pkg/clustermanager/clustermanager.go
pkg/clustermanager/types.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Support for discovering serviceTypeLB services in external cluster based serviceTypeLBDiscovery flag introduced in global ConfigMap

svcLB support for external clusters in default mode

---

pkg/controller/backend.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  Irule for traffic distribution in TS

Use irule for traffic distribution in TS

---

azure-pipelines.yaml
docs/cis-20.x/RELEASE-NOTES.rst

20.3.0 remove latest tag

---

pkg/controller/responseHandler.go

Remove false error log in default mode

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/multicluster/README.md
docs/upgradeProcess.md
f5-bigip-ctlr-operator/bundle/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml
helm-charts/f5-bigip-ctlr/Chart.yaml

**Description**:  Update CRD, helm and operator version
**Changes Proposed in PR**: Update CRD, helm and operator version

Update CRD, helm and operator version

---

docs/RELEASE-NOTES.rst
docs/config_examples/multicluster/customResource/transportServer/ts-with-extended-service-ha-svcs.yaml
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/validate.go
pkg/controller/validate_test.go
pkg/controller/worker.go

support ha services in extendedServiceReference (#3560)

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/nativeResourceWorker.go
pkg/controller/validate.go

**Description**:  Add validations for default mode in multiCluster
**Changes Proposed in PR**: Add validations for default mode in multiCluster

Add validations for default mode in multiCluster

---

pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

Support for service discovery of non multi-cluster resources in default mode

---

pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go

Support for the namespace removal for svcTypeLB

---

config/client/clientset/versioned/fake/register.go
config/client/clientset/versioned/scheme/register.go
pkg/clustermanager/clustermanager.go
pkg/clustermanager/types.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/controller_test.go
pkg/controller/eventNotifier.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/validate_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Changes Proposed in PR**: code refactoring for cluster informers

code refactoring for cluster informers

---

docs/config_examples/multicluster/ServiceTypeLB/README.md

Updating the example to be cluster independent

---

pkg/controller/clusterHandler.go
pkg/controller/constants.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/controller_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/validate_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

refactored the code for cluster handler

---

cmd/k8s-bigip-ctlr/main.go
pkg/controller/clusterHandler.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/controller_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/responseHandler.go
pkg/controller/routing.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/validate_test.go
pkg/controller/worker.go
pkg/controller/worker_test.go

refactored the code for handling common events from multiple clusters

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**: Support dots and dashes in object names aligned to AS3
**Changes Proposed in PR**: Supported dots and dashes in custom names
**Fixes**: resolves SR-00715269

SR-00715269 Support dots and dashes in vs name, hostgroup vs name, and pool name

---

pkg/controller/clusterHandler.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/node_poll_handler.go
pkg/controller/resourceConfig.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Handle informer recreation on kubeconfig expiry and secret update
fixes for multi cluster informers
Recreate informers on kubeconfig secret update

Handle informer recreation on kubeconfig expiry and secret update

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/TransportServer/ts-with-empty-nodeMemberLabel.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/node_poll_handler.go
pkg/controller/resourceConfig.go

**Description**:  support for empty node label
**Changes Proposed in PR**: support for empty node label

support for empty node label

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/config_examples/customResource/TransportServer/transport-server-with-tls/README.md
docs/config_examples/customResource/TransportServer/transport-server-with-tls/ts-with-tls-bigip-ref.yaml
docs/config_examples/customResource/TransportServer/transport-server-with-tls/ts-with-tls-secret-ref.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/backend.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/worker.go

**Description**: Add support for TLS in Transport Server
**Changes Proposed in PR**: Supported TLS for Transport Server
**Fixes**: resolves #3637

#3637 support for TLS in Transport Server

---

docs/RELEASE-NOTES.rst
pkg/controller/informers.go
pkg/controller/worker.go

**Description**: Service type: LoadBalancer IPs re-assigned when services are updated
**Changes Proposed in PR**: Handled the update event w.r.t the required service change
**Fixes**: resolves #3615

Service type: LoadBalancer IPs re-assigned when services are updated

---

pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  support implict service search in multiCluster mode
**Changes Proposed in PR**: support implict service search in multiCluster mode

support implict service search in multiCluster mode

---

pkg/controller/resourceConfig.go

**Description**:  Transport server pool members not populated with service port
**Changes Proposed in PR**: Handled the service port properly post service creation
**Fixes**: resolves #[#1170](https://gitswarm.f5net.com/cc/docs/-/issues/1170)

Transport server pool members not populated with service port

---

pkg/controller/resourceConfig.go
pkg/controller/worker.go

**Description**:  minor fixes for standalone mode

minor fixes for standalone ratio mode

---

pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go

**Description**:  fix implicit service discovery standalone mode

fix implicit service discovery standalone mode

---

docs/config_examples/multicluster/customResource/transportServer/ts-with-multiClusterServices.yaml
pkg/controller/multiClusterWorker.go
pkg/controller/resourceConfig.go
pkg/controller/worker.go

**Description**:  Fix for duplicate app created using the service type load balancer

Fix for duplicate app created using the service type load balancer

---

pkg/controller/statusUpdateUtils.go
pkg/controller/worker.go

**Description**:  Fix minor issues for non-multicluster loadbalancer service
**Changes Proposed in PR**: Fix minor issues for non-multicluster loadbalancer service

Fix minor issues for non-multicluster loadbalancer service

---

pkg/controller/resourceConfig.go

**Description**:  Fix to handle svc creation post VS/TS creation in default mode
**Changes Proposed in PR**: Fix to handle svc creation post VS/TS creation in default mode

Fix to handle svc creation post VS/TS creation in default mode

---

pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go

**Description**:  Fix informer handling in namespace label mode

Fix informer handling in namespace label mode

---

pkg/controller/clusterHandler.go
pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**: Fix for namespace label support in default mode

Fix for namespace label support in default mode

---

pkg/controller/clusterHandler.go
pkg/controller/informers.go
pkg/controller/multiClusterWorker.go
pkg/controller/responseHandler.go
pkg/controller/statusUpdateUtils.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Improve resource status update handling
**Changes Proposed in PR**: Improve resource status update handling

Improve resource status update handling

---

pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go

**Description**:  Fix for transport server pool name in multi cluster mode

Fix for transport server pool name in multi cluster mode

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/validate.go

**Description**:  Fix for transport server reprocessing on status update

Fix for transport server reprocessing on status update

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Description**:  Fix the ServiceAddress update in Transport server
**Changes Proposed in PR**: Restricted the TS and VS serverAddress modification.
**Fixes**: resolves #5016

Fix the ServiceAddress update in Transport server

---

pkg/controller/backend.go
pkg/controller/gtmBackend.go
pkg/controller/postManager.go

**Description**: Fix for CIS crash when bigip is busy and send the 201 status code

Fix for CIS crash when bigip is busy and send the 201 status code

---

pkg/controller/routing.go

**Description**:  fix target port handling for ts ab datagroup

fix target port handling for ts ab datagroup

---

pkg/controller/worker.go

**Description**:  handle vs processing with duplicate vs deletion

handle vs processing with duplicate vs deletion

---

pkg/controller/resourceConfig.go
pkg/controller/routing.go

**Description**:  Fix CIS not adding pool members for TS if different service port and target port

Fix CIS not adding default service namespace correctly

---

pkg/controller/worker.go

**Description**: Fix informer errors in external clusters with namespace-label

Fix informer errors in external clusters with namespace-label

---

pkg/controller/controller.go
pkg/controller/informers.go
pkg/controller/multiClusterInformers.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Fix for informer initialisation for multi cluster

Fix for informer initialisation for multi cluster

---

pkg/controller/resourceConfig.go
pkg/controller/routing.go
pkg/controller/worker.go

fix  insecure vs traffic and weight issue in default mode

---

pkg/controller/informers.go
pkg/controller/resourceConfig.go
pkg/controller/worker.go

**Description**:  Improve informer handling to avoid CIS crashes
**Changes Proposed in PR**: Improve informer handling to avoid CIS crashes

Improve informer handling to avoid CIS crashes

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**:  Improve the invaild resource requeue logic
**Changes Proposed in PR**: Improve the invaild resource requeue logic

Improve the invaild resource requeue logic

---

pkg/controller/nativeResourceWorker.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/worker.go

**Description**:  Fix for LB service processing in multiCluster environment
**Changes Proposed in PR**: Fix for LB service processing in multiCluster environment

Fix for LB service processing in multiCluster environment

---

pkg/controller/nativeResourceWorker.go
pkg/controller/worker.go

**Description**: 2.x stable bug fix
- fix routes not processed with default route group
- fix routes virtual server name format
- fix routes with namespace label not posting anything to BIGIP

2.x stable bug fix

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md

Reverts F5Networks/k8s-bigip-ctlr#3665

Revert "update release process docs"

---

docs/RELEASE-NOTES.rst
pkg/controller/controller.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Configuration errors reset VSAddress to None for all VirtualServers
**Changes Proposed in PR**: Added new vars and storing the vs address based on the unique keys
**Fixes**: resolves #3723

#3723 show vs address from none on successful configuration of errors

---

docs/RELEASE-NOTES.rst
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go

**Description**:  Avoid duplicate monitor creation for default mode.This fix required a bug fix from AS3 for https://my.f5.com/manage/s/article/K33604210 which limited sharing monitors for pools.
This is resolved in AS3 3.52 version.

pool monitor fix 

---

docs/RELEASE-NOTES.rst
pkg/controller/worker.go

**Description**:  handle kubeconfig secret update
**Fixes**: resolves #3727

handle kubeconfig secret update

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/controller/node_poll_handler.go
pkg/controller/node_poll_handler_test.go
pkg/controller/types.go
requirements.txt

fix static routes override

---

docs/RELEASE-NOTES.rst
pkg/controller/nativeResourceWorker_test.go
pkg/controller/resourceConfig.go

**Description**:  pool monitor fix

pool monitor fix

---

pkg/controller/resourceConfig.go

**Description**:  vs monitor name fix

vs monitor name fix

---

pkg/controller/resourceConfig.go

**Description**: fix vs monitor name

Fix vs monitorname

---

pkg/controller/node_poll_handler.go

**Description**:  calico cni fix for updating cis identifier

calico cni fix for updating cis identifier

---

docs/RELEASE-NOTES.rst
pkg/controller/clusterHandler.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/controller_test.go
pkg/controller/informers_test.go
pkg/controller/multiClusterHealthProbeManager_test.go
pkg/controller/multiClusterInformers_test.go
pkg/controller/multiClusterWorker_test.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler_test.go
pkg/controller/profile_test.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go
pkg/controller/validate_test.go
pkg/controller/worker_test.go

**Description**:  Reverted the status changes

Reverted the status changes

---

pkg/controller/types.go
pkg/controller/validate.go

**Description**:  fix for allowing svctypeLB same ip and port but different protocol
**Changes Proposed in PR**: fix for allowing svctypeLB same ip and port but different protocol
**Fixes**: resolves #3762

fix for allowing svctypeLB same ip and port but different protocol

---

docs/RELEASE-NOTES.rst
pkg/controller/types.go
pkg/controller/validate.go

**Description**:  fix svcTypeLB same IP and port with different protocol
**Fixes**: resolves #3762

fix svcTypeLB same IP and port with different protocol

---

config/apis/cis/v1/types.go
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/default-mode/IngressLink/README.md
docs/config_examples/multicluster/default-mode/IngressLink/ingresslink-with-existing-monitor.yaml
docs/config_examples/multicluster/default-mode/IngressLink/values.yaml
pkg/controller/resourceConfig.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**:  Ingresslink multicluster fixes
-  existing monitor reference support for ingresslink
-  fix for selector
**Fixes**: resolves #3739

Ingresslink multicluster monitor support

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/default-mode/IngressLink/README.md
docs/config_examples/multicluster/default-mode/IngressLink/ingresslink-with-existing-monitor.yaml
docs/config_examples/multicluster/default-mode/IngressLink/sample-multicluster-ingresslink.yaml
pkg/controller/resourceConfig.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  ingLink spec changes for multiclusterservices
1. ingLink spec changes for multiclusterservices
2. monitor creation for cluster pools
3. process affected IngressLink on secret updates

inglink spec fix

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResource/serviceTypeLB/README.md
docs/config_examples/customResource/serviceTypeLB/healthMonitor-with-bigip-reference-serviceTypeLB.yaml
docs/config_examples/customResource/serviceTypeLB/multiple-healthMonitors-serviceTypeLB.yaml
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/types.go

**Description**:  health monitor enhancements for serviceTypeLB
**Changes Proposed in PR**: health monitor enhancements for serviceTypeLB
**Fixes**: resolves #3779

fix: health monitor enhancements for serviceTypeLB

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md
pkg/controller/multiClusterHealthProbeManager.go
pkg/controller/requestHandler.go

support https for primary Endpoint

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/config_examples/multicluster/default-mode/IngressLink/README.md
docs/config_examples/multicluster/default-mode/IngressLink/ingresslink-with-existing-monitor.yaml
docs/config_examples/multicluster/default-mode/IngressLink/sample-multicluster-ingresslink.yaml
docs/config_examples/multicluster/default-mode/IngressLink/values.yaml
pkg/controller/as3Parser.go
pkg/controller/profile.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/validate.go
pkg/controller/worker.go
pkg/controller/worker_test.go

**Description**:  Ingresslink multicluster default mode support
1. Ingresslink multicluster support for default mode 
2. Retry request irule handling for 5xx errors
**Fixes**: resolves #3739

Ingresslink multicluster support

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
pkg/controller/requestHandler.go
pkg/controller/types.go

**Description**:  Added support for configuring refreshTokenInterval in deployment args for bigip token authentication

refresh token interval config

---

docs/RELEASE-NOTES.rst
pkg/controller/as3Parser.go
pkg/controller/types.go

**Description**:  Add virtual server name to pool description to help map vs and pools in bigip GUI
**Fixes**: resolves #3791

add vsname to pool decsription

---

cmd/k8s-bigip-ctlr/main.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/CustomResource.md
docs/upgradeProcess.md
pkg/controller/clusterHandler.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/informers.go
pkg/controller/informers_test.go
pkg/controller/multiClusterInformers.go
pkg/controller/nativeResourceWorker_test.go
pkg/controller/node_poll_handler_test.go
pkg/controller/resourceConfig_test.go
pkg/controller/statusUpdateUtils.go
pkg/controller/types.go
pkg/controller/worker_test.go

**Description**:  Support custom CRD label
**Changes Proposed in PR**: support custom CRD label
**Fixes**: resolves #3559

feat: support custom CRD label

---

pkg/controller/backend.go
pkg/controller/requestHandler.go
pkg/controller/responseHandler.go
pkg/controller/types.go
pkg/controller/worker.go

**Description**:  arp and gtm update using cccl

fix: arp and gtm update using cccl

---

cmd/k8s-bigip-ctlr/main.go
cmd/k8s-bigip-ctlr/main_test.go
cmd/k8s-bigip-ctlr/pythonDriver.go
pkg/controller/pythonDriver.go
pkg/controller/requestHandler.go
pkg/controller/types.go
pkg/securecreds/handleCredentials.go
requirements.txt

support secure credentials for bigip

---

pkg/controller/resourceConfig.go

Ingress link log fix

---

pkg/controller/as3Parser.go

**Description**:  handle pool description char limit

handle pool description char limit

---

azure-pipelines.yaml

**Description**:  updated with bot account for GitHub charts repo service connection in azure pipelines

charts sa update

---

pkg/controller/as3Handler.go

fix: skipping the gtm partition while creating ltm adc

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
docs/upgradeProcess.md

**Description**:  add crd validation to reject partition update

add crd validation to reject partition update

---

pkg/controller/as3Handler.go
pkg/controller/as3Handler_test.go
pkg/controller/backend.go
pkg/controller/requestHandler.go
pkg/controller/types.go

**Description**: Avoid posting GTM config to LTM bigip in case of external GTM
**Changes Proposed in PR**: Avoid posting GTM config to LTM bigip in case of external GTM

fix: stop posting GTM config to LTM bigip in case of external GTM

---

azure-pipelines.yaml

**Description**:  Disable documentation checks

Disable documentation checks

---

pkg/controller/backend.go

fix: posting of GTM config with CCCL GTM agent

---

docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

fix schema

---

pkg/controller/requestHandler.go

**Description**:  multicluster HA cis fix

multicluster HA cis fix

---

requirements.txt

**Description**:  Update f5-cccl version
**Changes Proposed in PR**:  Updated f5-cccl version

fix: update f5-cccl version

---

build-tools/Dockerfile.debian
build-tools/Dockerfile.ubi

**Description**:  Remove shell access from image
* Removed shell access from UBI image
* Removed shell access from Debian image

fix: remove shell access from image

---

docs/RELEASE-NOTES.rst
docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
docs/upgradeProcess.md
helm-charts/f5-bigip-ctlr/Chart.yaml

**Description**:  Release notes update for 2.20 release.
* Add example and documentation links for each newly added feature.
* Add Manifest file links
* Update the CRD yaml file with the latest CRD.

fix: release notes for 2.20

---

docs/RELEASE-NOTES.rst
pkg/controller/routing.go
requirements.txt

fix: policy not adding in default mode

---

docs/RELEASE-NOTES.rst
pkg/controller/validate.go
pkg/controller/worker.go

fix: crash issue with hostless and hostAliases vs

---

docs/RELEASE-NOTES.rst
docs/config_examples/configmap/user-defined-configmap/README.md
pkg/agent/as3/as3ConfigMap.go
pkg/agent/as3/as3Manager_test.go
pkg/appmanager/appManager.go
pkg/appmanager/appManager_test.go
pkg/resource/resourceConfig.go
pkg/resource/resourceConfig_test.go
pkg/resource/types.go

support for pool member priority group label for configmaps

---

pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/resourceConfig_test.go
pkg/controller/routing.go
pkg/controller/worker_test.go

**Description**:  add path in pool name
**Changes Proposed in PR**: add path in pool name

fix: add path in pool name

---

pkg/controller/worker.go

**Description**:  fix crash for rd cluster mode

fix crash for rd cluster mode

---

docs/RELEASE-NOTES.rst
docs/upgradeProcess.md

update release notes for 2.20.1

---

pkg/bigiphandler/bigiphandler.go
pkg/bigiphandler/bigiphandler_test.go
pkg/controller/controller.go
pkg/controller/controller_suit_test.go
pkg/controller/informers.go
pkg/controller/mutator.go
pkg/controller/mutator_test.go
pkg/controller/server.go
pkg/controller/validate.go
pkg/controller/validate_test.go

**Description**:  Policy validation is added for the current supported objects.

Policy validation

---

go.mod
go.sum
pkg/bigiphandler/bigiphandler.go
pkg/bigiphandler/bigiphandler_test.go
pkg/controller/validate.go
pkg/controller/validate_test.go
pkg/controller/worker_test.go
vendor/github.com/f5devcentral/go-bigip/apm.go
vendor/github.com/f5devcentral/go-bigip/asm.go
vendor/github.com/f5devcentral/go-bigip/ltm.go
vendor/modules.txt

**Description**:  improved the policy validation and added the remaining objects for policy CR.

feat: improved the policy validation

---

pkg/controller/multiClusterWorker.go
pkg/controller/nativeResourceWorker.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/validate.go
pkg/controller/worker.go

**Description**: SvcLB internal bug fixes
**Changes Proposed in PR**:  Fixed the following LB type service issues:
1. Incorrect processing of serviceTypeLB with multiple ports
2. Flaw in resource-service cache management for serviceTypeLB with multiple ports

SvcLB internal bug fixes

---

pkg/controller/worker.go

**Description**:  Improve the performance of processing VS with host group
**Changes Proposed in PR**: Ignore already processed Virtual Servers on Creation of tls profiles, custom policy

improve performance while processing the virtual servers with host group

---

docs/RELEASE-NOTES.rst
pkg/agent/as3/as3ConfigMap.go
pkg/agent/as3/as3Manager.go
pkg/agent/as3/postManager.go
pkg/controller/as3Handler.go

**Description**:  Set per-tenant AS3 logs level for improved operator visibility.
**Changes Proposed in PR**: Added and updated logs 
**Fixes**: resolves #3887

Set per-tenant AS3 logs level for improved operator visibility.

---

config/apis/cis/v1/types.go
docs/RELEASE-NOTES.rst
docs/config_examples/customResource/Policy/policy-with-empty-http2-profile.yaml
docs/config_examples/customResource/VirtualServer/http2/vs-with-empty-http2-profile.yaml
docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml
pkg/controller/as3Parser.go
pkg/controller/resourceConfig.go
pkg/controller/types.go
pkg/controller/worker_test.go

feat: support none value for http2 profile

---

pkg/controller/node_poll_handler.go
pkg/controller/routing.go

**Description**:  fix irule for redirect

fix irule for redirect

---

pkg/controller/worker.go

revert the host group performance changes

revert performance improvement changes

---

docs/config_examples/rbac/Namespaced-RBAC/README.md
docs/config_examples/rbac/Namespaced-RBAC/cluster_rbac.yaml
docs/config_examples/rbac/Namespaced-RBAC/configmap_namespace_rbac.yaml
docs/config_examples/rbac/Namespaced-RBAC/namespace_rbac.yaml
docs/config_examples/rbac/Namespaced-RBAC/secret_role_namespace_rbac.yaml
docs/config_examples/rbac/Namespaced-RBAC/serviceaccount.yaml
docs/config_examples/rbac/README.md
docs/config_examples/rbac/clusterrole.yaml

**Description**:  Documentation and examples added for namespace scoped RBAC  configuration.

Document namespaced rbac example for CIS
